Практика по 5 модулю.
IlyaOrlov/PythonCourse2.0_May23 pull request #114
Opened 2023-06-12 16:07 UTC by LoginovaMaria

2023-06-12 18:57 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.4.py
> +def del_int(arr1, x):
По заданию **x** - это НЕ индекс столбца в матрице, это некоторая цифра, которая есть в матрице.
И удалить надо столбцы, содержащие эту цифру.
Например, цифру 2 в arr1 содержит 1-й столбец.

2023-06-14 11:23 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.3.py
> +str = "зима и лето в одном цвете"
Вы уже писали об этом к другой задаче, но я не специально игнорирую...имя этой переменной автоматически придумывается если задание связано со строкой) надо запомнить уже.

2023-06-14 11:24 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.4.py
> +def del_int(arr1, x):
Переделала

2023-06-14 12:02 UTC, IlyaOrlov requested changes
Есть вопрос!

2023-06-14 12:02 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.4.py
> +    return arr1
Вопрос на понимание: меняется ли в этой функции исходная матрица arr1, заданная в стр.17? Или все изменения происходят только с одноименной локальной копией этой матрицы?

2023-06-14 14:05 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.4.py
> +    return arr1
Второе - изменения происходят только с одноименной локальной копией этой матрицы.
И у меня вопрос-уточнение, при отладке выдаётся предупреждение, хотела скрин прислать...подскажите тут есть возможность его прикрепить?

2023-06-14 14:20 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.4.py
> +    return arr1
На самом деле, матрица arr1 - это список - изменяемый тип данных. Локальная переменная arr1 указывает на ЭТОТ ЖЕ список. Поэтому все изменения ВНУТРИ списка будут видны как через локальную переменную arr1, так и через одноименную глобальную переменную. Если не возвращать здесь arr1, а просто вывести на экран в стр.20 глобальную arr1 - мы увидим тот же результат.
Да, картинку можно перетащить прямо сюда, в окно диалога.

2023-06-15 08:18 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.4.py
> +    return arr1
Добрый день!
Попробовала вернуть глобальную arr1 на экран, вернулось тоже самое, как и Вы и написали.
![5 4_1](https://github.com/IlyaOrlov/PythonCourse2.0_May23/assets/133433954/e7a9e223-0a60-430b-80ab-e4ee31f10f4e)
не пойму о чём предупреждение... имя 'lst' не объявлено если дословно

2023-06-15 10:02 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.4.py
> +    return arr1
Очень интересно. Изначально массив вместо arr1 был назван lst, потом переименован, не помню чтоб добавляла lst в список watcher, т.к. пользоваться этим инструментом не умею), сейчас удалила lst из списка Watches. Спасибо!

2023-06-15 10:07 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.4.py
> +    return arr1
Видимо, случайно получилось.

2023-06-15 14:34 UTC, IlyaOrlov requested changes
ОК. Но есть некоторые замечания.

2023-06-15 14:34 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.5.py
> +                f.close()
f.close() здесь и в стр.18 не нужен. Раз у нас есть with - файл закроется "автоматически" при выходе из тела with.

2023-06-15 14:34 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.5.py
> +a = '\t'
Константы стоит именовать большими буквами. А вообще, чтоб функция не обращался к глобальным переменным, лучше пробел и табуляцию сделать аргументами этой функции.

2023-06-15 20:26 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.5.py
> +                sys.exit(0)
Что ж так сразу программу-то закрывать? Можно просто из функции выйти через return!
И в стр.20 тоже.
С закрытие программы неестественным путём, вообще, стоит быть поосторожнее. Запустите такую функцию на каком-нибудь своём сайте, чтоб в пользовательских данных символы автоматически корректировать., а пользователь не укажет ни пробелы, ни табуляцию... И опа... сайт вдруг упал)

2023-06-15 20:27 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.5.py
> +A = '\t'
ОК, только тогда и имена надо со смыслом давать. Например, TAB_SYM или SPACE_SYM.

2023-06-16 17:59 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.5.py
> +                sys.exit(0)
Поняла, почему-то этот самый логичный вариант return в голову вообще не пришёл)

2023-06-16 18:05 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.5.py
> +A = '\t'
Исправила.

2023-06-16 18:07 UTC, IlyaOrlov requested changes
Ещё один нюанс.

2023-06-16 18:07 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_5.5.py
> +        if k == 1:
Здесь, видимо, должна быть переменная **choice**, а не **k**. Обращаться из функции к глобальным переменным нехорошо.

2023-06-16 20:10 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_5.5.py
> +        if k == 1:
Не заметила, исправила.

2023-06-17 06:50 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-06-17 06:50 UTC, merged