Задачи 4 и 5 к лекции 5
IlyaOrlov/PythonCourse2.0_May23 pull request #115
Opened 2023-06-12 18:23 UTC by DmitriySapegov

2023-06-12 19:09 UTC, IlyaOrlov requested changes
Хорошо. Но есть, что улучшить.

2023-06-12 19:09 UTC, IlyaOrlov commented on Practice/Sapegov/Sap5.4.py
> +        for index2, j in enumerate(i):
Этот цикл стоит сделать более гибким (возможно, с использованием while).
Сейчас, вот для таких вводных алгоритм не работает:
```python
matrix = [[1, 2, 2], [1, 1, 1]]
number = 2
```
Выдаётся: `[[1, 2], [1, 1]]`

2023-06-12 19:09 UTC, IlyaOrlov commented on Practice/Sapegov/Sap5.5.py
> +with open('for5.5.txt') as f:
Работа с внешней памятью (в данном случае с файлом на жестком диске, который при открытии еще должен загрузиться в оперативную память), всегда стоит дороже, чем напрямую с оперативной.
Поэтому имеет смысл сначала проверить, что ввод пользователя корректный. И только в этом случае выполнять работу с файлом (читать из него и записывать в него результат).

2023-06-13 19:45 UTC, DmitriySapegov commented on Practice/Sapegov/Sap5.4.py
> +        for index2, j in enumerate(i):
Не тестил повторяющиеся элементы друг за другом. Действительно работало не корректно.
Поправил. Но с учетом сегодняшних знаний об эффективности алгоритмов - грустно смотрю на этот код.

2023-06-13 19:45 UTC, DmitriySapegov commented on Practice/Sapegov/Sap5.5.py
> +with open('for5.5.txt') as f:
Звучит очень логично! Исправил

2023-06-13 20:25 UTC, IlyaOrlov commented on Practice/Sapegov/Sap5.4.py
> +        for index2, j in enumerate(i):
Стоит смотреть веселее) Т.к. особо эффективней решить эту задачу и нельзя. В любом случае придётся пройтись по всей матрице (для квадратной матрицы это уже n**2). Плюс неизбежные затраты на доп. проход по матрице  для удаления соответствующих столбцов (не считая затрат на доступ по индексу, это ещё одно умножение на n). Так и получается n^3.

2023-06-13 20:26 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-06-13 20:26 UTC, merged