Tanacheva branch
IlyaOrlov/PythonCourse2.0_May23 pull request #116
Opened 2023-06-12 20:45 UTC by JuliaTanacheva

задание для лекции 6

2023-06-13 08:18 UTC, IlyaOrlov requested changes
Хорошо, но есть вопрос.

2023-06-13 08:18 UTC, IlyaOrlov commented on Practice/Tanacheva/task6.1.py
> +    print("===========")
Просто интересно... этот print на всякий случай добавлен?

2023-06-14 19:31 UTC, JuliaTanacheva commented on Practice/Tanacheva/task6.1.py
> +    print("===========")
Да, это строка лишняя. Я проверяла, как будет выводиться , если поставить эту строку в другом месте. Меня смущает , что вывод результата выглядит как "====", "=====" и только потом результат функции. Из задания кажется ,что вывод должен быть "====", результат, "=====" .

2023-06-15 06:58 UTC, IlyaOrlov commented on Practice/Tanacheva/task6.1.py
> +    print("===========")
Теме не менее, решение правильное, хотя и не особо иллюстративное) Ведь по заданию "====" должно выводится до и после ВЫЗОВА исходной функции, а не до и после вывода её результата на экран.
Сначала (стр.4) выводится "====", потом (стр.5) вызывается функция, которая сама по себе ничего не выводит, затем (стр.7) выводится ещё раз "====". И только после всего этого, когда результат функции со всеми обертками возвращается в стр.18, этот результат и выводится. 
Для иллюстративности можно повесить этот декоратор на функцию, в которой есть print. Тогда порядок будет вообще очевиден.

2023-06-15 07:02 UTC, IlyaOrlov commented on Practice/Tanacheva/task6.1.py
> +    print("===========")
Если всё понятно, то могу зачесть задание (замечаний больше нет).

2023-06-16 20:28 UTC, JuliaTanacheva commented on Practice/Tanacheva/task6.1.py
> +    print("===========")
Да понятно. Спасибо за объяснение.

2023-06-17 06:50 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-06-17 06:50 UTC, merged