HW_6_Fedorov
IlyaOrlov/PythonCourse2.0_May23 pull request #119
Opened 2023-06-14 18:59 UTC by Fed909

2023-06-15 07:26 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.1.py
> +t1 - t2
Кстати, хорошая получается иллюстрация на тему использования магических методов.
t1 - t2 работает, но, согласитесь, выглядит экзотично.
Когда мы применяем вычитание, например, к числам, мы ожидаем несколько иного поведения. Например, здесь
```python
x = 10
y = 20
y - x
```
последняя операция никак не поменяет ни **x**, ни "y"... просто создастся новое число.
Мы ещё обсудим сегодня аспекты применения магических методов. Пока я бы предложил здесь использовать операцию `-=`, которой (неожиданно) соответствует отдельный магический метод `__isub__()`.

2023-06-17 06:48 UTC, IlyaOrlov requested changes
Супер! Оставил ещё несколько замечаний по мелочи.

2023-06-17 06:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.1.py
> +    @staticmethod
Пустой строки сверху не хватает.  Чтоб уж совсем всё красиво было!

2023-06-17 06:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.1.py
> +        hp = random.choice([True, False])
Строки 41-46 коротенькие. Можно их упаковать в одно выражение:
```python
return 10 if random.choice([True, False]) else 0
```
И, кстати, чуть быстрее отработает randint(0, 1):
```python
return 10 if random.randint(0, 1) else 0
```
Потому что random.choice(lst) - это lst[random.randint(0, len(lst) - 1)].

2023-06-17 06:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.1.py
> +class Tanks:
По [PEP8](https://peps.python.org/pep-0008/#blank-lines:~:text=Surround%20top%2Dlevel%20function%20and%20class%20definitions%20with%20two%20blank%20lines.) определения классов, как и функций, нужно обособлять двумя пустыми строками.

2023-06-17 06:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.2.py
> +        return self._weight + other._weight
Метод должен вернуть "**утку**, вес которой равен сумме весов 2-х уток".

2023-06-17 06:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.3.py
> +            file = open(self.filepath)
С файлом стоит работать через with. И код покороче, и файл точно не забудем закрыть, и сразу видна область использования файла.

2023-06-17 06:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.3.py
> +        open(self.filepath, "w").write(value)
Здесь тоже стоит открывать файл, используя with (да, в одну строку написать уже не получится).
В принципе, при таком обычном способе открытия файла, всё, что мы в него пишем, будет практически сразу писаться на жесткий диск. Программа закроется, файловый объект удалится, а на диске всё останется. Даже если мы забудем close().
Но при работе с большими объёмами данных очень часто используется буферизация (параметр buffering), когда все данные сначала пишутся в память и сбрасываются на жесткий диск при достижении заданного объёма. Если при таком способе забыть вызвать close(), который кроме, собственно, закрытия файла отвечает за дозапись содержимого буфера в памяти на жёсткий диск, то данные в буфере (всё, что мы старались, писали) пропадут.
Поэтому на всякий случай стоит не забывать использовать close(), а ещё лучше пользоваться with. Мало ли, вдруг мы потом всё же решим включить буферизацию в нашем коде.

2023-06-17 09:12 UTC, Fed909 commented on Practice/Fedorov/HW_6/6.1.py
> +class Tanks:
Ага, я ставил, но тут мне Pycharm пишет следующее Remove redundant parentheses, если я ставлю скобки

2023-06-17 09:29 UTC, Fed909 commented on Practice/Fedorov/HW_6/6.2.py
> +        return self._weight + other._weight
Так и знал, что неверно решил)

2023-06-17 11:20 UTC, AChertova commented on Practice/Fedorov/HW_6/6.1.py
> +class Tanks:
Пустые строки) скобки при создании класса действительно не нужны :)

2023-06-18 07:51 UTC, IlyaOrlov requested changes
Остались некоторые замечания.

2023-06-18 07:51 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.1.py
> +class Tanks:
Да, конкретно, 2 пустые строки между стр.1 (с импортом) и 2 (начало определения класса).

2023-06-18 07:51 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.2.py
> +        return self._weight + other._weight
Не то чтобы неверно, но не совсем очевидно для потенциального пользователя данного класса) Складываем уток  - получаем число.

2023-06-18 14:49 UTC, IlyaOrlov commented on Practice/Fedorov/HW_6/6.2.py
> +
И здесь ещё пустую строку)

2023-06-18 14:57 UTC, IlyaOrlov approved these changes
Идеально) Зачтено!

2023-06-18 14:57 UTC, merged