Задание к 5 лекции
IlyaOrlov/PythonCourse2.0_May23 pull request #121
Opened 2023-06-15 11:27 UTC by AnnaKapralova

Задание 5.1

2023-06-15 13:43 UTC, AnnaKapralova commented
Добавила задание 6.1

2023-06-15 19:59 UTC, IlyaOrlov requested changes
Хорошо. Но несколько нюансов отметил.

2023-06-15 19:59 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz6.1.py
> +    def add_speed(emp, bonus):
Здесь и в add_firing_range: первый аргумент метода (указатель на экземпляр) [следует называть self](https://peps.python.org/pep-0008/#:~:text=Always%20use%20self%20for%20the%20first%20argument%20to%20instance%20methods.).

2023-06-15 19:59 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz6.1.py
> +        self. weight = weight1
Лишний пробел между точкой и weight.

2023-06-15 19:59 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz5.1.py
> +        lst[minimum], lst[i] = lst[i], lst[minimum]
А если minimum равен i, мы его так и будем самого с собой местами менять?

2023-06-15 19:59 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz5.1.py
> +    for i in range(len(lst)):
Мелочь, но всё же... здесь достаточно идти до len(lst) - 1.

2023-06-16 11:18 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz6.1.py
> +        self. weight = weight1
Исправила

2023-06-16 11:19 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz6.1.py
> +    def add_speed(emp, bonus):
Ок)

2023-06-16 11:33 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz5.1.py
> +    for i in range(len(lst)):
Исправила

2023-06-16 11:54 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz5.1.py
> +        lst[minimum], lst[i] = lst[i], lst[minimum]
ну это же частный случай получается)

2023-06-16 15:23 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz5.1.py
> +        lst[minimum], lst[i] = lst[i], lst[minimum]
А это уж как повезет) Окажется список из миллиона элементов сразу отсортированным (или почти отсортированным)... и всё - миллион лишних перестановок.
А перестановка (операция записи, причем двойная) всегда дороже, чем проверка (операция чтения).

2023-06-17 11:15 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz5.1.py
> +        lst[minimum], lst[i] = lst[i], lst[minimum]
Исправила)

2023-06-17 11:16 UTC, AChertova commented on Practice/AKapralova/KapralovaDz6.1.py
> +
Какое может быть предназначение у этих атрибутов класса, если у экземпляров создаются аналогичные атрибуты?

2023-06-17 11:50 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz6.1.py
> +
Они определяют значения только одного базового объекта.  А когда атрибут определен в экземпляре, параметры могут быть использованы в нескольких объектах, и каждый получается индивидуальным.

2023-06-17 18:54 UTC, AChertova commented on Practice/AKapralova/KapralovaDz6.1.py
> +
Не совсем так. Для иллюстрации приведу пример: набор учеников 10А класса какой-нибудь школы. Класс тут является как раз моделью. Атрибут класса - цифра 10 и буква А, может быть набор стандартных учебных предметов. Они будут автоматически применяться _**к каждому**_ ученику класса. Т.е. классовые атрибуты имеют _**одинаковое**_ значение для всех учеников(экземпляров) класса. Но в целом сам по себе класс - абстракция, в отличии от самих учеников(экземпляров). У каждого отдельного ученика будет свое ФИО, профильный набор предметов, документы и другие личные особенности. Эти параметры мы обязательно укажем в "личном деле"  (при создании экземпляра, раз указали __init__), иначе  ученика просто не смогут зачислить (создать экземпляр). Как тут не может существовать "базового ученика" с пустыми значениями, так и в вашем случае нет базового экземпляра. В целом указание дублирующих параметров класса на результат работы кода не повлияет.  Но, думаю, что осветить этот момент было не лишним)

2023-06-18 07:47 UTC, IlyaOrlov approved these changes
Замечания решены. Вопросы выяснены. Отлично)

2023-06-18 07:47 UTC, merged