Задание к 6 лекции
IlyaOrlov/PythonCourse2.0_May23 pull request #126
Opened 2023-06-19 07:48 UTC by AnnaKapralova

Задание 6.2

2023-06-19 08:24 UTC, AChertova commented on Practice/AKapralova/KapralovaDz6.2.py
> +        return summa
По условию задачи функция должна возвращать именно утку, вес которой равен сумме, а не просто сумму

2023-06-19 12:03 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz6.2.py
> +        return summa
ок) переделала

2023-06-19 12:04 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz6.2.py
> +d1.__repr__()
Поняла. Исправила.

2023-06-19 12:59 UTC, AnnaKapralova commented
Добавила 6.3

2023-06-19 15:41 UTC, AChertova commented on Practice/AKapralova/KapralovaDz6.2.py
> +d1.__repr__()
Не совсем. Нам уже нет необходимости прописывать print через форматную строку, мы просто вносим наш объект в функцию print (как у вас в строке 51 и мы видим результат - имя и вес утки). И еще момент!
В задании перечислены необходимые методы экземпляров - метод выводящий имя и вес утки и метод __repr__. Все таки стоит то, что Вы возвращаете из __repr__ вынести в отдельную функцию без магического метода. А на __repr__ можно как раз вывести то, что у вас внутри print сейчас или указать что-то еще другое. Но тогда 51 строку надо будет подправить, чтобы лексически грамотно получилось на выходе)

2023-06-19 19:25 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz6.2.py
> +d1.__repr__()
Добавлю ещё свою интерпретацию замечания) Код в строках 37 и 42 повторяется с небольшими нюансами. Стоит сделать отдельный метод типа def say_hello(), который выводит приветствие в указанном формате, подставляя данные конкретной утки.

2023-06-19 19:27 UTC, IlyaOrlov requested changes
Всё супер! По 6.3 замечаний нет, по 6.2 - нужно одно небольшое улучшение.

2023-06-20 10:01 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz6.2.py
> +d1.__repr__()
Исправила

2023-06-20 20:16 UTC, IlyaOrlov requested changes
Ещё один нюанс!

2023-06-20 20:16 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz6.2.py
> +        print(f"Привет, меня зовут уточка {self.name}, мой вес {self.weight} кг.")
Я предполагал, что говорить "Привет" уточка будет только здесь, в `say_hello()`, а в `__repr__()` же будет выводиться, что и раньше (просто имя и вес).
Если хотите, чтоб строка была одинаковой и здесь и в `__repr__()` , не стоит дублировать код. Можно здесь просто написать print(self), и строка из `__repr__()` сюда и подставится.

2023-06-21 09:53 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz6.2.py
> +        print(f"Привет, меня зовут уточка {self.name}, мой вес {self.weight} кг.")
Столько разных вариантов, как прописать код...а результат вывода - одинаковый(
Я уже немного запуталась, что именно нужно. Прописала два варианта, один закомментирован.

2023-06-21 12:01 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz6.2.py
> +        print(f"Привет, меня зовут уточка {self.name}, мой вес {self.weight} кг.")
Оба варианта правильные)
Главное, чтоб было меньше кода! Тем более, повторяющегося.

2023-06-21 12:02 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-06-21 12:02 UTC, merged