Задачи 1 и 2 к лекции 7
IlyaOrlov/PythonCourse2.0_May23 pull request #128
Opened 2023-06-19 19:21 UTC by DmitriySapegov

Во второй задаче не понял слова на лекции - использовать максимальное наследование.
По идее можно обойтись вообще без init в Pupil, т.к. переопределяем только метод solve_task.
Возможно не так понял задачу.

2023-06-19 19:43 UTC, IlyaOrlov requested changes
Немного уточню 2-е задание.

2023-06-19 19:43 UTC, IlyaOrlov commented on Practice/Sapegov/Sap7.2.py
> +        time.sleep(random.randint(3, 6))
Pupil должен подумать и тоже сказать "I'm not ready yet") И вот, тут как раз стоит обратиться к родительскому методу (только придётся выбирать между super и staticmethod;))
Смысл всего этого: сколько бы у Man ни было наследников, если они будут завязаны на родительский solve_task, мы сможем менять поведение сразу у них у всех через всего один метод класса Man. Иногда такой функционал может быть весьма полезным.

2023-06-21 19:55 UTC, DmitriySapegov commented on Practice/Sapegov/Sap7.2.py
> +        time.sleep(random.randint(3, 6))
Все, теперь понятно! Не понял сперва, что должен и Pupil говорить)
Поправил

2023-06-22 06:39 UTC, IlyaOrlov approved these changes
Всё отлично! Зачтено.

2023-06-22 06:39 UTC, merged