Fedorov HW_7
IlyaOrlov/PythonCourse2.0_May23 pull request #130
Opened 2023-06-21 17:51 UTC by Fed909

2023-06-22 03:27 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +        self.balance = float(balance)
Наверное, не стоит давать пользователю класса доступ к балансу напрямую. Попробуйте использовать property)

2023-06-22 03:32 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +
Лишняя пустая строчка

2023-06-22 03:36 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +        pass
Наверное, подразумевается, что тут мы совершаем какие-либо операции? Стоит их вызвать так, как Вы бы делали это в коде далее. Можно подписать на print, что это онлайн-операция)

2023-06-22 03:39 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +    i += 1
Для подобных обходов лаконичнее бы был цикл for

2023-06-22 03:40 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +
Многовато пустых строк)

2023-06-22 15:13 UTC, Fed909 commented on Practice/Fedorov/HW_7/7.3.py
> +    i += 1
Да, что-то я тут затупил :)

2023-06-26 04:57 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +        pass
Все таки хотелось бы, чтобы в процессе вызова self.online_payments происходило списание средств. А то payments странный предмет, они вроде есть, но и их вроде нет ;)

2023-06-26 05:01 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +
Но одна все таки нужна) как и в 7.2

2023-06-26 14:57 UTC, IlyaOrlov requested changes
Тоже добавил некоторые замечания.

2023-06-26 14:57 UTC, IlyaOrlov commented on Practice/Fedorov/HW_7/7.3.py
> +        self.name = name
Имя тоже стоит сделать защищенным. И, например, завести для него геттер, чтоб показать пользователям класса, что имя банкомата по ходу программы меняться не должно.

2023-06-26 14:57 UTC, IlyaOrlov commented on Practice/Fedorov/HW_7/7.3.py
> +class BaseATM(ATM):
Обычно Base добавляют в имя как раз родительского класса)

2023-06-27 20:33 UTC, Fed909 commented on Practice/Fedorov/HW_7/7.3.py
> +
Пустая строка есть :)

2023-06-27 20:33 UTC, Fed909 commented on Practice/Fedorov/HW_7/7.3.py
> +        pass
Онлайн платежи просто к балансу внутри банкомата никак не относятся мне кажется, ну ладно :)

2023-06-28 00:11 UTC, IlyaOrlov commented on Practice/Fedorov/HW_7/7.3.py
> +        print("Запрещено менять баланс")
Достаточно просто не реализовывать setter:) А то получается, что setter есть, но он не работает.

2023-06-28 00:11 UTC, IlyaOrlov commented on Practice/Fedorov/HW_7/7.3.py
> +        pass
Логично. Видимо, произошло недопонимание - путаница между счётом клиента и балансом банкомата. Баланс банкомата, конечно, меняться не должен.

2023-06-28 00:12 UTC, IlyaOrlov requested changes
Всё супер! Осталось разрешить нюанс с онлайн-платежами и сеттером.

2023-06-28 06:12 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +        pass
Я так поняла, что мы вызываем/совершаем онлайн-платеж. Что-то оплачиваем, вследствие баланс изменится? Как Вы видите функционал этого метода? Придем к общему знаменателю

2023-06-28 11:45 UTC, AChertova commented on Practice/Fedorov/HW_7/7.3.py
> +        pass
Убедили, оставим как есть в таком случае)

2023-06-28 17:13 UTC, merged