дз №7, задача 3
IlyaOrlov/PythonCourse2.0_May23 pull request #131
Opened 2023-06-21 20:02 UTC by AlenaStupina

2023-06-22 06:52 UTC, IlyaOrlov requested changes
Есть несколько вопросов!

2023-06-22 06:52 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +class ATMCashInOut(ATM):
А здесь payments не нужно переопределять?

2023-06-22 06:52 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +        self.__summa = summa
Вопрос на понимание: почему атрибут summa объявлен именно приватным, а не просто защищённым?

2023-06-22 06:52 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +    operations = ['снятие наличных', 'внесение наличных', 'баланс', 'онлайн-платеж']
Операции, вроде как, не меняются по ходу работы программы...;)

2023-06-22 07:01 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +class ATMCashInOut(ATM):
Я считаю, что ненужно, т.к. данный тип операции этим классом банкоматов не поддерживается

2023-06-22 07:04 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +        self.__summa = summa
потому что summa не должна меняться пользователем и дочерними классами напрямую (ну кроме методов, ее изменяющих),  не должно быть прямого доступа к этому атрибуту извне, задали один раз при создании объекта и все, иначе меняется логика программы

2023-06-22 07:06 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    operations = ['снятие наличных', 'внесение наличных', 'баланс', 'онлайн-платеж']
вы про то, что можно использовать не список?
а так , ну как не меняются - для разного типа банкоматов (у нас их два) свои операции. Или я не поняла вопрос...

2023-06-22 07:07 UTC, AlenaStupina commented
Оставила комментарии к вопросам

2023-06-22 07:16 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
Этот алгоритм вывода типа банкоматов и их кол-ва для каждого вида банка можно было как-то проще реализовать? я так понимаю, что у него сложность алгоритмическая не очень, хоть и используется словарь.

2023-06-22 07:41 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +class ATMCashInOut(ATM):
Принято.

2023-06-22 07:42 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +    operations = ['снятие наличных', 'внесение наличных', 'баланс', 'онлайн-платеж']
Да, кортеж тогда больше подходит.

2023-06-22 07:44 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +        self.__summa = summa
ОК, согласен. Но ещё стоит обратить внимание, что в методах дочерних классов также не будет доступа к атрибуту summa. Т.е. в них нельзя будет поменять правила работы с этой суммой.

2023-06-22 07:50 UTC, IlyaOrlov requested changes
Стоит кое-то оптимизировтаь.

2023-06-22 07:50 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
Да, можно было в одном цикле всю информацию собрать за один проход по lst_obj.
```python
d[i.bank] += 1
и тут же
b[type(i).__name__] += 1
```

2023-06-22 08:39 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    operations = ['снятие наличных', 'внесение наличных', 'баланс', 'онлайн-платеж']
Я вспомнила, почему оставила список - если появится третий вид банкоматов и у него появится еще операция какая-нибудь (не знаю правда какая)) ), чтобы в описании этого нового класса можно было задать атрибут operations ,  унаследовав его из родительского и добавив к нему новую операцию.

2023-06-22 08:40 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +        self.__summa = summa
да, я это понимаю. Для данной задачи посчитала, что все операции  с суммой уже реализованы... Думаете, лучше сделать защищенным?

2023-06-22 08:42 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
Вчера пыталась, видимо в ночи уже не очень соображалось, попробую еще раз, спасибо

2023-06-22 10:40 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +    operations = ['снятие наличных', 'внесение наличных', 'баланс', 'онлайн-платеж']
Да, но неизменяемый тип данных сделать безопаснее. Тем более, добавить новую операцию в новом классе можно так:
```python
class NewATM(ATM):
    operations = ATM.operations + ("new operation", )
```

2023-06-22 10:42 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +        self.__summa = summa
Нет. Можно оставить и закрытым. Главное, понимать, какие правила для пользователей Вашего класса Вы таким образом задаёте.

2023-06-22 12:40 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    operations = ['снятие наличных', 'внесение наличных', 'баланс', 'онлайн-платеж']
согласна, а я зациклилась на том, что кортеж - неизменяемый тип данных...

2023-06-22 12:43 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +        self.__summa = summa
Я понимаю)

2023-06-22 13:09 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
либо в выражении b[type(j).__name__] += 1 
вместо type(j).__name__
использовать f'{type(j).__name__}-{j.bank}'

2023-06-22 15:18 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
поправка опечатки в предпоследнем комментарии:
 d = {'bank':  {'вид банкомата': 'кол-во 1шт' }}

2023-06-22 18:49 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
не совсем поняла, о чем Вы, я никуда не нажимала. актуален

2023-06-22 19:13 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
OK. За **один** обход множества банкоматов (название lst_obj как-то не очень подходит) собираем всю информацию в словарь словарей:
```python
        d = {}
        for i in lst_ob:
            if i.bank in d:
                b = d[i.bank]
                if type(i).__name__ in b:
                    b[type(i).__name__] += 1
                else:
                    b[type(i).__name__] = 1
            else:
                d[i.bank] = {type(i).__name__: 1}
```
Ещё за один обход можем вывести собранную информацию на экран.
Общая сложность - N * 2 => O(N)
У исходной реализации: N + N*N => O(N^2)

2023-06-23 06:11 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
про lst_ob согласна, это первоначальное название, т.к. изначально для теста был список банкоматов, потом стал множеством
Про словарь словарей я сама уже поняла)) выше в комментариях писала этот вариант. Но насколько можно/желательно пользоваться такой конструкцией?

2023-06-23 06:32 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
Словарь словарей - хорошее решение. Особенно для вспомогательных операций. Если нам требуется описать не разовый сложный объект, а полноценного участника реализуемой бизнес-логики, то лучше использовать композицию сущностей:
```python
class Bank:
    def __init__(self, atms):
        self._atms = atms

a1 = ATM()
a2 = ATM()
b = Bank((a1, a2))
```

2023-06-23 06:35 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +    def info_bank(lst_ob):
Об этом можете поподробнее рассказать на следующей лекции?

2023-06-25 17:23 UTC, AlenaStupina commented
Исправлено

2023-06-25 18:37 UTC, IlyaOrlov requested changes
Супер! Есть только одно небольшое замечание.

2023-06-25 18:37 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +[t.test() for t in atm]
Так, конечно, можно написать, но некрасиво) Список ради спискового выражения? Лучше обычный цикл.

2023-06-25 18:37 UTC, IlyaOrlov commented on Practice/Stupina/homework_7/task_3.py
> +            for j in set_atm:
Как я понимаю, это для того, чтобы даже по отсутствующим типам банкоматов информацию выводить? Хорошее решение! Причём, так даже лучше, чем сразу создавать `d[i.bank] = {atm.__name__: 0 for atm in ATM.__subclasses__()}`. Потому что не храним информацию со значениями по умолчанию, а просто выводим её по необходимости.

2023-06-26 07:03 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +[t.test() for t in atm]
Согласна) хотелось просто применить

2023-06-26 07:04 UTC, AlenaStupina commented on Practice/Stupina/homework_7/task_3.py
> +            for j in set_atm:
да, правильно понимаете

2023-06-26 07:25 UTC, AlenaStupina commented
исправлено

2023-06-26 08:23 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет)

2023-06-26 08:23 UTC, merged