Tanacheva branch
IlyaOrlov/PythonCourse2.0_May23 pull request #132
Opened 2023-06-24 21:07 UTC by JuliaTanacheva

домашнее задание 1-4 для лекции 5

2023-06-25 18:12 UTC, IlyaOrlov requested changes
Есть существенные замечания.

2023-06-25 18:12 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.1.py
> +        m = find_min(lst[i:])  # поиск минимума
Лучше, чтоб find_min возвращала не только сам минимум, но и его индекс, чтоб потом не приходилось использовать метод index, который снова бежит по тому же самому списку.

2023-06-25 18:12 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.2.py
> +    lst2 = list()
Есть более эффективный контейнер для используемой ниже операции in.

2023-06-25 18:12 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.3.py
> +def format_str(dict, str):
str - зарезервированное имя стандартной функции, его нельзя использовать для именования своих переменных.

2023-06-25 18:12 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.4.py
> +        while j < len(m[i]):
Можно проверять наличие n в m[i] одной операцией.
И ещё нужно контролировать m[i]. Иначе код не работает, например, на следующем примере:
```python
matrix = [[4, 4], [4, 3]]
number = 4
```

2023-06-27 21:44 UTC, JuliaTanacheva commented on Practice/Tanacheva/task5.2.py
> +    lst2 = list()
переделала задачу через использование множеста. Почему использование множества более предпочительно в этом случае?

2023-06-28 00:16 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.2.py
> +    lst2 = list()
Это связано со внутренней реализацией множеств. На больших наборах данных данное преимущество множеств становится весьма существенным. Стоит пересмотреть лекцию, посвященную множествам и словарям;)

2023-06-28 21:50 UTC, JuliaTanacheva commented on Practice/Tanacheva/task5.2.py
> +    lst2 = list()
Спасибо. Поняла

2023-06-29 08:59 UTC, IlyaOrlov requested changes
Добавил ещё одно замечание.

2023-06-29 08:59 UTC, IlyaOrlov commented on Practice/Tanacheva/task7.2.py
> +d3 = d1 + d2
Попробуйте сделать ещё одну утку: `d0 = Duck("SuperDuck", 6)` и сложить её с остальными вот так:
`d3 = d0 + d1 + d2`
Сразу скажу, что код не сработает, т.к. в реализации метода `__add__` упущен один нюанс!

2023-06-30 12:03 UTC, IlyaOrlov requested changes
Добавил замечаний по мелочи.

2023-06-30 12:03 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.1.py
> +        lst[i], lst[ind + i] = lst[ind + i], lst[i]
Стоит добавить условие: если ind == 0, то менять элемент местами с самим собой не нужно.

2023-06-30 12:03 UTC, IlyaOrlov commented on Practice/Tanacheva/task7.2.py
> +d5 = d1+d2+d4
Стоит добавить пробелов вокруг "+". В остальном коде же они есть. Лучше придерживаться единого стиля.

2023-06-30 19:54 UTC, IlyaOrlov requested changes
Хорошо. Осталось только замечание по [task5.4.py](https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/132/files/b78895c555999a5b791ec9bcce1fb92a33ea4903#diff-1604a733dd6e29e1e15412dc6b9337722d9c242c458468d7292e67d409e1ba45)

2023-07-01 19:37 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.
А удаление в одну строку - это на самом деле даже не удаление, а создание новой матрицы (из транспонированной) без рядов, содержащих n:
```python
new_m = [line for line in m if n not in line]
```
Это вместо строк 9-14.

2023-07-01 19:38 UTC, merged