пятое задание к 4 лекции
IlyaOrlov/PythonCourse2.0_May23 pull request #134
Opened 2023-06-27 11:35 UTC by Dkisunkina

2023-06-27 23:31 UTC, IlyaOrlov requested changes
Есть существенные замечания!

2023-06-27 23:31 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.5.py
> +        return list(range(y, x - 1))
Не понял логику. Почему верхняя граница range вычисляется по-разному в стр.21 и 23?
И ещё... Что делать, если x == y? Программа же упадёт.

2023-06-27 23:31 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.5.py
> +        return check(text)
Рекурсия - это круто! Можно оставить так. Но нужно понимать, что обычный цикл лучше. Потому что каждый вызов функции (в отличие от каждой итерации цикла) требует всё новых затрат памяти на контекст вызываемой функции (её локальные переменные, например). Ну и глубина рекурсии ограничена.

2023-06-27 23:31 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.5.py
> +    elif num > rand:
Здесь можно просто else.

2023-06-27 23:31 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.7.py
> +alone = decor_fun(alone)
Любопытно... Здесь мы вроде как только декорируем функцию alone. При этом, alone в основном коде после декорирования нигде не вызывается, а результат всё равно печатается. Как такое возможно?)

2023-06-27 23:31 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.8.py
> +    elif answer == "камень" and comp == "ножницы":
Чтоб сократить количество проверок, стоит их сгруппировать:
```python
elif answer == "камень":
    if comp == "ножницы":
        print("Вы выиграли")
    else:
        print("Вы проиграли")
```

2023-06-28 12:31 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.5.py
> +        return check(text)
я сначала написала обычный цикл, но так как было много повторений одного и того же решила сделать через рекурсию. Мне так показалось лучше, более оптимизировано чтоли))

2023-06-28 12:34 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.5.py
> +    elif num > rand:
исправила

2023-06-28 12:43 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.5.py
> +        return list(range(y, x - 1))
да, с минусом я накосячила)) хотя в голове логика была верной. Вначале напечатала ( x, y - 1)  а после исправила чтобы правильно выставлялся диапазон от меньшего к большему. x с y местами поменяла? а знак не исправила!

Сейчас знак поправила, спасибо!

Сейчас буду разбираться как красиво вписать  х == у...

2023-06-28 13:05 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.7.py
> +alone = decor_fun(alone)
В моей голове это выглядит так: мы передаём в этой строчке alone = decor_fun(alone) декоратору нашу исходную функцию и в середине декоратора (res = function_to_decorate(*args, **kwargs) )вызываем нашу исходную функцию которая содержит принт. function_to_decorate как раз получается равен alone после передачи декоратору нашей функции, вот она и срабатывает.

Я очень старалась разобраться в этих декораторах, поняла это так!

2023-06-28 13:33 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.8.py
> +    elif answer == "камень" and comp == "ножницы":
думала как оптимизировать! спасибо - исправила!

2023-06-28 17:09 UTC, IlyaOrlov requested changes
ОК. Жду обещанных исправлений)

2023-06-28 17:32 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.5.py
> +        return check(text)
могу переписать обратно)) или просто второй вариант решения создать и залить!

2023-06-28 17:41 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.7.py
> +alone = decor_fun(alone)
Хитрость какая! Понятно вроде бы :( внесла исправления!

2023-06-28 18:20 UTC, IlyaOrlov requested changes
Всё супер! Жду вариант с циклом.

2023-06-28 18:20 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.5.py
> +        return check(text)
Да, вариант с циклом весьма желателен.

2023-06-28 18:20 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.7.py
> +alone = decor_fun(alone)
Да, теперь всё ОК.
На всякий случай уточню.
Такой способ декорирования `alone = decor_fun(alone)` практически аналогичен применению @decor_fun
Претензии были только к стр.9:)

2023-07-24 12:43 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.
Задачу 5.1 можно докинуть отдельным пул реквестом.

2023-07-24 12:43 UTC, merged