дз №8
IlyaOrlov/PythonCourse2.0_May23 pull request #135
Opened 2023-06-27 18:28 UTC by AlenaStupina

задание №1

2023-06-28 00:00 UTC, IlyaOrlov requested changes
Всё супер! Только пара комментариев.

2023-06-28 00:00 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1.py
> +while True:
Я правильно понимаю, что такая реализация - только для эксперимента? Ведь можно и обычный цикл for применить к MyIter(s).

2023-06-28 06:06 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1.py
> +        self.i = self._text.find(self._p, 0)
Согласна, просто подумала, что для данной задачи это неважно, как и в примере с числами Фибоначчи

2023-06-28 06:15 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1.py
> +while True:
и для эксперимента в том числе. Вопрос по работе for для объектов класса: я правильно понимаю, что если мы внутри next не пропишем условие останова (исключение), то for будет бесконечным циклом?
и второй вопрос: как тогда без try... except вывести информацию об исключении (self.s_ex)?

2023-06-28 06:56 UTC, AlenaStupina commented
и еще вопрос: если бы вместо строки с текстом я использовала файл, мы с него не смогли бы  сразу считать текст от параграфа до параграфа? пришлось бы все равно считывать все содержимое в какую-то строку?

2023-06-28 08:12 UTC, AlenaStupina commented
добавлена задача 2

2023-06-28 08:49 UTC, AlenaStupina commented
Добавлена задача 2 и 3

2023-06-28 10:42 UTC, AlenaStupina commented
Добавлены задачи 2, 3, 4

2023-06-28 15:39 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1.py
> +        self.i = self._text.find(self._p, 0)
Да, но решение получилось почти идеальным, поэтому стоит добавить пару штрихов, чтоб убрать это "почти")

2023-06-28 15:42 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1.py
> +while True:
1. Да, в этом случае for будет бесконечным.
2. В Python есть много способов, как решить одну и ту же задачу, и наверное, можно что-то придумать, кроме for, iter и next. Но это точно не общепринятые способы, и читаемости/понятности коду не добавит.
3. Никак(

2023-06-28 16:00 UTC, IlyaOrlov requested changes
Оставил ещё несколько замечаний.

2023-06-28 16:00 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_4.py
> +for i in permutations('password', 4):  # возможно я неправильно поняла,что нужно вывести
Всё верно. Допускаются разные варианты: combinations, permutations и даже варианты с повторами.

2023-06-28 17:57 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1.py
> +        self.i = self._text.find(self._p, 0)
исправлю конечно, просто ждала ответа про исключение, чтобы сразу все поправить

2023-06-28 18:03 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1.py
> +while True:
2. да, но чтобы итератор заработал, надо ведь его вызвать, т.е. вызвать методы iter и next. разве это можно как то еще сделать, кроме как .__iter__ и .__next__ , здесь разве не все однозначно? или мы о разном говорим...
3. поэтому еще я хотела использовать try...except. Но все равно исправлю на for

2023-06-28 18:14 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_4.py
> +from itertools import *
исправлю)  знаю, что это крайне нежелательный вариант импорта, но просто для данной задачи вроде как никакого риска нет)

2023-06-28 18:32 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1.py
> +while True:
2. Ну если без извращений, то, конечно, никак иначе не получится. Но есть такие возможности как интроспекция, например. Или можно открыть сам же исполняемый файл на чтение, прочитать нужные строки и применить к ним eval. На практике такое не применяется, но возможность есть, поэтому я и сделал оговорку про множество способов)
3. Я так и понял)

2023-06-28 18:34 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_4.py
> +from itertools import *
Переходить дорогу на красный, когда на ней нет машин, в принципе, тоже не особо рискованно...)

2023-06-28 18:38 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_4.py
> +lst_1 = []
не совсем поняла, как это list(itertools.chain([1, 2, 3], [4, 5], [6, 7])) сработало, ведь чтобы генератор вызвался (вычислился, как правильно сказать?.. ), нужен метод next. Он неявно вызывается в for, а без for почему заработало... или я что-то неправильно понимаю...

2023-06-28 18:44 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_4.py
> +for i in permutations('password', 4):  # возможно я неправильно поняла,что нужно вывести
но эти две функции дадут разные результаты...

а я голову ломаю, сначала подумала, что на выходе должно быть ([('p', 'a', 's', 's'), ('p', 'a', 's', 'w'), ('p', 'a', 's', 'o'), ('p', 'a', 's', 'r'), ('p', 'a', 's', 'd')]) и сидела мучалась, как это сделать; потом решила упростить себе жизнь))) 
и кстати, я в коде в итоге использовала combinations, не пойму как в код попал permutations('password', 4), не ту версию закомитила наверное...

2023-06-28 18:58 UTC, AlenaStupina commented
> Файл можно считывать построчно и побайтово. Построчно это просто `for i in f`. А побайтово - f.read(1) - до тех пор, пока что-то читается. Считываем строку или очередной байт в некий буфер (доп. переменную), проверяем на символ параграфа. Кстати, стоит попробовать реализовать работу с файлом. **Целиком** считывать файл в строку - точно не вариант.

считывать с файлов я умею, и побайтово, и построчно)  это просто муторнее, чем работать сразу со строкой (в плане поиска параграфа, он же может быть и в середине строки, надо часть первой строки (после параграфа) запомнить, потом считать следующую строку, найти там параграф и дозаписать эту часть строки  до параграфа в сохраненную строку). А если побайтово: русские , английские буквы, символы (символ параграфа), цифры они же занимают разное количество байт вроде? т.е. как мне считать так, чтобы быть уверенным, что я  считал целый символ\букву\число, а не его половину, например?..

2023-06-28 18:59 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_4.py
> +from itertools import *
а Вы так не делаете? 😄

2023-06-28 20:40 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_4.py
> +from itertools import *
Стараюсь не делать) На самом деле риск есть всегда. Даже когда кажется, что его нет. Но тут ещё надо смотреть, чем оправдывается этот риск. Если я не тороплюсь, зачем нарушать правила?)

2023-06-28 20:46 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_4.py
> +lst_1 = []
Магия функции list(). Она умеет проходить итераторы/генераторы для выполнения своей задачи - получения списка. Фактически, внутри нее тот же цикл for и работает.

2023-06-28 20:50 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_4.py
> +for i in permutations('password', 4):  # возможно я неправильно поняла,что нужно вывести
Разные. permutations жонглирует позициями элементов, не глядя на значения. combinations оперирует конкретно значениями.
Но в задании нет **точных** указаний, каким должен быть результат.

2023-06-28 20:56 UTC, IlyaOrlov commented
> > Файл можно считывать построчно и побайтово. Построчно это просто `for i in f`. А побайтово - f.read(1) - до тех пор, пока что-то читается. Считываем строку или очередной байт в некий буфер (доп. переменную), проверяем на символ параграфа. Кстати, стоит попробовать реализовать работу с файлом. **Целиком** считывать файл в строку - точно не вариант.
> 
> считывать с файлов я умею, и побайтово, и построчно) это просто муторнее, чем работать сразу со строкой (в плане поиска параграфа, он же может быть и в середине строки, надо часть первой строки (после параграфа) запомнить, потом считать следующую строку, найти там параграф и дозаписать эту часть строки до параграфа в сохраненную строку). А если побайтово: русские , английские буквы, символы (символ параграфа), цифры они же занимают разное количество байт вроде? т.е. как мне считать так, чтобы быть уверенной, что я считала целый символ\букву\число, а не его половину, например?..

Для построчного чтения - да, все так. А при побайтовом... Тут надо смотреть кодировку. И экспериментировать. По умолчанию, в Python3 все символы - в Юникоде, т.е. занимают два байта. Для цифр и английских символов старший байт - ничего особо не значит: что с ним, что без него - представление одинаковое.

2023-06-29 05:38 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_4.py
> +lst_1 = []
Вот, значит для вызова итератора/генератора еще можно использовать list (это к моему вопросу выше). А еще есть какие-нибудь функции с таким неявным вызовом for? ну кроме range, enumerate, которыми мы можем пользоваться для вызова генератора

2023-06-29 09:04 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_4.py
> +lst_1 = []
В range, enumerate нет вызова for. Он есть в list. То же самое умеют делать tuple, set.

2023-06-29 09:05 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-06-29 09:05 UTC, merged