дз №8, задание №1 с файлом
IlyaOrlov/PythonCourse2.0_May23 pull request #138
Opened 2023-06-29 11:02 UTC by AlenaStupina

2023-06-29 12:10 UTC, IlyaOrlov requested changes
Есть вопрос!

2023-06-29 12:10 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +        while self.__s != self.__p:
А в чём смысл этого цикла? Получается, если в файле нет символа параграфа, то вообще ничего не выведется.

2023-06-29 12:26 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1_file.py
> +        while self.__s != self.__p:
Смысл цикла - проверка на нужный символ и на конец файла. 
ну это же логично,  нет нужного символа - ничего не выведено. добавить туда print("символ не найден") не получится по смыслу (проверяется еще конец файла), return None тоже перед raise не напишешь. Я думала этот цикл в init сделать, но посчитала, что если в init будет вызываться исключение - это не очень...

2023-06-29 20:22 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +        self.__f.close()
Стоит добавить проверку `if hasattr(self, '_MyIter__f'):` Т.к. деструктор вызовется даже если, при открытии файла произошла ошибка.

2023-06-29 20:22 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +        while self.__s:
while здесь явно лишний

2023-06-29 20:22 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +        while self.__s != self.__p:
Насчёт логичности очень сомневаюсь) Параграф нужен для разделения блоков в тексте. Если его нет - значит, разделять нечего, и можно выводить весь текст целиком. Но раз Вы видите эту функциональности иначе, то ОК, пусть так будет.

2023-06-29 20:23 UTC, IlyaOrlov requested changes
Оставил пару замечаний.

2023-06-30 05:44 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1_file.py
> +        while self.__s != self.__p:
Задание звучало так: "Реализовать итератор, который бы "читал" заданный текст по параграфам". Соответственно если параграфа нет - он не читает. Я поняла так, логический вывод из тз))

2023-06-30 05:52 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1_file.py
> +        self.__f.close()
1. Можно поподробнее об этой функции? Она означает, что файл будет закрыт, если он существует как атрибут объекта self?
2. А что случится, если файл открылся с ошибкой, почему его нельзя закрыть? Если при открытии произошла ошибка - с файлом нельзя будет работать, open не сработает, поэтому и на закрытии того, чего нет ,будет ошибка, так?

2023-06-30 06:36 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1_file.py
> +        while self.__s:
согласна, это рудимент кода и моя невнимательность...)

2023-06-30 06:37 UTC, AlenaStupina commented
исправлено

2023-06-30 12:45 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +        self.__f.close()
1. Эта функция просто проверяет есть ли у объекта self атрибут с именем '_MyIter__f'. Если исключение произошло в строке `self.__f = open(name_file, encoding='utf-8')`, то атрибут __f даже не будет создан.
2. Да, open не сработал, ничего не открылось, атрибут __f не создался.

2023-06-30 12:47 UTC, IlyaOrlov requested changes
Это не тот случай, когда надо создавать своё исключение!

2023-06-30 12:47 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +            raise FileNotExists('Файл не существует')
Какой смысл подменять стандартное исключение, придуманное конкретно для случая, когда файл не существует, своим?

2023-06-30 13:20 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1_file.py
> +        self.__f.close()
а файл может создаться, но с ошибкой? и быть непригодным для чтения/записи? Как поступать в этом случае, для корректной работы кода?

2023-06-30 13:21 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1_file.py
> +            raise FileNotExists('Файл не существует')
да не знаю...) захотелось)

2023-06-30 17:12 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +        self.__f.close()
Только не создаться, а открыться) Мы же его на чтение открываем. Всё может быть. Каждый исключительный случай надо рассматривать/обрабатывать отдельно. В данном конкретном случае мы предусматриваем вариант, когда не существует атрибута __f.

2023-06-30 17:14 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +            raise FileNotExists('Файл не существует')
Сомнительный аргумент)
Стандартное исключение FileNotFoundError тоже не надо выбрасывать. Оно и так выбросится при попытке открытия несуществующего файла. Не отнимайте хлеб у интерпретатора)

2023-06-30 18:46 UTC, AlenaStupina commented on Practice/Stupina/homework_8/task_1_file.py
> +        self.__f.close()
Да, открыться, оговорилась. Я так и не поняла: если файл открывается на чтение, но с ошибкой (не FileNotFoundError, есть же наверное другие ошибки? всякое может быть ведь),  он доступен для работы, т.е. для чтения? Или если при открытии возникает любая ошибка, то всегда выбрасывается исключение?

2023-06-30 18:46 UTC, AlenaStupina commented
исправлено

2023-06-30 19:52 UTC, IlyaOrlov commented on Practice/Stupina/homework_8/task_1_file.py
> +        self.__f.close()
Исключение прерывает выполнение программы. В выражении `self.__f = open(...)` выполняется последовательно несколько операций: тут и запрос к ОС на открытие файла (файла может не существовать), загрузка содержимого файла (может не быть прав на чтение) в память (может не хватить места в памяти) и т.д. И только в конце всего этого конвейера происходит связывание атрибута self.__f с областью памяти, в которую загрузилось содержимое файла. Соответственно, если ошибка происходит на каком-то из приведённых этапов, все последующие этапы (в т.ч. и самый последний - связывание self.__f с памятью, через которую и происходит работа с файлом) не выполняются. Таким образом, при выполнении этого выражения любая ошибка, приводящая к исключению, делает невозможной работу с файлом. Исключения выбрасываются при любой ошибке, предусмотренной в операционной системе и/или интерпретаторе (не забывайте: и то, и другое - тоже программы со своим кодом).  Если в файле некорректные данные (например, отсутствует символ параграфа) - это тоже может считаться ошибкой с точки зрения реализуемой бизнес-логики, но не для операционной системы и не для интерпретатора, поэтому для подобной ошибки стандартного исключения не предусмотрено.

2023-06-30 19:52 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-06-30 19:52 UTC, merged