дз №9
IlyaOrlov/PythonCourse2.0_May23 pull request #139
Opened 2023-06-30 20:03 UTC by AlenaStupina

задача №2

2023-06-30 20:08 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
Ожидаю замечания по поводу Exception, но я не знаю как еще правильно и не слишком нудно описать все возможные ситуации некорректного ввода даты (буквы, другие разделители, кроме заданного; корректный год, месяц и число )

2023-07-01 09:12 UTC, AChertova commented on Practice/Stupina/homework_9/task_2.py
> +        print(f'Количество рабочих дней в период с {data_1} по {data_2}: {res}')
Есть существенная проблема. Если первая дата - воскресенье, вторая будни - мы теряем 1 рабочий день

2023-07-01 09:22 UTC, AChertova commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
Вообще интерпретатор и сам неплохо справляется (ValueError, TypeError, IndexError ... - смотря, что вводит пользователь). Хоть и аварийно не хотелось бы  завершать программу. Тут надо понимать - что именно вы хотите донести до пользователя и зачем. Я попрошу Илью меня дополнить :)

2023-07-01 09:27 UTC, AChertova commented on Practice/Stupina/homework_9/task_2.py
> +    data_2 = datetime.date(int(data_2[0]), int(data_2[1]), int(data_2[2]))
В целом сама конструкция ввода даты несколько непривычная для бытового пользователя, можно много ошибок при вводе совершить - не прочитал в каком порядке, не те знаки поставил (точки, слэш и тд). И печально смотреть, что ты что-то делаешь не так. Как минимум я бы сначала сделала все операции для data_1, чтобы ошибка обозначилась как можно раньше, а не введя обе даты. Как максимум - можно запрашивать данные порционно, так и вероятность ошибки ниже. Технически ошибки в вашем запросе нет, но для пользователя не очень friendly

2023-07-01 09:52 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
Тут следует вспомнить один из пунктов Дзена: "ошибки не должны замалчиваться") Если не хотите аварийно завершать программу, перехватить исключение можно, но информацию, которую это исключение в себе несёт, игнорировать всё же не следует. Как вариант, можно сделать так:
```python
except Exception as ex:
    print(f"Некорректно заданы даты. Ошибка: {ex}")
```
Но учитывая, что при ошибке ввода даты дальнейшее выполнение программы не имеет смысла - перехватывать исключение незачем.

2023-07-01 09:57 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +    data_2 = datetime.date(int(data_2[0]), int(data_2[1]), int(data_2[2]))
Согласен. Могу также предложить рассмотреть функцию [fromisoformat](https://docs.python.org/3/library/datetime.html#:~:text=classmethod%20date.fromisoformat(date_string)%C2%B6) - более гибкий вариант создания объекта datetime из строки.

2023-07-01 10:45 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
> Но учитывая, что при ошибке ввода даты дальнейшее выполнение программы не имеет смысла - перехватывать исключение незачем.

чтобы пользователь видел, что ошибка именно в некорректном вводе даты, а не в самой программе

2023-07-01 10:48 UTC, AlenaStupina commented
[AChertova](https://github.com/AChertova), мне на почту пришел Ваш комментарий : Есть существенная проблема. Если первая дата - воскресенье, вторая будни - мы теряем 1 рабочий день. 
Вы его удалили? не вижу в коммите. 
И да, я проверила, все корректно работает

2023-07-01 11:32 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
ОК, допустимо) Но исходное исключение печатать тоже надо. Иначе программа скажет пользователю, что у него ошибка - "Некорректно заданы даты". Но этой информации не хватит, чтоб пользователь понял, что конкретно он не так делает.

2023-07-01 12:55 UTC, AChertova commented
Да, я его удалила, все работает корректно, я просто в 2022 году живу :))

2023-07-01 13:37 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
Я согласна, исправлю) Но просто если пользователь далек от программирования, он и так не поймет))))

2023-07-01 13:57 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +    data_2 = datetime.date(int(data_2[0]), int(data_2[1]), int(data_2[2]))
> Согласен. Могу также предложить рассмотреть функцию [fromisoformat](https://docs.python.org/3/library/datetime.html#:~:text=classmethod%20date.fromisoformat(date_string)%C2%B6) - более гибкий вариант создания объекта datetime из строки.

не вижу особо разницы в данном контексте, эта функция не распознает дату, если она введена с использованием любых разделителей, кроме тире...

2023-07-01 14:26 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
Проблема даже не в том, что пользователь не поймет. А в том, что он Вам, как автору программы, не сможет объяснить, что с ней не так. И начнется...
- У меня не работает(
- Что не работает?
- Ошибка какая-то. Некорректно заданы даты.
- А Вы как даты задаёте?
- Корректно.
- Давайте смотреть.
- Мне сейчас некогда.
И т.д. Пользователь же надеется, что Вы - экстрасенс)
Исключение в этом плане более информативно.

2023-07-01 14:31 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +except Exception:
аа, поняла

2023-07-01 14:35 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +    data_2 = datetime.date(int(data_2[0]), int(data_2[1]), int(data_2[2]))
Начиная с 3.11 эта функция даже дату без разделителей понимает)
А ещё более гибкий вариант - функция [strptime()](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior)
Она вообще преобразует строку в дату по заданному формату.

2023-07-01 15:39 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +    data_2 = datetime.date(int(data_2[0]), int(data_2[1]), int(data_2[2]))
> Начиная с 3.11 эта функция даже дату без разделителей понимает) А ещё более гибкий вариант - функция [strptime()](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior) Она вообще преобразует строку в дату по заданному формату.
У меня 3.11,но fromisoformat только и понимает дату , написанную либо слитно, либо с тире

2023-07-01 15:52 UTC, AlenaStupina commented
исправлено

2023-07-01 19:29 UTC, IlyaOrlov requested changes
Оставил ещё несколько замечнаий.

2023-07-01 19:29 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
Если мы не планируем в этой же строке что-то делать с результатом выражения, лучше писать if...else.. обычным способ в несколько строк.

2023-07-01 19:29 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_4.py
> +        s = ('Иван', 'Петр', 'Аня', 'Оля', 'Александр', 'Маша', 'Артём')
Здесь и в других генераторах имён при каждом вызове **s** - один и тот же константный кортеж - создаётся заново. Лучше сделать наборы фамилий, имён и т.д. атрибутами класса. Тогда они будут создаваться всего один раз за время работы программы (вместе с классом) и потом просто переиспользоваться.

2023-07-01 19:29 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_4.py
> +        MyClass = pickle.load(f)
Здесь всё-таки должно быть `Human = `. Т.к. элементы распаковываемого списка man относятся именно классу Human. Это будет иметь значение, если функции упаковки/распаковки будут находиться в разных файлах.

2023-07-02 07:16 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
Не совсем поняла ,что Вы имеете ввиду.  Мы вызываем функцию для результата выражения - это не действие?

2023-07-02 07:18 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_4.py
> +        s = ('Иван', 'Петр', 'Аня', 'Оля', 'Александр', 'Маша', 'Артём')
согласна. Создавать несколько раз одно и то же наверное хуже с точки зрения работы интерпретатора, чем сохранить в памяти на все время работы программы? просто в первом случае вроде как память не занимается: создал объект - s удалилась

2023-07-02 07:20 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_4.py
> +        MyClass = pickle.load(f)
Спасибо за комментарий. У меня возник этот вопрос, но я решила ответ на него получить не в телеграм ,а тут, через дз)

2023-07-02 10:52 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
Если бы было так:
```python
res = fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
```
то ОК, можно считать это единым сложным выражением.
А так получается, что мы в одной строке пытаемся уместить несколько выражений, что не согласуется с PEP8.

2023-07-02 10:58 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_4.py
> +        s = ('Иван', 'Петр', 'Аня', 'Оля', 'Александр', 'Маша', 'Артём')
На память тут влияние небольшое, т.к. константные объекты обычно сами по себе небольшие. И ещё стоит учесть, что многократные занятия/освобождения памяти способствуют её дефрагментации. Представьте зрительный зал. Одно дело, когда все зрители один раз расселись по местам и более-менее равномерно расселись по залу. Совсем другая картина, когда зрители забегают периодически, приседают с краю, так что к середине ряда не пройдёшь. В итоге, места как бы есть, но пробраться к ним сложно.

2023-07-02 12:16 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
а если б было так:
fun(data[1], data[0])+2 if data[0] > data[1] else fun(data[0], data[1])
это бы считалось за то, что мы что-то делаем с результатом выражения?

2023-07-02 12:38 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
Нет. Речь шла о результате всего выражения, а не только результате вызова функции.

2023-07-02 12:43 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
Иными словами, такой код:
```python
if data[0] > data[1]:
    res = fun(data[1], data[0])
else:
    res = fun(data[0], data[1])
```
стоит переписать, как
```python
res = fun(data[1], data[0]) if data[0] > data[1] else fun(data[0], data[1])
```
Хотя бы, чтоб не писать лишний раз присваивание.
А такой код:
```python
if data[0] > data[1]:
    fun(data[1], data[0])
else:
    fun(data[0], data[1])
```
умещать в одну строку не нужно.

2023-07-03 05:42 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_2.py
> +        if d.weekday() < 5:
Кстати, можно было использовать какую-нибудь другую функцию, кроме isoweekday?

2023-07-03 10:05 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_3.py
> +
в моем решении папка с файлом удаляется не одновременно с файлом (не за одну итерацию), а при вызове функции в бесконечном цикле. Я так полагаю, что это тоже верно, но мне все-таки хотелось ,чтобы после файла удалялась папка, если она пустая и если время ее жизни больше заданного. Может быть подскажете решение? Я что только не пробовала, но не получается сделать это корректно и компактно...

2023-07-03 10:07 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_3.py
> +        d_exist = datetime.datetime.today() - d_creation
есть какой-то другой путь решения это задачи в плане работы со временем? Какие другие функции/подходы можно было использовать вместо datetime.fromtimestamp, datetime.now(), datetime.timedelta(minutes=1)?

2023-07-03 19:10 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_2.py
> +        if d.weekday() < 5:
Всё описание здесь - https://docs.python.org/3/library/datetime.html
Ничего похожего на isweekend() или isworkday() тут не видно)

2023-07-03 19:20 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_3.py
> +        d_exist = datetime.datetime.today() - d_creation
Есть библиотеки типа https://pypi.org/project/watchdog/, которые могут делать то же самое. Но в любом случае алгоритм реализуется один и тот же: 
1. узнаём дату/время создания файла
2. смотрим разницу между текущими датой/временем и датой/временем создания файла.
datetime позволяет реализовать эти шаги практически один в один.
При этом всегда предпочтительнее  использовать возможности стандартной библиотеки.

2023-07-03 19:34 UTC, IlyaOrlov requested changes
Оставил комментарии и предложения по оптимизации.

2023-07-03 19:34 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_3.py
> +            if os.listdir(path):
Использовать listdir для проверки пустоты папки слишком расточительно. Здесь как раз можно использовать итератор: `if next(os.scandir(path), None):`

2023-07-03 19:34 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_3.py
> +
Можно переписать строку 22 на:
```python
if d_exist > datetime.timedelta(minutes=2) and not next(os.scandir(path), None):
```

2023-07-04 07:03 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_3.py
> +            if os.listdir(path):
Что делает next для пути, заходит внутрь?

2023-07-04 07:12 UTC, AlenaStupina commented on Practice/Stupina/homework_9/task_3.py
> +
согласна. А я мудрила, делала проверки папки в ветке условия, относящейся к файлу , хотела чтобы там, после удаления файла, проверялась папка на пустоту и время и тоже удалялась  🙈

2023-07-04 07:21 UTC, AlenaStupina commented
Исправлено

2023-07-04 08:48 UTC, IlyaOrlov commented on Practice/Stupina/homework_9/task_3.py
> +            if os.listdir(path):
Для пути next ничего не делает. Он, как обычно, дергает итератор scandir. Итератор же ищет по указанному пути файлы и папки и возвращает их **по одному**.

2023-07-04 08:52 UTC, IlyaOrlov reviewed
У меня замечаний нет. Если с Вашей стороны вопросов не осталось, то я готов зачесть это д/з. 
Да, если на открытые Вами диалоги (conversation) получены устраивающие Вас ответы, просьба нажать в них кнопку Resolve converstion.

2023-07-04 09:04 UTC, AlenaStupina commented
> У меня замечаний нет. Если с Вашей стороны вопросов не осталось, то я готов зачесть это д/з. Да, если на открытые Вами диалоги (conversation) получены устраивающие Вас ответы, просьба нажать в них кнопку Resolve converstion.

вопросов нет

2023-07-04 09:57 UTC, merged