Залача 1 к лекции 8
IlyaOrlov/PythonCourse2.0_May23 pull request #141
Opened 2023-07-03 20:22 UTC by DmitriySapegov

2023-07-04 08:45 UTC, IlyaOrlov requested changes
Всё супер! Одно небольшое предложение по оптимизации.

2023-07-04 08:45 UTC, IlyaOrlov commented on Practice/Sapegov/Sap8.1.py
> +        self.i += 1
Это выражение стоит поместить под else
Принципиально ничего не поменяется, но если мы вышли из цикла через break (по условию if self.i >= len(self.text)), то увеличивать self.i уже не нужно.

2023-07-04 19:51 UTC, DmitriySapegov commented on Practice/Sapegov/Sap8.1.py
> +        self.i += 1
Илья, не совсем понял о какой конструкции под else идет речь.
Без условия и break мы улетаем в бесконечный цикл.

2023-07-04 20:26 UTC, IlyaOrlov commented on Practice/Sapegov/Sap8.1.py
> +        self.i += 1
```python
while self.text[self.i] != self.symbol:
    res += self.text[self.i]
    self.i += 1
    if self.i >= len(self.text):
        break
else:
    self.i += 1
```

2023-07-05 16:53 UTC, DmitriySapegov commented on Practice/Sapegov/Sap8.1.py
> +        self.i += 1
А, блин!)))
то увеличивать self.i уже не нужно.
Меня вот это смутило. Подумал, что вообще убрать второй счетчик нужно.

Поправил и закинул еще 2 и 3 задачу по этой теме.

2023-07-05 19:59 UTC, DmitriySapegov commented on Practice/Sapegov/Sap8.1.py
> +        self.i += 1
Добавил задачу 3 к 6ой лекции

2023-07-06 11:53 UTC, IlyaOrlov approved these changes
Отлично! Теперь замечаний нет.

2023-07-06 11:53 UTC, merged