Kapralova
IlyaOrlov/PythonCourse2.0_May23 pull request #142
Opened 2023-07-04 10:28 UTC by AnnaKapralova

Задания 7.3, 8.1 и 8.2
Уверена, что с банкоматами будет много ошибок...

2023-07-04 10:34 UTC, AChertova commented on Practice/AKapralova/KapralovaDz7.3.py
> +#     i.about_atm()
Да, задача понята не совсем верно. У вас три класса банкоматов - один умеет только принимать деньги, другой только выдавать, у третьего только онлайн-операции. А в задаче требуется реализовать два класса банкоматов - один умеет выдавать и принимать деньги, второй умеет все, что умеет первый + у него есть возможности онлайн-операций

2023-07-04 10:36 UTC, AChertova commented on Practice/AKapralova/KapralovaDz7.3.py
> +b3.about_atm()
В задании указано, что выполнение однотипных операций стоит осуществить в цикле

2023-07-04 10:51 UTC, AChertova commented on Practice/AKapralova/KapralovaDz8.1.py
> +        self.paragraphs = self.text.split(self.paragraph_symbol)
Мне не очень нравится идея хранить текст повторно в формате списка... Подождем мнения Ильи

2023-07-04 10:56 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz7.3.py
> +#     i.about_atm()
Поняла, переделаю!

2023-07-04 13:21 UTC, AChertova commented on Practice/AKapralova/KapralovaDz7.3.py
> +        print("Банкомат может осуществлять операцию получения и выдачи наличных, а так же онлайн платежи")
Предлагаю вынести метод operation() в родительский класс, потому что смысл един для всех наследников - вывод информации об операциях. А в этом классе отнаследовать его у родителя через super() и дополнить print-ом с дополнительной информацией. Так мы обеспечим принцип полиморфизма. А в GetGiveATM просто pass

2023-07-04 17:21 UTC, IlyaOrlov requested changes
Добавил ещё замечание.

2023-07-04 17:21 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz8.1.py
> +        self.paragraphs = self.text.split(self.paragraph_symbol)
Да, так теряется смысл итератора - возможность получения результата по частям, не перегружая память. Здесь же помимо исходного текста, мы заполняем память списком, сформированным из этого текста. 
Здесь достаточно сохранить text в self.text. А в методе `__next__` надо идти по символам, складывая их в некий вспомогательный буфер (строку или тоже список), и как только встретится символ параграфа, всё, что накоплено в буфере, возвращать.

2023-07-04 17:21 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz8.3.py
> +    enumerated_numbers = enumerate(list(range(1, 10001)))
list здесь лишний. enumerate умеет работать и с генераторами, коим тут является range.

2023-07-04 18:53 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz8.3.py
> +    enumerated_numbers = enumerate(list(range(1, 10001)))
Исправила

2023-07-04 19:12 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz7.3.py
> +        print("Банкомат может осуществлять операцию получения и выдачи наличных, а так же онлайн платежи")
Исправила

2023-07-05 07:33 UTC, IlyaOrlov requested changes
Всё хорошо. Осталось только немного переделать итератор.

2023-07-13 07:23 UTC, IlyaOrlov approved these changes
Отлично! Больше замечаний нет.

2023-07-13 07:23 UTC, merged