Fedorov_HW9
IlyaOrlov/PythonCourse2.0_May23 pull request #143
Opened 2023-07-04 20:04 UTC by Fed909

2023-07-05 08:00 UTC, IlyaOrlov requested changes
Хорошо. Оставил несколько замечаний.

2023-07-05 08:00 UTC, IlyaOrlov commented on Practice/Fedorov/HW_9/9.4.py
> +class Human:
Всё-таки класс стоит определить выше функций, которые с ним работают.

2023-07-10 08:04 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.1.py
> +need_path = current_path.replace(r"Fedorov\HW_9", "") + "README.md"
Да Pathlib - крутая штука.

2023-07-10 10:12 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.4.py
> +    lst = create_human(count_human)
Очень люблю такие комментарии. Которые помогают подумать, как сделать код лучше, не просто готовое решение, а типо почитай библиотеку такую-то там есть метод такой то. Да убивает намного больше времени, но и дает намного больше знаний.

2023-07-10 19:31 UTC, IlyaOrlov requested changes
Ещё пара небольших замечаний.

2023-07-10 19:31 UTC, IlyaOrlov commented on Practice/Fedorov/HW_9/9.1.py
> +        m = re.search(pattern2, i)
pattern2 используется в цикле, поэтому имеет смысл его предварительно скомпилировать, как было рассмотрено на лекции.

2023-07-10 19:31 UTC, IlyaOrlov commented on Practice/Fedorov/HW_9/9.2.py
> +        if start_date in new_holidays:
Наверное, здесь всё-таки должно быть elif. Т.к. если в new_holidays вдруг попадёт выходной, учесть его надо только один раз.

2023-07-11 09:08 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.1.py
> +        m = re.search(pattern2, i)
"сохранение полученного объекта регулярного выражения для повторного использования более эффективно, когда выражение будет использоваться несколько раз в одной программе"
А в чём эффект? Я не уловил сути, поэтому не использую, а надо использовать!

2023-07-11 09:10 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.1.py
> +    text = myfile.read()
Т.е если я читаю файл сразу весь и записываю его в переменную - то это не совсем правильно?
Лучше идти по строкам? и записывать в множество чтобы потом? не понял что потом :)

2023-07-11 09:13 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.2.py
> +        if start_date in new_holidays:
ага ага, поменял название переменной, чтобы пользователь типо понимал, что не включая дату по, но это не верно как-то :) через elif правильнее.
end_date_not_include

2023-07-11 09:23 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.2.py
> +        if start_date in new_holidays:
во поправил, теперь 9.2 идеально, и списковое выражение есть и включает последнюю дату в подсчете рабочих дней

2023-07-11 13:10 UTC, IlyaOrlov commented on Practice/Fedorov/HW_9/9.1.py
> +        m = re.search(pattern2, i)
Эффект в скорости. 
re.search (да и прочие функции re) сама предварительно выполняет компиляцию переданного строкового выражения в специальный объект, подготовленный для посимвольного сравнения (Зачем это делается? Представьте, что Вы бы сами реализовывали поиск по спец символам. Как минимум, это потребует создания/настройки вспомогательных функций сравнения под каждый спец. символ.).
Т.е. если Вы сразу передадите скомпилированный объект, одной операцией в цикле будет меньше.
Правда, даже без предварительной компиляции, когда регулярных выражений в программе немного, умный модуль re запомнит единожды скомпилированный параметр и будет его неявно переиспользовать. Так что особой ошибки, если не сделать re.compile, нет. Но нужно понимать, почему она могла бы быть, и что помогло её избежать.

2023-07-11 13:12 UTC, IlyaOrlov requested changes
ОК. Ответил на вопросы и добавил замечание.

2023-07-11 13:12 UTC, IlyaOrlov commented on Practice/Fedorov/HW_9/9+.1.py
> +new_lst = [int(i)**2 for i in lst if i.isdigit() and int(i) % 5 == 0]
Хмм... двойная операция int(i), и ни одного моржового оператора)

2023-07-11 13:45 UTC, Fed909 commented on Practice/Fedorov/HW_9/9+.1.py
> +new_lst = [int(i)**2 for i in lst if i.isdigit() and int(i) % 5 == 0]
Мне очень понравились списковые выражения, что я забыл про моржовый оператор :)

2023-07-11 14:08 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.1.py
> +        m = re.search(pattern2, i)
Спасибо! я понял)

2023-07-11 14:08 UTC, Fed909 commented on Practice/Fedorov/HW_9/9.1.py
> +    text = myfile.read()
Спасибо большое!

2023-07-11 14:12 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-07-11 14:12 UTC, merged