задания 1 для модуля 10
IlyaOrlov/PythonCourse2.0_May23 pull request #154
Opened 2023-07-28 22:36 UTC by JuliaTanacheva

2023-07-29 15:30 UTC, IlyaOrlov requested changes
Хорошо. Но есть замечания. Также ожидаются ответы на вопросы к заданию (можно в виде комментариев).

2023-07-29 15:30 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.2.py
> +    tread1 = Thread(target=find_primes, args=(3, 10000))
Всё-таки создавать/запускать потоки (и процессы) лучше в цикле. А то столько повторения одинакового кода!

2023-07-29 15:30 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.1.py
> +        for j in lst:
Такой способ отбора простых чисел сработает, только если начинать с 2.
Так, например, в find_primes(3, 10000) попадает 4, а это не простое число.

2023-07-31 19:46 UTC, JuliaTanacheva commented on Practice/Tanacheva/task10.1.1.py
> +        for j in lst:
Если забыть выполнить start для потоков, то программа не запустится(поток не запустится, а функция выполняется в потоке). Если забыть выполнить join, то время выполнения программы будет неправильным, эта операция выполнится быстрее,чем функция в потоках. Программа не будет ждать пока выполнятся потоки. 
Для процессов аналогично.
Для потоков время выполнения аналогично программе без потоков, так как тратится время на создание потоков.
Для процессов время меньше

2023-07-31 20:17 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.1.py
> +        if i > 1:
Чтоб это условие не проверялось на каждой итерации цикла, проще сделать одну проверку перед циклом для start.

2023-07-31 20:17 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.1.py
> +            for j in range(2, i):
Достаточно проверять делители не до i, а до квадратного корня из i.

2023-07-31 20:17 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.1.py
> +        for j in lst:
А удалось засечь, сколько времени реально потратилось во всех трех случаях?

2023-07-31 20:20 UTC, IlyaOrlov requested changes
Есть ещё, что улучшить.

2023-07-31 20:20 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.2.py
> +    thr1 = Thread(target=find_primes, args=(3, 10000))
Так можно и создание потоков в цикл вместить:
```python
for args in ((3, 10000), (10001, 20000), (20001, 30000)):
    thr = Thread(target=find_primes, args=args)
    thr.start()
    threads.append(thr)
```

2023-08-01 20:43 UTC, JuliaTanacheva commented on Practice/Tanacheva/task10.1.2.py
> +    thr1 = Thread(target=find_primes, args=(3, 10000))
Изменила программу. Теперь по времени всех медленнее для процессов(Затраченное время 0.12543120000918861) , для потоков(Затраченное время 0.09334469999885187) и без (Затраченное время 0.10052680000080727) примерно одинаковое.

2023-08-01 22:06 UTC, JuliaTanacheva commented on Practice/Tanacheva/task10.1.2.py
> +    thr1 = Thread(target=find_primes, args=(3, 10000))
Можете подсказать ,какой способ многопоточности лучше использовать для второй задачи из дз для этой лекции

2023-08-02 07:26 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.2.py
> +    thr1 = Thread(target=find_primes, args=(3, 10000))
Насчёт того, что с процессами получилось медленно... Есть понимание, почему это произошло?
Насчет "способа многопоточности") В условии задачи фигурирует операция сложения (очевидно, вычислительная) и слово "параллельно". Это однозначный намёк на то, какой механизм применить для решения задачи;)

2023-08-02 07:31 UTC, IlyaOrlov requested changes
Остались ещё вопросы и предложения по оптимизации.

2023-08-02 07:31 UTC, IlyaOrlov commented on Practice/Tanacheva/task10.1.1.py
> +                if j > int((sqrt(i))+1):
Вычисление int(sqrt(i))+1 (ещё и в 2-х строках) лучше вынести из внутреннего цикла for, чтоб на каждой итерации не пересчитывать корень из одного и того же числа.
Ну и мне бы надоело переписывать find_primes каждый раз в 3-х файлах:) Стоит вынести эту функцию в отдельный файл и импортировать, где нужно.

2023-08-09 21:13 UTC, JuliaTanacheva commented on Practice/Tanacheva/task10.1.2.py
> +    thr1 = Thread(target=find_primes, args=(3, 10000))
Программа работает с процессами медленее, чем с потоками, так как процессы требуют себе отдельное место в памяти, а потоки используют память, выделенную под процесс. Поэтому потоки создаются и завершаются быстрее, потому что систмеме не нужно каждый раз выделять им новое адресное пространство, а потом высвобождать его

2023-08-10 07:55 UTC, IlyaOrlov approved these changes
Отлично. Зачтено.

2023-08-10 07:55 UTC, merged