Практика по 14 лекции
IlyaOrlov/PythonCourse2.0_May23 pull request #155
Opened 2023-07-31 22:17 UTC by LoginovaMaria

2023-08-01 20:17 UTC, IlyaOrlov requested changes
Есть существенные замечания.

2023-08-01 20:17 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_14.py
> +        self.txt = text
В чем смысл `__init__` здесь?

2023-08-01 20:17 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_14.py
> +class MyFun:
Зачем тут класс? Можно же передавать number сразу в to_roman?

Вот если в качестве атрибута класса хранить roman_numbers - тогда класс пригодится. Но в любом случае number надо передавать в to_roman().

2023-08-01 20:17 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_14.py
> +m1 = MyFun(566)
Код в глобальной области видимости - это плохо. Особенно для тестов. Так как он может приводить к необъективным результатам.
Надо его, как минимум, под `if __name__ == '__main__'` убирать.

2023-08-01 20:17 UTC, IlyaOrlov commented on Practice/MLoginova/tests.py
> +        res = Loginova_14.m1.to_roman()
На самом деле все тесты здесь выполняются с одним и тем же объектом m1 (и конкретно с числом 566, заданным в строке 23 файла Loginova_14.py). Поэтому тест получается некорректным.

2023-08-01 20:17 UTC, IlyaOrlov commented on Practice/MLoginova/tests.py
> +        assert(res, parametrize_sum)
assert проверяет что выражение в скобках является истиной. Здесь у нас в скобках что? Правильно: кортеж из двух значений. Никакого сравнения нет. Поэтому все тесты и проходят.

2023-08-01 21:39 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_14.py
> +        self.txt = text
я хотела создать свой пользовательский класс исключений, но вероятнее всего он не нужен.

2023-08-01 21:42 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_14.py
> +class MyFun:
Да, можно и нужно без него обойтись..просто сначала через классы писать начала, хотела сохранить структуру.

2023-08-01 22:35 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_14.py
> +        self.txt = text
Подскажите, в задании указано "Этот тип ошибки надо создать отдельно", что предполагается под отдельностью? отдельный класс? или достаточно в самой функции прописать raise TypeError('NonValidInput')

2023-08-02 07:13 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_14.py
> +        self.txt = text
То, что Вы класс создали под ошибку - это верно., это и требовалось. Вопрос - конкретно про наличие конструктора `__init__` в этом классе. Зачем он? Можно же просто вместо тела класса написать pass.

2023-08-02 07:15 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_14.py
> +class MyFun:
Насчёт нужно всё-таки не уверен. roman_numbers лучше хранить в виде атрибута класса, чем в виде глобальной переменной. Можно сделать класс с единственным методом (можно классовым - для доступа к атрибуту класса roman_numbers) to_roman(cls, num).

2023-08-02 13:18 UTC, IlyaOrlov requested changes
По 13.2 оставил небольшие пожелания.

2023-08-02 13:18 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_13.2.py
> +        return ("<RegistryUL(inn='{}'), "
Можно использовать форматную строку. Пример с методом format в лекции остался ещё с давних времён)

2023-08-02 13:18 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_13.2.py
> +    input_inn = ' '
Стоит всё же отделить код, отвечающий за первичное заполнение БД, от кода для обработки запросов к БД, как в примерах с реляционными БД. Ну и желательно, чтоб данные в БД сохранялись при перезапуске скрипта)

2023-08-02 15:03 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_13.2.py
> +    input_inn = ' '
Это я для тестирования удаляла каждый раз записи(документы), с меньшим кол-вом удобнее проверять было.

2023-08-02 15:13 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_14.py
> +        self.txt = text
Да, я поняла, что не нужен. Спасибо!

2023-08-03 09:24 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_14.py
> +m1 = MyFun()
Это надо под `if __name__ == '__main__'`. А в тесте надо либо в каждом тест кейсе отдельный экземпляр MyFun создавать, либо создать атрибут тестового класса _m_test = MyFun и с ним работать. Это важно для чистоты экспериментов.

2023-08-03 09:24 UTC, IlyaOrlov commented on Practice/MLoginova/tests.py
> +        assert (Loginova_14.m1.to_roman(3459) == 'MMMCDLIX')
Надо либо в каждом тест кейсе отдельный экземпляр MyFun создавать, либо создать атрибут тестового класса _m_test = MyFun и с ним работать. Это важно для чистоты экспериментов.

2023-08-03 09:24 UTC, IlyaOrlov commented on Practice/MLoginova/tests.py
> +    def test_my_error1(self):
Три тест-кейса test_my_error отличаются только переданным значением. Почему бы не применить параметризатор (в качестве параметров будут '3459', 5521, -2)?

2023-08-03 09:24 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_13.2.py
> +        return ("<RegistryUL(inn='{}'), "
В Монго нет точного соответствия файла и базы данных. Монго использует различные служебные файлы для хранения коллекций, индексов даже в рамках одной БД.

2023-08-03 09:38 UTC, IlyaOrlov requested changes
Стало гораздо лучше. Но ещё есть, что поправить.

2023-08-03 09:38 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_13.2.py
> +    db_exists = os.path.exists(db_name)
С Монго это не прокатит)
Как вариант, проверить вывод RegistryUL.objects.count(). Если 0 объектов - предложить пользователю заполнить базу input("Отсутствуют документы в БД. Заполнить тестовыми данными? (y/n)")

2023-08-03 11:13 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_13.2.py
> +    db_exists = os.path.exists(db_name)
Добрый день!
Я это заметила пока тестировала, поэтому саму БД и начала искать. Переделала с проверкой вывода на кол-во объектов - теперь работает.

2023-08-03 11:39 UTC, LoginovaMaria commented on Practice/MLoginova/tests.py
> +    def test_my_error1(self):
Попробовала, вроде даже получилось и самой понравился теперь код) Спасибо за рекомендации!

2023-08-04 08:41 UTC, IlyaOrlov requested changes
Всё хорошо. Осталась пара нюансов.

2023-08-04 08:41 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_13.2.py
> +            input_inn = ' '
Код в стр.49-52 такой же, как в стр.41-44. Можно его вынести, если не в отдельную функцию, то точно из if-else под отдельное условие. В любом случае повторяться не стоит.

2023-08-04 08:41 UTC, IlyaOrlov commented on Practice/MLoginova/tests.py
> +        assert (self._m_test.to_roman(3459) == 'MMMCDLIX')
Внешние скобки, кстати, необязательны.

2023-08-04 11:38 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_13.2.py
> +            input_inn = ' '
Хорошо, постараюсь учесть, что повторяющегося кода надо избегать. Поправила.

2023-08-04 15:16 UTC, merged