Задания 1, 2 к лекции 6
IlyaOrlov/PythonCourse2.0_May23 pull request #157
Opened 2023-08-02 06:06 UTC by pavelzagy

2023-08-02 07:36 UTC, IlyaOrlov requested changes
Есть замечания по уткам)

2023-08-02 07:36 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW7/HW - lect 6 - task 2.py
> +        return sum_duck
Тут надо возвращать утку!
Представьте, что у Вас будет три утки:
d1 = Duck("Gus", 300)
d2 = Duck("Mike", 500)
d3 = Duck("James", 100)
и Вы захотите их сложить:
print(d1 + d2 + d3)
Сейчас будет ошибка...

2023-08-02 07:36 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW7/HW - lect 6 - task 2.py
> +print(d1.__repr__())
Магические методы не надо вызывать явно. В данном случае достаточно написать print(d1). Ещё магический метод `__repr__` можно вызывать через одноимённую функцию: repr(d1).

2023-08-02 07:39 UTC, pavelzagy commented on Practice/Zagorskiy/HW7/HW - lect 6 - task 2.py
> +print(d1.__repr__())
Принял, спасибо

2023-08-02 15:10 UTC, pavelzagy commented on Practice/Zagorskiy/HW7/HW - lect 6 - task 2.py
> +print(d1.__repr__())
исправил

2023-08-02 15:10 UTC, pavelzagy commented on Practice/Zagorskiy/HW7/HW - lect 6 - task 2.py
> +        return sum_duck
Понял, исправил

2023-08-02 15:23 UTC, pavelzagy commented on Practice/Zagorskiy/HW7/HW - lect 7 - task 3.py
> +# сервер, который создает пользователей банка и начисляет первоначальную сумму, а так же хранит все счета пользователей
У меня возник вопросик, в этом задании я в правильном направлении иду? Спасибо)

2023-08-03 10:01 UTC, IlyaOrlov requested changes
Пока, в целом, всё ОК. Замечаний по коду нет.

2023-08-03 10:01 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW7/HW - lect 7 - task 3.py
> +# сервер, который создает пользователей банка и начисляет первоначальную сумму, а так же хранит все счета пользователей
Да, направление правильное. Вопросы, если только, по бизнес-логике:
- Почему у CashMachine нет метода проверки ПИН?
- Bank (да и CashMachine, как наследник) сделан таким образом, что обслуживает только один счёт только одного клиента.
- CashMachine._cash - общий атрибут для всех банкоматов. Получается, положив деньги в одном банкомате, мы увеличим их количество сразу во всех.
В принципе, можно оставить, как есть, т.к. замечания к собственно программированию не относятся. Но вообще, стоит продумывать логику создаваемой программы тщательней.

2023-08-03 19:18 UTC, pavelzagy commented on Practice/Zagorskiy/HW7/HW - lect 7 - task 3.py
> +# сервер, который создает пользователей банка и начисляет первоначальную сумму, а так же хранит все счета пользователей
Постараюсь ответить)

1. У CashMachine не задумывалось метода проверки пин-кода, т.к. предполагается, что он работает только с наличкой. В голове было так, что пин-код нужен только, когда задействуется карта.

2. Может быть я не такой далекий, но не совсем понял, как тогда сделать. В «идеальной картине» вообще «сервер», который хранит данные пользователей и банкоматы, которые с этими данными взаимодействуют. Стоит попробовать реализовать именно этот вариант?

2023-08-04 09:09 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW7/HW - lect 7 - task 3.py
> +# сервер, который создает пользователей банка и начисляет первоначальную сумму, а так же хранит все счета пользователей
1. ОК
2. Правило "Разделяй и властвуй". Для работы со Счётом клиента нужен отдельный класс Счёт. Под каждого нового клиента, создаём экземпляр этого класса. При этом, в классе Bank может быть либо список экземпляров Счёта в качестве атрибута, либо Счёт передаётся в методы Bank в качестве параметра. В реальности такие классы (Счёт, Банк) связываются с таблицами БД через ORM. Но, чтоб не заморачиваться, в рамках задачи можно ограничиться реализацией функциональности конкретно банков и банкоматов, т.е. уменьшением и увеличением кэша в них без привязки к конкретному клиенту.
3. Нет. Наоборот. _cash должен быть атрибутом экземпляра, а не класса, и создаваться в `__init__`. Класс - это общая модель, экземпляры класса - это уже конкретные его представители (банки, банкоматы).

2023-08-10 07:36 UTC, IlyaOrlov requested changes
Хорошо. Оставил предложения по оптимизации.

2023-08-10 07:36 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW8/HW8 - task 1.py
> +        if self._i < len(self._text):
Из-за того, что мы выходим из этого метода, возвращая None, когда символ self._symbol ещё не встретился, получаются лишние выводы (поэтому, видимо, Вы и добавили в стр.31 проверку if elm). Чтоб этого избежать, достаточно здесь (в стр.13) заменить if на while. Тогда мы будем возвращать уже не пустоту, а куски накопленного в res текста - параграфы.

2023-08-10 07:36 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW8/HW8 - task4.py
> +    for i in arr:
Для решения этой подзадачи в itertools есть функция filterfalse!

2023-08-10 07:36 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW8/HW8 - task4.py
> +    return lst
Можно значительно упростить код этой функции (да и других тоже):
```python
return list(itertools.chain(a, b, c))
```

2023-08-10 08:37 UTC, pavelzagy commented on Practice/Zagorskiy/HW8/HW8 - task4.py
> +    for i in arr:
Понял, спасибо! Что меня в ней смутило - это функция в одном из позиционных аргументов. Получается, что для выполнения одного "задания" мы задействуем 2 функции, мне казалось, что выполнение будет дольше. Но, проверил свою теорию, код из библиотеки работает быстрее. Вы были правы! Спасибо) 

![2023-08-10_11-36-32](https://github.com/IlyaOrlov/PythonCourse2.0_May23/assets/103645372/5cad7750-fb61-4702-8435-9b3f3ac06ca5)

2023-08-10 08:40 UTC, pavelzagy commented on Practice/Zagorskiy/HW8/HW8 - task4.py
> +    return lst
Принял, осознал. Спасибо большое!

2023-08-10 08:42 UTC, pavelzagy commented on Practice/Zagorskiy/HW8/HW8 - task 1.py
> +        if self._i < len(self._text):
Исправил

2023-08-10 08:45 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW8/HW8 - task4.py
> +    for i in arr:
Кстати, да. В общем случае, вызов функции - это всегда дополнительные расходы. Но библиотечный код, реализованный, как правило, на C, обычно дает небольшое преимущество.

2023-08-10 08:49 UTC, IlyaOrlov approved these changes
Отлично! Зачтено. Исправления по банкоматам при необходимости можно прислать в отдельном pull request.

2023-08-10 08:49 UTC, merged