дз №10,задача 1
IlyaOrlov/PythonCourse2.0_May23 pull request #159
Opened 2023-08-03 14:56 UTC by AlenaStupina

2023-08-03 14:57 UTC, AlenaStupina commented
время выполнения:
обычная ф-ия: 0.047035999999934575
потоки: 0.04724580000038259
процессы: 0.08972659999926691
ерунда какая-то, видимо где-то ошибка, а где - не пойму

2023-08-04 08:56 UTC, IlyaOrlov commented
> время выполнения: обычная ф-ия: 0.047035999999934575 потоки: 0.04724580000038259 процессы: 0.08972659999926691 ерунда какая-то, видимо где-то ошибка, а где - не пойму

Из кода не совсем понятно, для каких конкретно блоков засекалось время (например, не попал ли случайно в тест для процессов код, запускающий потоки).
Но на самом деле, то, что процессы оказались медленнее - это допустимая ситуация для небольшого набора данных (как у нас здесь). Просто затраты времени на запуск процесса оказываются гораздо больше, чем время самих вычислений.

2023-08-04 08:57 UTC, IlyaOrlov requested changes
Хорошо. Один небольшой комментарий.
И там еще теоретические вопросы были в задании. Можно на них ответить комментариями в коде или к коду.

2023-08-04 08:57 UTC, IlyaOrlov commented on Practice/Stupina/homework_10/task_1.py
> +        if start % 2 == 0 or start == 1 or start == 0:
Имеет смысл эту проверку вынести из цикла. По определению простое число больше единицы, поэтому с 0, 1, 2 достаточно сравнить один раз.

2023-08-11 09:31 UTC, AlenaStupina commented
> > время выполнения: обычная ф-ия: 0.047035999999934575 потоки: 0.04724580000038259 процессы: 0.08972659999926691 ерунда какая-то, видимо где-то ошибка, а где - не пойму
> 
> Из кода не совсем понятно, для каких конкретно блоков засекалось время (например, не попал ли случайно в тест для процессов код, запускающий потоки). Но на самом деле, то, что процессы оказались медленнее - это допустимая ситуация для небольшого набора данных (как у нас здесь). Просто затраты времени на запуск процесса оказываются гораздо больше, чем время самих вычислений.

все так и оказалось, для большего набора данных выполнение в параллельных процессах в 2 раза меньше

2023-08-11 11:01 UTC, AlenaStupina commented
1. Что будет, если 'забыть' выполнить start или join для потоков?
если не выполнить start - потоки не запустятся
если join - продолжится выполняться главный поток ,  не дожидаясь завершения выполнения дочерних потоков - время выполнения кода будет измерено не верно (это будет время работы главного потока)
2. Что будет, если 'забыть' выполнить start или join для процессов?
start - аналогично потокам
join - аналогично потокам

2023-08-11 13:16 UTC, AlenaStupina commented
во второй задаче почему-то запускается только один процесс, я не понимаю, почему....

2023-08-11 15:57 UTC, IlyaOrlov requested changes
Остались замечания по мелочи.

2023-08-11 15:57 UTC, IlyaOrlov commented on Practice/Stupina/homework_10/task_2.py
> +    par = [tuple(par_0), (lst_1, lst_2, lst_3), ('abc', 'defgh','iklmnopqrst')]
Проще написать: tuple(range(100))

2023-08-11 15:57 UTC, IlyaOrlov commented on Practice/Stupina/homework_10/task_1.py
> +        if start < 3:
Если у нас будет вызов вида find_primes(2), то это тоже допустимое значение. Можно вернуть {} или {2} в зависимости от того, входит end в проверяемый диапазон, или нет.

2023-08-11 15:58 UTC, IlyaOrlov commented
> во второй задаче почему-то запускается только один процесс, я не понимаю, почему....

Просто один процесс решает задачу так быстро, что тут же получает следующую. Если добавить в функцию sleep, чтоб его искусственно затормозить, можно увидеть, что к решению подключаются и другие процессы.

2023-08-11 17:15 UTC, AlenaStupina commented on Practice/Stupina/homework_10/task_1.py
> +        if start < 3:
в данной логике недопустимое (я так посчитала), потому что если вызывается функция с одной переменной - эта переменная = end . А start по умолчанию (из условия дз) = 3, end не может быть меньше старта.

2023-08-11 17:22 UTC, AlenaStupina commented
> > во второй задаче почему-то запускается только один процесс, я не понимаю, почему....
> 
> Просто один процесс решает задачу так быстро, что тут же получает следующую. Если добавить в функцию sleep, чтоб его искусственно затормозить, можно увидеть, что к решению подключаются и другие процессы.

Я думала об этом, но посчитала, что если мы реализуем многопроцессорность через Pool, то задачи должны уйти в разные процессы...спасибо

2023-08-11 21:04 UTC, IlyaOrlov commented on Practice/Stupina/homework_10/task_1.py
> +        if start < 3:
В условиях д/з даны конкретные примеры (3, 10000), (10001, 20000), (20001, 30000), в которых всегда есть и start, и end. И тем не менее Вы предусматриваете возможность задания только end, стараясь сделать функцию универсальной. Интуитивно ожидаемое значение start у функции, занимающейся поиском простых чисел - минимальное простое число, т.е. 2. Согласитесь, это удобно, когда интерфейс предсказуем и интуитивно понятен. Впрочем, дело хозяйское)

2023-08-11 21:05 UTC, IlyaOrlov approved these changes
Отлично. Замечаний нет.

2023-08-11 21:05 UTC, merged

2023-08-12 06:16 UTC, AlenaStupina commented on Practice/Stupina/homework_10/task_1.py
> +        if start < 3:
Так я не спорю, просто пытаюсь объяснить, почему я так сделала , чтобы в итоге прийти к правильному решению. В дз написано так:  Написать функцию find_primes(start, end), которая ищет все простые числа в диапазоне от заданного числа start (по умолчанию 3) до заданного числа end. То есть по умолчанию только start. И он по умолчанию = 3. Соответсnвенно, если будет вызов  find_primes(2), то это значит, что  end = 2. 
Но я согласна, что логически правильно так, как говорите Вы, start по умолчанию должен быть равен 2, но в задании то по-другому написано, возможно, я не так трактую задание...