Практика по лекции: Параллельное программирование
IlyaOrlov/PythonCourse2.0_May23 pull request #161
Opened 2023-08-06 12:33 UTC by LoginovaMaria

Если судить об общем времени для 3-ёх диапазонов, то наименьшее время вычислений при использовании процессов, затем обычная функция и уже потом с помощью потоков. Если судить о времени вычислении в разрезе каждого диапазона тут сложнее, медленнее всего отработало с использованием потоков. 
Замеры приведtны в комментариях для каждого варианта.

2023-08-06 13:36 UTC, LoginovaMaria commented
Буду переделывать  ф-цию find_primes, алгоритм поиска простых чисел, не корректный( 4 проходит как простое, а оно не простое..

2023-08-07 08:04 UTC, IlyaOrlov commented
> Если судить об общем времени для 3-ёх диапазонов, то наименьшее время вычислений при использовании процессов, затем обычная функция и уже потом с помощью потоков. Если судить о времени вычислении в разрезе каждого диапазона тут сложнее, медленнее всего отработало с использованием потоков. Замеры приведtны в комментариях для каждого варианта.

Судя по рассчитанному времени:
`# Без всего: 0.007450300035998225`
`# Процессы: 0.07697579998057336`
`# Потоки: 0.031286600045859814`
самый худший результат у процессов. И этому есть логичное объяснение, связанное с затратами ОС на создание и запуск процесса! Сможете привести такое объяснение?

2023-08-07 08:05 UTC, IlyaOrlov requested changes
Есть вопрос по подсчёту времени выполнения.

2023-08-07 11:27 UTC, LoginovaMaria commented
> > Если судить об общем времени для 3-ёх диапазонов, то наименьшее время вычислений при использовании процессов, затем обычная функция и уже потом с помощью потоков. Если судить о времени вычислении в разрезе каждого диапазона тут сложнее, медленнее всего отработало с использованием потоков. Замеры приведtны в комментариях для каждого варианта.
> 
> Судя по рассчитанному времени: `# Без всего: 0.007450300035998225` `# Процессы: 0.07697579998057336` `# Потоки: 0.031286600045859814` самый худший результат у процессов. И этому есть логичное объяснение, связанное с затратами ОС на создание и запуск процесса! Сможете привести такое объяснение?

2023-08-07 11:32 UTC, LoginovaMaria commented
Не очень поняла, какое объяснение нужно привести, т.к. Вы сами озвучили почему через процессы отработало медленнее - по причине затрат ОС на создание и запуск процесса)

2023-08-07 11:57 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_10.1.py
> +        print(f'{i+1}.Время вычислений в секундах: {time.perf_counter() - start}')
Поняла, поправила. После перезапуска получилось:
Без всего: 0.030037499964237213
Процессы: 0.03076120000332594
Потоки: 0.031701300060376525
Т.е. всех медленнее потоки, затем процессы и без всего - лучший результат.
Потоки вероятно медленнее из-за GIL, только один поток может исполнять код.

2023-08-07 19:47 UTC, IlyaOrlov commented
> Не очень поняла, какое объяснение нужно привести, т.к. Вы сами озвучили почему через процессы отработало медленнее - по причине затрат ОС на создание и запуск процесса)

Ну так-то, да) Но можно ещё добавить, что затраты времени на создание и запуск процесса значительно превышают время выполнения процессов. Поэтому использовать процессы на таких небольших расчетах - всё равно, что стрелять из пушки по воробьям. Ну а потоки в любом случае тут (в явной CPU-bound задаче) бесполезны.

2023-08-07 19:47 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-08-07 19:47 UTC, merged