Задача 5.4
IlyaOrlov/PythonCourse2.0_May23 pull request #162
Opened 2023-08-06 13:18 UTC by Dkisunkina

2023-08-07 07:32 UTC, IlyaOrlov requested changes
Одно небольшое замечание.

2023-08-07 07:32 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 5/homework 5.4.py
> +    number = int(input("Введите число от 0 до 10"
number всё-таки стоит задавать вне search_columns и передавать сюда в качестве аргумента.
Это позволить вызывать search_columns для фиксированной матрицы и искомого числа, что значительно облегчит, например, написание автотестов для этого кода.

2023-08-09 08:46 UTC, IlyaOrlov requested changes
Хорошо. Остались замечания по мелочи.

2023-08-09 08:46 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 5/homework 5.5.py
> +    with open(name, "r") as filename:
filename и new_filename - не самые подходящие переменные для указания на файловый объект. По смыслу больше подойдут file и new_file.

2023-08-09 09:39 UTC, Dkisunkina commented on Practice/Kisunkina/lec 5/homework 5.4.py
> +    number = int(input("Введите число от 0 до 10"
перенесла

2023-08-09 09:39 UTC, Dkisunkina commented on Practice/Kisunkina/lec 5/homework 5.5.py
> +    with open(name, "r") as filename:
подправила, спасибо

2023-08-10 07:25 UTC, IlyaOrlov requested changes
Один нюанс остался!

2023-08-10 07:25 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 5/homework 5.4.py
> +    arr = search_columns(matrix)
Лучше передать number в search_columns в качестве аргумента. Функция, не использующая глобальные переменные, является более гибкой, безопасной и удобной для тестирования.

2023-08-10 09:04 UTC, Dkisunkina commented on Practice/Kisunkina/lec 5/homework 5.4.py
> +    arr = search_columns(matrix)
исправила!

2023-08-10 10:04 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-08-10 10:04 UTC, merged