Задача 1 к лекции 14
IlyaOrlov/PythonCourse2.0_May23 pull request #170
Opened 2023-08-10 11:58 UTC by DmitriySapegov

На антитренинги залил уже.
Может есть что улучшить в коде тестов? Не нравятся повторяющиеся методы, но через параметризацию ничего не смогу придумать.
Сделал специально чтобы на нескольких значениях тест падал, чтобы проверить сам тест)

2023-08-12 15:00 UTC, IlyaOrlov requested changes
Есть некоторые замечания!

2023-08-12 15:00 UTC, IlyaOrlov commented on Practice/Sapegov/HW_14/Sap14_1.py
> +        raise NonValidInputError('NonValidInput')
Не вижу особого смысла в том, чтоб перехватывать исключение ради вывода на печать. Но если очень нужно так сделать и перевыбросить исключение, лучше делать так:
```python
    except NonValidInputError as ex:
        print('Вы ввели не число, либо число вышло из диапазона')
        raise ex
```
Чтоб пробросить прямо это же исключение.

2023-08-12 15:00 UTC, IlyaOrlov commented on Practice/Sapegov/HW_14/tests.py
> +    def test_to_roman3(self):
Так можно же по аналогии с test_exception (негативный сценарий) так же, через параметризатор проверить одним методом различные позитивные сценарии
```python
    @pytest.fixture(
        scope='function',
        params=[('8', 'VIII'), ('4509', 'MMMMDIX'), ('5000', 'MMMMM')],
        ids=lambda args: f"Test with args: '{args}'"
    )
    def positive_parametrs(self, request):
        return request.param
```

2023-08-12 15:00 UTC, IlyaOrlov commented on Practice/Sapegov/HW_14/tests.py
> +        assert(to_roman('5000') == 'MM')
Как-то маловато букв M:)

2023-08-12 15:26 UTC, DmitriySapegov commented on Practice/Sapegov/HW_14/Sap14_1.py
> +        raise NonValidInputError('NonValidInput')
Делать без try/except?
У меня тогда в тестах же не поймает ошибку

2023-08-12 15:28 UTC, DmitriySapegov commented on Practice/Sapegov/HW_14/tests.py
> +        assert(to_roman('5000') == 'MM')
Это было сделано специально ради тестов теста)) Посмотреть, что тест корректно работает)

2023-08-12 16:03 UTC, IlyaOrlov commented on Practice/Sapegov/HW_14/Sap14_1.py
> +        raise NonValidInputError('NonValidInput')
Поймает) 
Не поймает, если перехватывать исключение.

2023-08-13 14:48 UTC, IlyaOrlov requested changes
Остались вопросы/замечания по мелочи.

2023-08-13 14:48 UTC, IlyaOrlov commented on Practice/Sapegov/HW_8/Sap8.4.py
> +def filter_mas(x2):
Определения функция должны быть выше основного кода.

2023-08-13 14:48 UTC, IlyaOrlov commented on Practice/Sapegov/HW_14/tests.py
> +        res = positive_parametrs[1]
Можно короче:
arg, res = positive_parametrs

2023-08-13 14:48 UTC, IlyaOrlov commented on Practice/Sapegov/HW_8/Sap8.4.py
> +res = combinations(word, length)
А что сразу весь res не напечатать?

2023-08-13 15:37 UTC, DmitriySapegov commented on Practice/Sapegov/HW_8/Sap8.4.py
> +res = combinations(word, length)
Так ведь тогда он будет длинным некрасивым списком(

2023-08-14 11:52 UTC, IlyaOrlov commented on Practice/Sapegov/HW_8/Sap8.4.py
> +res = combinations(word, length)
А, ну если так, то ... ОК)

2023-08-14 11:53 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-08-14 11:53 UTC, merged