Задачи к лекции №2
IlyaOrlov/PythonCourse2.0_May23 pull request #22
Opened 2023-05-15 21:39 UTC by DmitriySapegov

Надеюсь я не испортил общую третью задачу)

2023-05-16 07:49 UTC, IlyaOrlov requested changes
Всё хорошо, но по pep8task.py есть некоторые замечания: надо уточнить комментарии.

2023-05-16 07:49 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +from time import *     # на данном уровне не могу определить какие библиотеки стандартные, а какие сторонние
А и не нужно) Но здесь есть другое нарушение: такая форма импорта со звёздочкой (буквально означает "импортировать из time ВСЁ") [крайне НЕ желательна](https://peps.python.org/pep-0008/#imports:~:text=Wildcard%20imports%20(from%20%3Cmodule%3E%20import%20*)).

2023-05-16 07:49 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +            os.rename(path + '/' + mp3), path + '/' + hashname))  # 2 лишних скобки после hashname
Да, две лишние скобки, но не две крайние, а две внутренние.

2023-05-16 07:49 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +          f = open(output, 'r')                                   # нужно добавить 2 пробела
В стр.24-25 не всё так однозначно. Здесь стоило написать так же, как Вы написали в стр.30.
Если добавить пробелы, эти строки попадут внутрь цикла for и будут повторятся многократно (по факту, в файл будет перезаписываться значение переменной self.map).
Если убрать пробелы, строки будут вынесены из цикла, и в файл однократно запишется только итоговое значение переменной self.map (что гораздо эффективней).

2023-05-16 07:49 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +        os.remove(restore_path)                              # нужно добавить 4 пробела
Здесь так же как в стр.24-25, только речь идёт о многократном удалении одного и того же файла)

2023-05-17 14:26 UTC, DmitriySapegov commented on Practice/Sapegov/pep8task.py
> +from time import *     # на данном уровне не могу определить какие библиотеки стандартные, а какие сторонние
Правильно ли понял, что это тоже самое, что и import time?

2023-05-17 14:34 UTC, DmitriySapegov commented on Practice/Sapegov/pep8task.py
> +          f = open(output, 'r')                                   # нужно добавить 2 пробела
Согласен. Не вчитываясь в код, довольно сложно определить, строчки должны быть внутри конструкции, либо снаружи. Я увидел, что так точно не правильно, но не угадал в какую сторону их утащить)

2023-05-17 14:34 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +from time import *     # на данном уровне не могу определить какие библиотеки стандартные, а какие сторонние
По сути, то же самое. Разница в способах доступа. Например, в модуле (библиотеке) time есть функция sleep. Получаем такие варианты обращения к этой функции:
1.
```python
import time  # безопасный импорт

time.sleep(5)
```
2.
```python
from time import *  # опасный импорт

sleep(5)
```
Если вдруг в нашем файле оказалась бы функция с таким же именем (sleep), во втором случае было бы непонятно, какую функцию мы вызываем.
При безопасном же импорте мы чётко можем определить к функции какого модуля хотим обратится.

2023-05-17 14:36 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +          f = open(output, 'r')                                   # нужно добавить 2 пробела
Ага) Поэтому в таких случаях комментарий: "2 лишних пробела, либо добавить 2"  - 100%-й вариант)

2023-05-17 15:00 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +    def __init__(self):                      # совершенно не понял про магию))
А что с магией? Здесь вроде всё корректно?)

2023-05-18 14:43 UTC, DmitriySapegov commented on Practice/Sapegov/pep8task.py
> +    def __init__(self):                      # совершенно не понял про магию))
в целом не понятно описание в презентации про магические методы или атрибуты

2023-05-18 18:15 UTC, IlyaOrlov commented on Practice/Sapegov/pep8task.py
> +    def __init__(self):                      # совершенно не понял про магию))
Ааа.. ну это мы ещё пройдём) Там большая тема!

2023-05-18 18:15 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-05-18 18:15 UTC, merged