Svetlova
IlyaOrlov/PythonCourse2.0_May23 pull request #24
Opened 2023-05-16 06:09 UTC by Svetlya23

2023-05-16 07:59 UTC, IlyaOrlov requested changes
Есть некоторые замечания. Ну и папку, наверное, лучше всё же какую-то одну оставить.

2023-05-16 07:59 UTC, IlyaOrlov commented on Practice/ESvetlova/myntest.py
Видимо этот Pull Request https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/23 лишний (надо его тогда закрыть), но замечания из него применимы и здесь.

2023-05-16 07:59 UTC, IlyaOrlov commented on Practice/Svetlova/my1.py
> +a="Echo:"
Согласно PEP8 вокруг знака "=" [должно быть по одному пробелу](https://peps.python.org/pep-0008/#:~:text=Always%20surround%20these%20binary%20operators%20with%20a%20single%20space%20on%20either%20side%3A%20assignment%20(%3D)%2C%20augmented%20assignment%20(%2B%3D%2C%20%2D%3D%20etc.)%2C%20comparisons%20(%3D%3D%2C%20%3C%2C%20%3E%2C%20!%3D%2C%20%3C%3E%2C%20%3C%3D%2C%20%3E%3D%2C%20in%2C%20not%20in%2C%20is%2C%20is%20not)%2C%20Booleans%20(and%2C%20or%2C%20not).).

2023-05-17 16:14 UTC, Tetrackon commented on Practice/Svetlova/my1.py
> +
Теперь всё хорошо :) Можете приступать к следующему заданию

2023-05-17 17:19 UTC, IlyaOrlov requested changes
Есть замечания по новым заданиям.

2023-05-17 17:19 UTC, IlyaOrlov commented on Practice/Svetlova/ДЗ к лекции 2.py
> +distance = int (input("Расстояние: "))
Согласно [PEP8](https://peps.python.org/pep-0008/#blank-lines:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call%3A) пробелов между именем функции (int) и последующей открывающей скобкой быть не должно.

2023-05-17 17:19 UTC, IlyaOrlov commented on Practice/Svetlova/ДЗ к лекции 2.py
> +
Здесь и ниже лишние пустые строки.

2023-05-18 06:44 UTC, Svetlya23 commented
Добрый день. направила исправленное ДЗ ко 2 лекции.

2023-05-18 08:25 UTC, IlyaOrlov commented on Practice/Svetlova/ДЗ к лекции 2.py
> +diff =int(start) - int(end)
В стр.16 и 17: не хватает пробела после =.

2023-05-18 08:27 UTC, IlyaOrlov commented on Practice/Svetlova/pep8.py
> +        # отступ должен быть 4 пробела, здесь отступили лишнего строка 17
Нет. В стр.17, 18 с отступами все хорошо: просто цикл внутри цикла.

2023-05-18 08:29 UTC, IlyaOrlov commented on Practice/Svetlova/pep8.py
> +        # строки ниже опять лишний отступ 28,29, 32,34
Насчёт строк 28,29 - согласен (правда, написали, что отступ лишний, а строки сдвинули вправо).
А со стр.32-34 на самом деле всё ОК)

2023-05-18 08:29 UTC, IlyaOrlov commented on Practice/Svetlova/pep8.py
> +        return hashlib.md5(str(seed)).hexdigest()
Тут, правда, был пробел?

2023-05-20 18:07 UTC, Svetlya23 commented
Добрый день. замечания по практике ко 2 лекции были исправлены, прошу проверить. Единственное, что было с пробелом не помню :) был ли он или не был, просто удалила этот комментарий.

2023-05-20 18:37 UTC, IlyaOrlov requested changes
Остались замечания по pep8.py

2023-05-20 18:37 UTC, IlyaOrlov commented on Practice/Svetlova/pep8.py
> +        return hashlib.md5(str(seed)).hexdigest()
Всегда же можно сравнить с оригиналом - Tasks/pep8task.py
А лишний пробел действительно был(
Если всё-таки удалили комментарий, то строку пустую (с.45) тоже оставлять нет смысла.

2023-05-20 18:37 UTC, IlyaOrlov commented on Practice/Svetlova/pep8.py
> +
В этой строке (с.15) у Вас был правильный комментарий! Неправильный комментарий - про строки 17 и 18.

2023-05-20 18:58 UTC, IlyaOrlov requested changes
Теперь замечание по DZ3.py

2023-05-20 18:58 UTC, IlyaOrlov commented on Practice/Svetlova/DZ3.py
> +a=int(input ("Введите длину"))
Согласно PEP8 вокруг знака **=** должно быть [по одному пробелу](https://peps.python.org/pep-0008/#:~:text=Always%20surround%20these%20binary%20operators%20with%20a%20single%20space%20on%20either%20side), а между input и открывающей скобкой пробела быть [не должно](https://peps.python.org/pep-0008/#function-and-method-arguments:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call).

2023-05-20 19:05 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2023-05-20 19:06 UTC, merged

2023-05-20 19:08 UTC, Svetlya23 commented
Ура! Это маленькая победа