Add files via upload
IlyaOrlov/PythonCourse2.0_May23 pull request #27
Opened 2023-05-16 16:46 UTC by KirillLazarev

Первая и вторая задача

2023-05-16 17:39 UTC, IlyaOrlov requested changes
Всё хорошо. Один вопрос оставил.
Ещё вижу, что файлы добавлены через браузер. Для синхронизации Вашего локального бранча с Вашим удаленным надо будет выполнить git pull, иначе потом гит будет ругаться.

2023-05-16 17:39 UTC, IlyaOrlov commented on Practice/Lazarev/HW2.2.py
> +result = int(diff) / int(distance)
diff - и так int, т.к. представляет собой разность двух чисел

2023-05-17 12:47 UTC, KirillLazarev commented
Спасибо! Отправлял файлы через PyCharm. git pull сделал

2023-05-17 13:48 UTC, IlyaOrlov requested changes
Эти два файла
[pep8HW2.3.py](https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/27/files#diff-f75d07d8423a15871912a2270079408e9770b941531aab4feae4a46529089d8d)
[pep8HW23.py](https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/27/files#diff-ba81e0505ebab837092cb8f5c9a15b705081411d257dba93217e9bc0c698bec4)
вроде как лишние.
Что касается чужих файлов в этом Pull Request, надо в PyCharm сделать Git -> Pull (origin **main**) и Git->Push.

2023-05-17 13:48 UTC, IlyaOrlov commented on Practice/Lazarev/HW2.3.pep8.py
> +        for path, mp3 in mp3s:                          # удалить отступ перед for
Тогда for выйдет из пределов метода rename и останется вроде как внутри класса Shufflee, но вне каких либо методов. А так делать нельзя.

2023-05-17 14:04 UTC, KirillLazarev commented
"Что касается чужих файлов в этом Pull Request, надо в PyCharm сделать Git -> Pull (origin main) и Git->Push."
Сделал и ничего не поменялось. 
Не понимаю как их удалить из гитхаб

2023-05-18 08:19 UTC, IlyaOrlov requested changes
С гитом всё исправилось. Осталось ликвидировать замечания.

2023-05-18 09:37 UTC, IlyaOrlov commented
> исправил

ОК. Ещё замечание по файлу Practice/Lazarev/HW2.2.py

2023-05-18 16:44 UTC, KirillLazarev commented
Исправил

2023-05-18 18:13 UTC, IlyaOrlov approved these changes
Отлично! Нет больше замечаний.

2023-05-18 18:14 UTC, merged