task1
IlyaOrlov/PythonCourse2.0_May23 pull request #48
Opened 2023-05-19 21:37 UTC by Lud-mila88

2023-05-20 09:38 UTC, IlyaOrlov requested changes
Всё супер! Один небольшой комментарий.

2023-05-20 09:38 UTC, IlyaOrlov commented on Practice/Kulinich/dz3.2.py
> +result = (int(d)/int(t))
Здесь внешние скобки не нужны. И вообще, лишних символов всегда стоит избегать.
В остальных файлах так же.

2023-05-21 16:25 UTC, IlyaOrlov requested changes
Пробел после print добавлять не следовало.

2023-05-21 16:25 UTC, IlyaOrlov commented on Practice/Kulinich/dz3.2.py
> +print (f"Средняя скорость равна {result}  ")
Здесь тоже не должно быть пробела между print и открывающей скобкой.

2023-05-21 16:25 UTC, IlyaOrlov commented on Practice/Kulinich/dz3.1.py
> +print (f"Периметр прямоугольника равен :{result}  ")
Пробел между именем функции и открывающей скобкой нарушает [требование PEP8](https://peps.python.org/pep-0008/#:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call%3A).

2023-05-21 19:21 UTC, Lud-mila88 commented on Practice/Kulinich/dz3.1.py
> +print (f"Периметр прямоугольника равен :{result}  ")
Исправила,спасибо!

2023-05-21 19:23 UTC, IlyaOrlov approved these changes
Ну теперь вообще красота получилась) Отлично!

2023-05-21 19:24 UTC, merged