Первый
IlyaOrlov/PythonCourse2.0_May23 pull request #5
Opened 2023-05-14 08:40 UTC by Dimaly123

2023-05-15 07:36 UTC, IlyaOrlov requested changes
Всё супер! Только небольшие пожелания по стилю.

2023-05-15 07:36 UTC, IlyaOrlov commented on Practice/Lyagin/my2.py
> +x=input("Введите значение основания: ")
Всё ОК! По коду замечаний нет. Но есть одно по стилю ([стандарт PEP8](https://peps.python.org/pep-0008/), который мы сегодня ещё пройдём): вокруг знака "=" [должно быть по одному пробелу](https://peps.python.org/pep-0008/#:~:text=Always%20surround%20these%20binary%20operators%20with%20a%20single%20space%20on%20either%20side%3A%20assignment%20(%3D)%2C%20augmented%20assignment%20(%2B%3D%2C%20%2D%3D%20etc.)%2C%20comparisons%20(%3D%3D%2C%20%3C%2C%20%3E%2C%20!%3D%2C%20%3C%3E%2C%20%3C%3D%2C%20%3E%3D%2C%20in%2C%20not%20in%2C%20is%2C%20is%20not)%2C%20Booleans%20(and%2C%20or%2C%20not).).
Ну и лишние пустые строки (7-9) в конце файла не нужны (одну можно оставить).

2023-05-16 16:19 UTC, Dimaly123 commented on Practice/Lyagin/my2.py
> +x=input("Введите значение основания: ")
Исправил.

2023-05-16 17:45 UTC, IlyaOrlov requested changes
Всё хорошо. Только ещё одно небольшое замечание по стилю в файле Behzin.py

2023-05-18 14:57 UTC, Dimaly123 commented on Practice/Lyagin/Behzin.py
> +start = input("Топлива было: "); end = input("Топлива осталось: ")
Да, конечно, это сразу в глаза бросается, что не должно вроде как быть в одну троку...Но запустил, сработало, значит получается понимает и так)

2023-05-18 18:12 UTC, IlyaOrlov commented on Practice/Lyagin/Behzin.py
> +start = input("Топлива было: "); end = input("Топлива осталось: ")
Да, интерпретатор понимает. Но в Python важно ещё, чтоб код был понятен и легко читаем для человека, которой его будет потом дорабатывать и поддерживать.

2023-05-19 06:56 UTC, IlyaOrlov approved these changes
Всё отлично!

2023-05-19 06:56 UTC, merged