Create my1work.py
IlyaOrlov/PythonCourse2.0_May23 pull request #50
Opened 2023-05-20 10:14 UTC by Alexey152RUS

2023-05-20 10:15 UTC, Alexey152RUS commented
Начало

2023-05-20 10:29 UTC, IlyaOrlov requested changes
Начало хорошее, но есть одно замечание.

2023-05-20 10:29 UTC, IlyaOrlov commented on Practice/my1work.py
Вот это файл my1work.py должен лежать не просто в папке Practice, а в Вашей папке, которую надо создать внутри Practice.

2023-05-20 10:50 UTC, Alexey152RUS commented on Practice/my1work.py
поправил?

2023-05-20 10:52 UTC, IlyaOrlov commented on Practice/my1work.py
Нет. Надо переместить файл в папку, сделать снова git add, git commit, git push.

2023-05-20 11:01 UTC, Alexey152RUS commented on Practice/my1work.py
так?

2023-05-20 11:10 UTC, IlyaOrlov commented on Practice/my1work.py
Ничего не изменилось. Вы сами можете видеть результат здесь на вкладке Files changed (https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/50/files)

2023-05-20 14:29 UTC, IlyaOrlov commented on Practice/my1work.py
Теперь с файлом my1work.py всё супер! Его можно больше не трогать.
Плохо, что сюда (в Pull Request) попала папка **.idea**. Это служебная папка PyCharm. Чтоб исправить ситуацию,  я эту папку удалю с Вашего бранча. Вам надо только сделать git pull origin APripisnov (не main).
После этого папка всё равно может появиться у Вас на компьютере (её PyCharm автоматически пересоздаёт). И чтоб она больше в Pull Request не попадала, добавьте её в .gitignore, как показано на рисунке 
![image](https://github.com/IlyaOrlov/PythonCourse2.0_May23/assets/14909169/73cb5c24-4311-4722-91f0-69a5810b013a)
Ну или просто не отмечайте галочкой в окне Git->Commit)

2023-05-20 14:43 UTC, Alexey152RUS commented on Practice/my1work.py
я попробовал в бранче Pripisnov, который ниже

2023-05-20 14:45 UTC, IlyaOrlov commented on Practice/my1work.py
В смысле в папке Pripisnov?) Если всё получилось, то у меня больше вопросов нет. Можно двигаться дальше)

2023-05-21 12:28 UTC, IlyaOrlov commented on Practice/Pripisnov/work/my2work.py
> +
Здесь не хватает пустой строки ([PEP8](https://peps.python.org/pep-0008/#blank-lines:~:text=Surround%20top%2Dlevel%20function%20and%20class%20definitions%20with%20two%20blank%20lines.))

2023-05-21 12:32 UTC, IlyaOrlov commented on .gitignore
> +/Practice/Pripisnov/venv/.idea/
Чтоб не менять общий файл .gitignore, можно вместо этого сделать ещё один файл .gitignore в своей папке /Practive/Pripisnov и там прописать:
/venv/
/.idea/
/work/.idea/

2023-05-21 16:31 UTC, IlyaOrlov requested changes
Хорошо. Ещё немного исправить, и будет отлично.

2023-05-21 16:31 UTC, IlyaOrlov commented on .gitignore
Изменения в этом файле теперь можно откатить, т.к. у Вас уже есть свой собственный .gitignore

2023-05-21 16:31 UTC, IlyaOrlov commented on Practice/Pripisnov/work/my2work.py
> +
Две пустые строки - как-то многовато для основного кода... Файл большой становится, листать долго))
Пустые строки в конце файла (с.13 и с.14) - тоже лишние. Одна пустая строка должна быть, но не больше.

2023-05-21 17:35 UTC, IlyaOrlov requested changes
Всё хорошо. Замечания остались только по .gitignore и my2.1work.py

2023-05-21 17:35 UTC, IlyaOrlov commented on Practice/Pripisnov/work/my2.1work.py
> +
И здесь пустая строка нужна. Определение функции с обеих сторон двумя пустыми строками отделяется.

2023-05-24 17:35 UTC, IlyaOrlov requested changes
Всё хорошо! Остался только старый комментарий по .gitignore, и добавил ещё один новый.

2023-05-24 17:56 UTC, Alexey152RUS commented on Practice/Pripisnov/work/my3.2work.py
> +v = (s/t)
Комментарий по .gitignore, я не понимаю ,как исправить

2023-05-24 18:14 UTC, Alexey152RUS commented on Practice/Pripisnov/work/my3.2work.py
> +v = (s/t)
Сейчас получилось?

2023-05-24 18:49 UTC, IlyaOrlov commented on Practice/Pripisnov/work/my3.2work.py
> +v = (s/t)
![image](https://github.com/IlyaOrlov/PythonCourse2.0_May23/assets/14909169/60a1aa14-f5cf-457e-a465-357101beee2b)
вот так должен выглядеть этот файл

2023-05-25 16:42 UTC, IlyaOrlov requested changes
Супер! С .gitignore разобрались! Осталось скобки из my3.2work.py убрать

2023-05-27 14:53 UTC, IlyaOrlov approved these changes
Теперь всё отлично! Зачтено

2023-05-27 14:53 UTC, merged

2023-05-27 16:13 UTC, Alexey152RUS commented
я работу выполнил на main, как подтянуть на свой бранч?

2023-05-27 20:10 UTC, IlyaOrlov commented
> я работу выполнил на main, как подтянуть на свой бранч?

1. Если commit еще не сделали, то в PyCharm -> Git -> Branches -> выбираете свой (Pripisnov) -> Checkout. Ну идальше как обычно: commit, push.
2. Если сделали, то придётся скопировать файлы в отдельное место, также переключиться на свой бранч (как в п.1) и обратно вставить скопированные ранее файлы.