O lunina
IlyaOrlov/PythonCourse2.0_May23 pull request #51
Opened 2023-05-20 14:25 UTC by LesyaLunina

2023-05-20 14:43 UTC, IlyaOrlov requested changes
Хорошо. Но есть некоторые замечания.

2023-05-20 14:43 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.1.py
> +
Ещё одна пустая строка нужна по [PEP8](https://peps.python.org/pep-0008/#blank-lines:~:text=Surround%20top%2Dlevel%20function%20and%20class%20definitions%20with%20two%20blank%20lines.)

2023-05-20 14:43 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +# Class  пишется с нижним подчеркиванием. А название с большой буквы Shuffler
class - служебное слово для создания классов (так же, как def - для функций), с ним всё хорошо. А про название класса согласен.

2023-05-20 14:43 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +                mp3s.append([root, file])
Относительно чего здесь отступы?

2023-05-20 14:43 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +# time - стандартная б-ка. Д.б. в начале импортов
Остальные тоже стандартные. Ошибка здесь [в другом](https://peps.python.org/pep-0008/#blank-lines:~:text=Wildcard%20imports%20(from%20%3Cmodule%3E%20import%20*)%20should%20be%20avoided). При таком импорте всё содержимое импортируемого модуля доступно в нашем файле напрямую. Например, в модуле (библиотеке) time есть функция sleep. К ней теперь надо обращаться так:

```python
from time import *  # опасный импорт

sleep(5)
```
Если вдруг в нашем файле оказалась бы функция с таким же именем (sleep), во втором случае было бы непонятно, какую функцию мы вызываем. 
А должно быть так:

```python
import time  # безопасный импорт

time.sleep(5)
```

При безопасном импорте мы чётко можем определить к функции какого модуля хотим обратится.

2023-05-20 14:50 UTC, Tetrackon requested changes
Третье задание это задание на понимание. Найти  три ошибки это уже хорошо, но попробуйте ещё посмотреть :) 
Подсказка: Pycharm подчёркивает все ошибки, если навести курсор на них, он покажет что не так, в большинстве случаев. 
Подсказка 2.0: под ошибками могут подразумеваться нежелательные действия.

2023-05-20 14:50 UTC, Tetrackon requested changes
Третье задание это задание на понимание. Найти  три ошибки это уже хорошо, но попробуйте ещё посмотреть :) 
Подсказка: Pycharm подчёркивает все ошибки, если навести курсор на них, он покажет что не так, в большинстве случаев. 
Подсказка 2.0: под ошибками могут подразумеваться нежелательные действия.

2023-05-20 14:53 UTC, LesyaLunina reviewed
Здесь тоже не хватает пустой последней строки

2023-05-20 14:53 UTC, LesyaLunina commented on Practice/Lunina/Practice 2/Task 2.3.py
> +# time - стандартная б-ка. Д.б. в начале импортов
Где про импорт и работу с ним можно более подробно прочитать?

2023-05-20 14:53 UTC, LesyaLunina commented on Practice/Lunina/Practice 2/Task 2.3.py
> +# Class  пишется с нижним подчеркиванием. А название с большой буквы Shuffler
Поняла. Приняла.

2023-05-20 14:53 UTC, LesyaLunina commented on Practice/Lunina/Practice 2/Task 2.3.py
> +                mp3s.append([root, file])
Посмотрю ещё раз внимательнее.

2023-05-20 14:53 UTC, LesyaLunina commented on Practice/Lunina/Practice 2/Task 2.1.py
> +
В самом конце кода. Исправлю

2023-05-20 14:58 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.1.py
> +
Между определением функции (стр.4-5) и основным кодом должно быть две пустые строки.

2023-05-20 15:02 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +# time - стандартная б-ка. Д.б. в начале импортов
Здесь -> https://habr.com/ru/articles/713458/
Здесь -> https://tproger.ru/translations/guide-into-python-imports/
А вот здесь вообще оригинальная документация Python -> https://docs.python.org/3/reference/import.html
...
Но на самом деле для понимания стиля импортов достаточно того, что описано в лекции и вот [этой секции](https://peps.python.org/pep-0008/#imports) PEP8:)
Технический же аспект применения импортов мы ещё пройдём в рамках базового курса.

2023-05-20 15:04 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +# Class  пишется с нижним подчеркиванием. А название с большой буквы Shuffler
Комментарий стоит скорректировать.

2023-05-20 15:07 UTC, LesyaLunina reviewed
Посмотрите 2.2 задание?

2023-05-20 15:09 UTC, LesyaLunina commented on Practice/Lunina/Practice 2/Task 2.3.py
> +# time - стандартная б-ка. Д.б. в начале импортов
По лекции, я только сделала вывод что импорт неправильно написан и что это стандартная библиотека. А то что функции по другому нужно писать, им ходя из написания импорта я и не знала. Вот и хочу пробелы восполнить

2023-05-20 15:29 UTC, IlyaOrlov commented
> Посмотрите 2.2 задание?

С ним всё ОК. Остались замечания по Task 2.3.py

2023-05-21 16:08 UTC, LesyaLunina reviewed
Внесены изменения

2023-05-21 16:45 UTC, IlyaOrlov requested changes
Появились новые вопросы и замечания.

2023-05-21 16:45 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +          #Здесь отступ 2 пробела - правильно по PEP 8 отступ- 4 пробела
Смотря относительно чего надо отступать) Если по-правильному - то 4 пробела относительно верхней строки. Значит, здесь надо как раз 2 лишних пробела убрать.

2023-05-21 16:45 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +            # В конце двойная скобка.
Так по паре же для каждой открывающей скобки) Может, не только в конце лишние скобки?

2023-05-21 16:45 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +          # в конце строки поставить ";"
А зачем?

2023-05-21 16:45 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +            # функция библиотеки os.  удалить.  В скобках дословный перевод: восстановление части
На самом деле restore_path - это переменная - параметр функции (см. стр. 31), поэтому её в кавычках указывать не надо. Про функции и передачу в них параметров мы ещё поговорим на лекциях.

2023-05-21 16:45 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +            # между return hashlib д.б. нижнее подчеркивание
Нет. return - ключевое слово для возврата значения из функции, hashlib - название библиотеки, которой мы здесь пользуемся (см. стр. 3).

2023-05-21 19:41 UTC, LesyaLunina commented on Practice/Lunina/Practice 2/Task 2.3.py
> +          # в конце строки поставить ";"
Так РС убирает ошибку, в ошибках посмотрела )) вместо 10 - 9 красных кружков

2023-05-21 19:46 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +          # в конце строки поставить ";"
Если в вычислении сделать чётное количество ошибок, то можно получить правильный ответ) Нашёл целую [теорию ](http://www.kulichki.com/moshkow/ANEKDOTY/errors.txt#:~:text=%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8%20%D0%B4%D0%BE%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D1%8E%D1%82%20%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE%D0%BA%D1%80%D0%B0%D1%82%D0%BD%D0%BE%D0%B5%20%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B4%D1%80%D1%83%D0%B3%20%D0%B2%20%D0%B4%D1%80%D1%83%D0%B3%D0%B0.%20%D0%94%D0%B2%D0%B5%20%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0%2D%0A%D0%BA%D0%BE%D0%B2%D1%8B%D0%B5%20%D0%B2%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8%20%D0%BD%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%8E%D1%82%D1%81%D1%8F%20%D1%87%D0%B5%D1%82%D0%BD%D0%BE%D0%B9%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%BE%D0%B9%20%D0%B8%20%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%BE%D0%B9%20%20%D0%BD%D0%B5%0A%D1%8F%D0%B2%D0%BB%D1%8F%D1%8E%D1%82%D1%81%D1%8F.)по этой теме)))

2023-05-21 19:50 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +          # в конце строки поставить ";"
Но точка с запятой здесь точно не нужна) Просто в коде Python всё завязано на отступы. Если где-то выше по коду отступы кривые, то интерпретатор (а с ним и PC) полностью теряет нить написанного и предлагает, так сказать, чисто симптоматическое лечение.

2023-05-22 16:41 UTC, LesyaLunina reviewed
Внесены исправления

2023-05-22 16:41 UTC, LesyaLunina reviewed
Внесены исправления

2023-05-22 18:42 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +          #Здесь отступ 2 пробела - правильно по PEP 8 отступ- 4 пробела
Да. На всякий случай уточню. Вот так должно быть:
```python
    def rename(self, dirname, output):
        mp3s = []
        for root, directories, files in os.walk(dirname):
```

2023-05-22 18:44 UTC, IlyaOrlov commented on Practice/Lunina/Practice 2/Task 2.3.py
> +            # В конце двойная скобка.
Важно не название имён, а количество аргументов, разделённых запятой. Обязательных аргументов - два (`path + '/' + mp3` и `path + '/' + hashname`), лишние скобки между ними не нужны:
```python
os.rename(path + '/' + mp3, path + '/' + hashname)
```

2023-05-22 18:47 UTC, IlyaOrlov requested changes
Ещё бы комментарий про скобку и отступ внутри rename всё же указать (только с учётом замечаний), и будет всё ОК.

2023-05-23 07:25 UTC, LesyaLunina reviewed
Исправления внесены с строку 16 и 25

2023-05-23 07:31 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-05-23 07:31 UTC, merged