Задачи 4, 5 к лекции №3
IlyaOrlov/PythonCourse2.0_May23 pull request #52
Opened 2023-05-20 17:54 UTC by DmitriySapegov

2023-05-20 18:28 UTC, IlyaOrlov requested changes
Хорошо, но есть одно замечание.

2023-05-20 18:28 UTC, IlyaOrlov commented on Practice/Sapegov/Sap3.5.py
> +print(x[:] == x[::-1])
Вместо **x[:]** можно написать просто **x**
Иначе возникает вопрос, что хотел сказать автор, усложнив код)

2023-05-21 12:16 UTC, DmitriySapegov commented on Practice/Sapegov/Sap3.5.py
> +print(x[:] == x[::-1])
Оу, и правда работает)
Буду знать, поправил, спасибо!

2023-05-21 12:33 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-05-21 12:33 UTC, merged