ДЗ 3.2
IlyaOrlov/PythonCourse2.0_May23 pull request #57
Opened 2023-05-21 17:49 UTC by Dimaly123

2023-05-21 18:43 UTC, IlyaOrlov requested changes
Супер! Оставил одно небольшое пожелание.

2023-05-21 18:43 UTC, IlyaOrlov commented on Practice/Lyagin/dim3.3.1.py
> +
Пустые строки в конце файла лучше убрать. Это не замечание, а скорее, пожелание, чтоб код смотрелся красивей. При этом одну пустую строку оставлять нужно, чтоб Гитхаб не рисовал значки "кирпичей") Это старое требование не относится к PEP8 напрямую и обусловлено ограничениями некоторых текстовых редакторов (преимущественно, в Unix системах), которые могут проигнорировать последнюю строку в файле (т.к. эта строка единственная не заканчивается символом переноса строки).

2023-05-21 18:47 UTC, Dimaly123 commented on Practice/Lyagin/dim3.3.1.py
> +
Принято! Я так то кое где удаляю лишние пустые строки, но в основном забываю про это.

2023-05-21 20:39 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет. Можно отправлять в main)

2023-05-22 06:24 UTC, IlyaOrlov commented
Если просто закрыть пулл реквест, это помножит на ноль все сделанные изменения.
Тут есть кнопка Merge pull request. Она становится доступной, когда изменения получили одобрение.
Вот её надо нажимать, чтоб изменения в main отправить.
Обычно я её нажимаю, но можете и Вы нажать)

2023-05-22 06:28 UTC, merged