домашнее задание №4
IlyaOrlov/PythonCourse2.0_May23 pull request #67
Opened 2023-05-23 19:24 UTC by AlenaStupina

2023-05-23 20:09 UTC, IlyaOrlov requested changes
Супер! Но есть небольшое замечание.

2023-05-23 20:09 UTC, IlyaOrlov commented on Practice/Stupina/homework_4/task_1.py
> +    if (i % 15) == 0:
Всё хорошо, только скобки здесь (и в стр.3, 5, 7) не нужны. Приоритет операций и так однозначен (логические операторы всегда выполняются последними), а лишние символы засоряют код.

2023-05-24 19:29 UTC, AlenaStupina commented on Practice/Stupina/homework_4/task_1.py
> +    if (i % 15) == 0:
Не знала про приоритет, исправлю

2023-05-25 11:32 UTC, AlenaStupina commented
исправила о добавила новые

2023-05-25 11:37 UTC, IlyaOrlov approved these changes
Всё отлично! Замечаний нет.

2023-05-25 11:37 UTC, merged

2023-05-25 11:40 UTC, AlenaStupina commented
По всем пяти задачам нет замечаний? просто мало ли, вдруг не заметили, что я добавила на проверку остальные 4 задачи...