Ножницы прикольная игра, можно как-то легче написать 100 %
IlyaOrlov/PythonCourse2.0_May23 pull request #69
Opened 2023-05-23 20:42 UTC by Fed909

А ещё с декораторами ещё разбираться и разбираться

2023-05-23 21:48 UTC, IlyaOrlov requested changes
Прекрасно! Но есть некоторые замечания.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.1.py
ОК. Только нужно вывести не случайное число из указанного диапазона, а **все** числа, заменяя некоторые на Fizz, Buzz, FizzBuzz.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.2.py
> +    print(f"{index + 1} цифра равна {x[index]}")
Раз у нас есть **i**, то **x[index]** нам уже не нужен. Тем более **i** сразу указывает на очередной элемент строки, а **x[index]** - это целая операция по получению элемента строки с номером index.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.2.py
> +for index, i in enumerate(x):
Начать считать index с 1 при помощи enumerate можно проще: 
```python
for index, i in enumerate(x, 1):
```

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.3.py
> +        x = input("Ошибка! Введите цифры: ")
Не очень удобно для пользователя. Если он попадёт в этот цикл, то не сможет выйти из программы по слову stop, пока перед этим не введёт цифру. 
Можно просто вложенный цикл заменить на if, а вместо input здесь использовать print.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.4.py
> +while not (input(f"{lst[x]} \n :")).lower() == "хватит":
ОК. Только не совсем логично... я ещё ничего не написал, а он мне уже выдаёт: "Ты хоть понял что написал?"

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.5.py
> +        None
Обычно для задания пустого тела цикла (и не только цикла) используют ключевое слово **pass**

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.5.py
> +    elif int(numGuess) < numTrue:
Чтоб дважды не повторять одну и ту же операцию int(numGuess) можно перед стр.20 запомнить результат в отдельной переменной: i_num_guess = int(numGuess)

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.5.py
> +numStart = numprov("text", "минимальное")
Не стоит забывать про именование переменных в snake_case по [PEP8](https://peps.python.org/pep-0008/#function-and-variable-names:~:text=Function%20names%20should,as%20function%20names.).

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.6.py
> +def poiskMax(num1, num2):
Не стоит забывать про именование функций в snake_case по [PEP8](https://peps.python.org/pep-0008/#function-and-variable-names:~:text=Function%20names%20should,as%20function%20names.).

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.6.py
> +    print(val)
Нет. Эта функция должна делать то же самое, что и poiskMax, только не возвращать результат через return, а сразу выводить этот результат на экран через print.
Задача на понимание возврата значения из функции.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.6.py
> +    x = max(num1, num2)
Вызов функции - это всегда хоть небольшие, но накладные расходы. В данном случае, для двух переменных всё можно решить при помощи сравнения и if...else.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.7.py
> +def decorate(func):
Хорошая попытка, но есть нюанс. Если функция принимает аргументы и/или возвращает значение, к ней такой декоратор применить не получится.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.8.py
> +tableWin =[["ножницы", "бумага","Ты"], ["ножницы", "камень","Я"], ["камень", "бумага","Я"], ["камень", "ножницы","Ты"],
Ох... Понимаю, что строка убирается в ограничение в 120 символов, но для повышения читабельности, можно и ещё какие-то части на отдельные строки вынести. 
И да, после вторых запятых везде не хватает пробелов.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.8.py
> +            if player1 == tableWin[i][0] and player2 == tableWin[i][1]:
Многовато пробелов.

2023-05-23 21:48 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.8.py
> +                print(f"Ура! {tableWin[i][2]} победил!")
Стоит добавить break после этого print, иначе даже после выявления победителя этот цикл for продолжить проверять таблицу победителей.

2023-05-29 12:56 UTC, Fed909 commented on Practice/Fedorov/HW_4/4.2.py
> +    print(f"{index + 1} цифра равна {x[index]}")
тут на самом деле не понял, каким образом из i я могу вытщаить индекс, поэтому и ввел данную конструкцию, если подскажите, как или где почитать, переделаю

2023-05-29 13:16 UTC, Fed909 commented on Practice/Fedorov/HW_4/4.6.py
> +    x = max(num1, num2)
Я тут не совсем понимаю тогда терминологию, для меня функции - это функции def.
Если бы не было так написано, я бы сделал через if...else, может

2023-05-29 13:18 UTC, Fed909 commented on Practice/Fedorov/HW_4/4.7.py
> +def decorate(func):
Мне что-то нужно поправить? Мб почитать ещё что-то про декораторы или может накиньте мне ещё ДЗ для освоения и понимания декораторов.

2023-05-29 19:21 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.1.py
> +    for i in krat:
Ещё один нюанс. Если число кратно 15, то должно выводиться только **FizzBuzz**,  а не **Fizz; Buzz; FizzBuzz;** .

2023-05-29 19:21 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.2.py
> +    print(f"{index + 1} цифра равна {x[index]}")
Смысл моего комментария не в том, как вытащить index из i, а в том что x[index] - лишняя операция. Можно же так:
```python
for index, i in enumerate(x):
    print(f"{index + 1} цифра равна {i}")
```
i - это и есть x[index].
Можно ещё заставить enumerate начинать считать с 1:
```python
for index, i in enumerate(x, 1):
    print(f"{index} цифра равна {i}")
```
Но можно, конечно, и без enumerate, и без индекса, как такового, обойтись:
```python
index = 1
for i in x:
    print(f"{index} цифра равна {i}")
    index += 1
```

2023-05-29 19:25 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.3.py
> +        x = ""
Вместо этой строки можно просто написать else. Если x - пустая строка, то незачем его добавлять к num.

2023-05-29 19:25 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.6.py
> +    x = max(num1, num2)
max - это тоже функция, только встроенная. Где-то и для неё есть свой def:)

2023-05-29 19:27 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.7.py
> +def decorate(func):
Нужно применить *args, **kwargs и возврат значения res, как было рассмотрено сегодня на лекции.

2023-05-29 19:32 UTC, IlyaOrlov requested changes
Стало лучше. Но добавились ещё замечания.

2023-05-29 19:32 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.8.py
> +    if player2 == player1.lower().replace(" ", ""):
Если player1 будет включать пробелы, он и так не пройдёт проверку в стр.14
А чтоб лишний раз не вызывать для него метод lower(), стоит немного переместить вправо одну скобку в стр.13;)

2023-05-29 20:14 UTC, Fed909 commented on Practice/Fedorov/HW_4/4.1.py
> +    for i in krat:
Я специально оставил так.
Число 15 и другие числа кратны 3, 5 и 15 одновременно, поэтому я считаю решение верным :) 
Но если нужно - поправлю, мб я что-то недопонял

2023-05-29 20:18 UTC, Fed909 commented on Practice/Fedorov/HW_4/4.2.py
> +    print(f"{index + 1} цифра равна {x[index]}")
Мега лайк, полностью согласен, не хотел вводить счетчик. просто подумал, мб нельзя enumerate использовать.

2023-05-29 20:21 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.1.py
> +    for i in krat:
Ну если это сделано осознанно, а не от безысходности, то можно оставить и так:)

2023-05-29 20:37 UTC, Fed909 commented on Practice/Fedorov/HW_4/4.8.py
> +    if player2 == player1.lower().replace(" ", ""):
done

2023-05-30 20:05 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.6.py
> +    print(val)
Непохоже, чтоб эта функция делала то же самое, что и poisk_max.
Она должна делать буквально следующее:
```python
    if num1 > num2:
        print(num1)
    else:
        print(num2)
```

2023-05-30 20:10 UTC, IlyaOrlov requested changes
Хорошо. Но некоторые замечания ещё остались.

2023-05-30 20:10 UTC, IlyaOrlov commented on Practice/Fedorov/HW_4/4.7.py
> +    return inner()
Нет, скобки здесь не нужны. Попробуйте обернуть в этот декоратор функции из примера с лекции (Useful\for_lec6\decorator_example.py), чтоб проверить его работоспособность.
Также этот декоратор не подойдёт для функций, возвращающих результат.

2023-05-30 21:17 UTC, Fed909 commented on Practice/Fedorov/HW_4/4.5.py
> +numStart = numprov("text", "минимальное")
это уже проф деформация, VBA, C#, java, python
Везде своя история, но я постараюсь использовать snake_case

2023-05-30 21:31 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2023-05-30 21:31 UTC, merged