Практика по 4-ой лекции
IlyaOrlov/PythonCourse2.0_May23 pull request #70
Opened 2023-05-23 22:49 UTC by LoginovaMaria

2023-05-24 03:58 UTC, Tetrackon requested changes
Всё хорошо!)) Есть только одно замечание по поводу преобразования типа данных. Остальное просто советы :)

2023-05-24 03:58 UTC, Tetrackon commented on Practice/MLoginova/Loginova_4.1.py
> +    if i % 3 == 0 and i % 5 == 0:
Очень хорошо! Единственное что не обязательно было устраивать две проверки на кратность 3 и 5, можно было сразу проверить на кратность 15. В рамках домашнего задания это не критично, но на будущее - если можно сократить количество действий, особенно в цикле, если это не повредит читаемости кода, то обязательно сокращайте!)

2023-05-24 03:58 UTC, Tetrackon commented on Practice/MLoginova/Loginova_4.2.py
> +    new_x = str(x)
x и так строка, так как функция input() возвращает только строки, дополнительное преобразование, с добавлением переменной, не нужно.

В такие моменты, когда я не уверен какой тип данных будет у переменной, я всегда пользуюсь функцией type()
Например:
print(type(x))
Таким образом, при тестовом запуске программы, мне выведется на экран тип данных переменной.

Тип данных переменной можно также посмотреть в дебаг-режиме Pycharm

2023-05-24 03:58 UTC, Tetrackon commented on Practice/MLoginova/Loginova_4.2.py
> +        print(str(i+1) + " цифра равна {}".format(new_x[i]))
форматные строки можно записывать и так:
f" цифра равна {new_x[i]}")
В каком-то смысле это более удобно и читабельно.
В Вашем написании ошибки нет, просто указываю на возможности Python :)

2023-05-24 07:02 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.2.py
> +        print(str(i+1) + " цифра равна {}".format(new_x[i]))
Илья, показывал и рассказывал на лекции разные варианты...пробую в заданиях эти разные варианты, чтобы и руку набить и понять каким удобнее пользоваться)

2023-05-24 13:47 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.2.py
> +        print(str(i+1) + " цифра равна {}".format(new_x[i]))
Ого, не догадалась, что так можно...поэтому и разные варианты форматирования применила) Спасибо, что об этом написали!

2023-05-24 14:17 UTC, IlyaOrlov requested changes
Всё супер! Остались комментарии по мелочи.

2023-05-24 14:17 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.3.py
> +    elif x.lower() == "stop":
Это уже лишняя проверка. Если пользователь ввёл "stop", мы и так выйдем из цикла по условию в стр.6

2023-05-24 14:17 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.3.py
> +        a = a + x
Немножко оптимизации... то же самое, но покороче: a += x

2023-05-24 14:32 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.3.py
> +        a = a + x
Не привычна пока эта запись в таком виде  и  нагляднее использованный вариант(

2023-05-24 14:34 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.3.py
> +    elif x.lower() == "stop":
Соглашусь и поправлю этот момент.

2023-05-24 14:58 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.3.py
> +        a = a + x
Стоит привыкнуть, т.к. этот вариант широко распространён (и не только в Python) в виду своей лаконичности.

2023-05-24 14:59 UTC, IlyaOrlov reviewed
Пока замечаний нет)

2023-05-28 16:22 UTC, IlyaOrlov requested changes
Замечание по заданию 4.4

2023-05-28 16:22 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.4.py
> +while request.lower() != "хватит" and i <= len(answers)-1:
Двойная проверка request.lower() в стр.7 и здесь избыточна! Стоит оптимизировать алгоритм. Тем более задание предусматривает остановку спора, только когда пользователь ввёл слово "хватит". Если слова из списка закончились, видимо, стоит начать идти по списку заново.

2023-05-29 09:42 UTC, IlyaOrlov requested changes
Есть существенные замечания.

2023-05-29 09:42 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.4.py
> +    if i <= len(answers)-2:
То ж самое, но чуть короче: `if i < len(answers) - 1`

2023-05-29 09:42 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.6_1.py
> +def myfun1(x, y):
Вопрос на понимание: что делает return в этой функции?

2023-05-29 09:42 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova 4.5.py
> +while not b.isdecimal():
Код для получения b (cтр.9-11) практически такой же, как и для получения a. Можно оптимизировать и вынести код в функцию.

2023-05-29 09:42 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova 4.5.py
> +    if int(poisk) != n:
Зачем эта проверка здесь, если она уже есть в стр.15?

2023-05-29 09:42 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova 4.5.py
> +        if int(poisk) > n:
Многовато вызовов int для одного и того же poisk. Лишняя работа.

2023-05-29 11:17 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.4.py
> +    if i <= len(answers)-2:
Почему то даже не подумала о таком варианте...Ваш вариант более оптимизированный, поправлю. Спасибо!

2023-05-29 11:19 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.4.py
> +    if i <= len(answers)-2:
Мне не нравится один момент коду: если пользователь вводит фразу "хватит", то сначала даётся ответ из списка, а только потом приложение останавливается, но я не могу input с вводом запроса(стр.5) расположить выше цикла while(стр.4), так как запрос ввода должен быть внутри цикла.
Подскажите, пожалуйста, как быть)

2023-05-29 11:24 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.6_1.py
> +def myfun1(x, y):
Оператор return возвращает большую цифру из двух

2023-05-29 12:51 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.4.py
> +    if i <= len(answers)-2:
Можно объединить ввод значения и проверку в одном выражении, используя "моржовый" оператор:
```python
while (request := input("Введите Ваш запрос: ")).lower() != "хватит":
    ...    
```

2023-05-29 12:56 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova_4.6_1.py
> +def myfun1(x, y):
Хорошо. А можно было бы обойтись без return в этом варианте функции?

2023-05-29 14:08 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.6_1.py
> +def myfun1(x, y):
Да, можно, в этом случае было бы достаточно print, поскольку результат возвращать не просили.
Поправлю

2023-05-29 14:09 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.4.py
> +    if i <= len(answers)-2:
Интересная конструкция, попробую. Спасибо!

2023-05-29 14:21 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova_4.4.py
> +    if i <= len(answers)-2:
Оказалось очень удобен этот "моржовый" оператор и присвоил и вернул значение. Теперь отрабатывает более правильно код на мой взгляд.

2023-05-29 19:49 UTC, IlyaOrlov requested changes
Новых замечаний нет. Но осталось кое-что из старых.

2023-06-03 06:38 UTC, IlyaOrlov requested changes
Хорошо. Но ещё есть, что улучшить.

2023-06-03 06:38 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova 4.5.py
> +while poisk := enter_chislo():
Если пользователь введёт 0, то игра закончится( А ведь ноль вполне может быть загаданным!

2023-06-03 06:38 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova 4.5.py
> +    elif poisk == n:
Достаточно else. Если poisk - не больше и не меньше n, то числа, по-любому, равны.

2023-06-03 06:38 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova 4.5.py
> +x = enter_chislo()
Одинаковый код в стр.10,11 и 15,16. Можно оптимизировать:
```python
while True:
    x = enter_chislo()
    y = enter_chislo()
    if x == y:
        print("Нижняя и верхняя граница диапазона совпадают. Повторите ввод: ")
    else:
        break
```
Ну или ещё проще:
```python
while (x := enter_chislo()) == (y := enter_chislo()):
    print("Нижняя и верхняя граница диапазона совпадают. Повторите ввод: ")
```

2023-06-03 13:27 UTC, LoginovaMaria commented on Practice/MLoginova/Loginova 4.5.py
> +x = enter_chislo()
Обратила на это внимание, но как соединить, чтобы несколько раз не запрашивать диапазон  не догадалась..

2023-06-03 14:24 UTC, IlyaOrlov requested changes
OK. Но ещё есть, что улучшить.

2023-06-03 14:24 UTC, IlyaOrlov commented on Practice/MLoginova/Loginova 4.5.py
> +if x < y:
Код в стр.13-18 тоже можно упростить. Ведь если y < x достаточно поменять их местами. Остальные операции менять не нужно.
```python
if y < x:
    x, y = y, x
n = random.randint(x, y)
print(f"Загадано число в диапазоне от {x} до {y}, попробуй отгадать какое:")
```
Ну и в одном файле стоит придерживаться какого-то одного способа форматирования строк. Либо f"" (рекомендуется), либо "".format()

2023-06-03 15:24 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-06-04 08:31 UTC, IlyaOrlov requested changes
Всё супер! Но есть одно предложение по оптимизации!

2023-06-04 08:31 UTC, IlyaOrlov commented on Practice/MLoginova/Lofinova_4.8.py
> +lst = [0, 1, 2]
Раз, у нас lst меняться не будет... стоит сделать его кортежем. Можно было бы и множеством (идеально для операции in в стр.8), но тогда не будет работать random.choice в стр.11, т.к. он умеет работать только с последовательностями.

2023-06-04 16:24 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-06-07 04:48 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.
Наверное, уже можно нажимать Ready for review;)

2023-06-07 14:22 UTC, LoginovaMaria commented
"Ready for review" нажала, если замечаний по 4 практике  - просьба её переместить в main.

2023-06-07 15:32 UTC, IlyaOrlov approved these changes
Отлично!

2023-06-07 15:34 UTC, merged