K lazarev
IlyaOrlov/PythonCourse2.0_May23 pull request #73
Opened 2023-05-24 20:44 UTC by KirillLazarev

ДЗ к 3 лекции

2023-05-25 06:38 UTC, Tetrackon reviewed
В целом всё хорошо, есть только пара рекомендаций.

2023-05-25 06:38 UTC, Tetrackon commented on Practice/Lazarev/HW3.1.Расчёт_периметра.py
> +    print('Периметр прямоугольника =', perimeter ,'см')
Так конечно можно выводить результат на экран, но гораздо удобнее использовать форматную строку

2023-05-25 06:38 UTC, Tetrackon commented on Practice/Lazarev/HW3.3.1.Шифратор.py
> +result = int(secret_code) ^ int(password)
Секретный код лучше сразу хранить в целочисленном формате, а не в виде строки. Как Вы сделали это в программе дешифраторе. (можно не исправлять)

2023-05-25 08:56 UTC, IlyaOrlov requested changes
Хорошо. Но есть некоторые замечания!

2023-05-25 08:56 UTC, IlyaOrlov commented on Practice/Lazarev/HW3.1.Расчёт_периметра.py
> +elif length == width:
Это уже лишняя проверка. Если length != width - Ложь, то length == width - по-любому, Истина. Третьего не дано) Поэтому здесь достаточно else.

2023-05-25 08:56 UTC, IlyaOrlov commented on Practice/Lazarev/HW3.5.py
> +word = input("Введите слово: ")
А если слово начинается с большой буквы? Например, "Топот". Это же тоже палиндром.

2023-05-25 08:56 UTC, IlyaOrlov commented on Practice/Lazarev/HW3.5.py
> +if word == word[::-1]:
Проще сразу вызывать print(word == word[::-1]) - напечатается либо True, либо False.

2023-05-29 13:21 UTC, IlyaOrlov requested changes
ОК. Но есть существенные замечания.

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.1.py
> +# Я пытался вывести результат в строку, но не получилось
По заданию этого не требовалось. Но если очень хочется, то можно выводить так: print('Fizz',  end = ' ')

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.1.py
> +        m.append(i)
Зачем складывать i в m, если мы потом с m ничего не делаем?

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.1.py
> +    if i % 3 == 0:
Всё-таки стоит начать с проверки на кратность 15, иначе FizzBuzz не выведется никогда!

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.1.py
> +n = list(range(101))
Этим выражением мы фактически перебираем всё, что возвращает range и складываем это в список. В стр. 5 мы повторно проходим по тем же элементам, но уже в списке. Незачем делать лишнюю работу. Просто в цикле for надо обращаться сразу к range.

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.2.py
> +        continue
continue здесь и в стр.8 лишний

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.2.py
> +        for i in s:
Учитывая, что этот код лежит в цикле while, пользователь может ввести несколько пятизначных чисел. Вот только для всех этих чисел начиная со второго будет выводится некорректная **a**.

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.3.py
> +        continue
continue здесь не нужен

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.3.py
> +        r = r * 10 + int(s)
Нет. **r** по типу вполне может оставаться строкой. С ним же никаких вычислений не должно производиться. Тогда здесь достаточно будет написать **r += s**

2023-05-29 13:21 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.3.py
> +    if s == 'stop':
Строки 3-7 можно объединить в одно выражение, используя "моржовый" оператор.

2023-06-11 17:38 UTC, IlyaOrlov requested changes
Стало лучше. Но некоторые замечания остались.

2023-06-11 17:38 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.1.py
> +for i in list(range(101)):
list здесь лишний.
Представьте, что Вас попросили досчитать до 100...
for i in list(range(101)) - означает, что мы расположим все числа 0 до 100 в памяти, а потом будем по ним идти. Т.е. Вы сначала напишете все эти числа на бумажке, а потом будете читать по бумажке.
for i in range(101) - мы сразу будем идти по числам 0 до 100, которые нам будет возвращать range. Т.е. Вы сразу будете просто сразу называть числа от 0 до 100.
И да, чтоб начинать счёт не с 0, а с 1 (как указано в задании), надо писать for i in range(1, 101).

2023-06-11 17:38 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.2.py
> +while (s := input('Введите пятитизначное число: ')):
Внешние круглые скобки здесь необязательны.

2023-06-11 17:38 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.3.py
> +while True(s := input('Вводите цифры: ')
Этот код работать не будет!

2023-06-11 17:38 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.3.py
> +        r = r * 10 + int(s)
Если **r** изначально сделать строкой: `r = ''`, то добавлять к нему цифры будет гораздо проще: `r += s`

2023-06-12 15:23 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.3.py
> +    if not s.isdecimal: #почему не работает со строкой - не понимаю
Скобок не хватает. Должно быть `if not s.isdecimal():`
Без скобок функция не вызывается.

2023-06-12 15:27 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +    # не нашел как сделать break при нечисловом символе
Чтоб сделать break при нечисловом символе, надо убрать преобразование к int из условия цикла в тело этого цикла.

2023-06-12 15:27 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +    # как сделать print('Пока') при вводе -1 ?
```python
while ...:
   ...
else:
    print("Пока")
```

2023-06-13 08:33 UTC, IlyaOrlov requested changes
Хорошо. Но вопросы ещё остались!

2023-06-13 08:33 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.1.py
> +print(i)
Почему этот print из цикла вынесли? Было всё хорошо: числа, не кратные 5, 3, 15 тоже должны были выводиться на экран (только без замен).

2023-06-13 08:33 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.3.py
> +    if not s.isdecimal(): #без скобок не работает
Чтоб лифт поехал, недостаточно наличия лифта. Надо нажать кнопку.
Чтоб сварился кофе, недостаточно купить кофеварку. Надо передать в нее фактические аргументы (кофе и вода) и поставить на огонь (вызвать).
Что функция isdecimal проверила, что **s** состоит только из цифр недостаточно написать имя этой функции. Нужно её вызвать, указав скобки после имени. И так с ЛЮБОЙ функцией.

2023-06-13 08:33 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +while (a := input('Введите целое число : ')) != 'stop':
Это шаг в правильном направлении!
Теперь в стр.7 можно написать:
```python
if not a.isdecimal():
    print("Вы ввели НЕ число")
    break
```

2023-06-13 08:33 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +    elif int(a) < number:
Чтоб дважды для одной и той же **a** не вызывать int(), можно перед стр.7 написать `a = int(a)` и дальше просто работать с **a**.

2023-06-13 08:33 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +print('Пока')
Вопрос на понимание. В чём разница между таким вызовом `print('Пока')`, как сейчас в коде, и следующим:
```python
else:
    print('Пока')
```
?

2023-06-13 13:15 UTC, IlyaOrlov requested changes
Лучше. Но вопросы ещё остаются.

2023-06-13 13:15 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +        #а вдруг юзер случайно, нужно дать щанс исправиться)
Тогда не ставьте break)

2023-06-13 13:15 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +##    a = int(a)
А вот этот код надо всё-таки после проверки a.isdecimal() делать но до сравнений, начинающихся со стр. 12.

2023-06-15 07:33 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.6.1_Большее_число_из_введёных.py
> +def first_func():
Эта функция должна делать то же, что и функция в HW4.6.2_Больщее_по_месту_вызова.py, только вместо print у нее должен быть return.
Стандартную функцию max здесь использовать не нужно.
Смысл задания в том, чтоб слушатель понял разницу между print (вывод значения на экран) и return (возврат значения из функции).

2023-06-15 14:44 UTC, IlyaOrlov requested changes
ОК. Но замечания ещё есть.

2023-06-15 14:44 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.6.1_Большее_число_из_введёных.py
> +def first_func():
Нет. Имелось в виду сделать так:
```python
    if a > b:
        return a
    else:
        return b
```

2023-06-15 14:44 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.6.1_Большее_число_из_введёных.py
> +    a = int(input('Введите первое число: '))
Ввод **a** и **b** лучше вынести из функции и передавать сюда эти переменные в качестве аргументов (как в 4.6.2). Тогда функция сможет работать как с вводимыми пользователем, так и жестко прописанными в коде данными.

2023-06-15 14:44 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.6.2_Большее_по_месту_вызова.py
> +        if a > b:
Многовато пробелов слева. Должно быть 4.

2023-06-15 14:44 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.6.2_Большее_по_месту_вызова.py
> +print(fist_func(10, 20))
Вопрос на понимание: этот print здесь что делает?

2023-06-15 14:44 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7_Камень_ножницы_бумага.py
> +    user = (input('')).lower()
Вокруг input() скобки не нужны.

2023-06-15 14:44 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7_Камень_ножницы_бумага.py
> +    z = ['камень', 'ножницы', 'бумага']
Т.к. **z** не меняется, лучше использовать не список, а кортеж, и вынести это определение из цикла. Иначе **z** будет переопределяться на каждом круге цикла.

2023-06-16 07:28 UTC, IlyaOrlov requested changes
Хорошо. Остались замечания по HW4.5_Угадай число.py и одно небольшое по HW4.6.2_Большее_по_месту_вызова.py

2023-06-16 07:28 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.6.2_Большее_по_месту_вызова.py
> +(fist_func(10, 20))
Внешние скобки тоже не нужны.

2023-06-16 17:53 UTC, IlyaOrlov requested changes
Есть новые существенные замечания. 
В названиях файлов импортозамещение лучше не применять) Лучше файлы именовать на английском и не использовать специальные символы.
Для учебных файлов - ОК, но для реальных рабочих так лучше не делать, т.к. могут быть проблемы как с запуском на некоторых англоязычных операционных системах, так и с импортами в другие файлы.

2023-06-16 17:53 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5Угадай_число.py
> +a = int()
Какой смысл этого присваивания?

2023-06-16 17:53 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5Угадай_число.py
> +    elif int(a) == number:
Вот перед этой строкой стоило бы написать `a = int(a)`, чтоб получился такой код:
```python
    if not a.isdecimal():
        print("Вы ввели НЕ число")
        continue
     a = int(a)
    if a == number:
        ...
    elif a < number:
        ...
``` 
Иначе получится, что функция int() вызывается дважды для одной и той же **a**. А лишняя работа нам ни к чему.

2023-06-16 17:53 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7=====декоратор===== .py
> +        return '===========' + func(x) + '==========='
А если функция, на которую вешается декоратор. будет такой:
```python
def anyfunc(y):
    return y ** 2
```
И мы будем её использовать в выражении:
```python
z = anyfunc(10) * 2
```
Повесим на неё этот декоратор, и всё сломается.

2023-06-16 17:53 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +print('Пока')
Вопрос остался без ответа.

2023-06-19 18:33 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.5_Угадай число.py
> +print('Пока')
ОК. Просто `print('Пока')` будет выводить на экран 'Пока' при любом выходе из цикла.
В случае же else:
```
else:
    print('Пока')
```
'Пока' не будет выводиться, если выход из цикла произошел через break.

2023-06-19 19:16 UTC, IlyaOrlov requested changes
Хорошо. Замечания остались только по декоратору.

2023-06-19 19:16 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7 Decorator.py
Код не работает!
Надо исправить декоратор!

2023-06-21 12:17 UTC, IlyaOrlov requested changes
Ещё пара небольших замечаний!
Решение корректное, но можно было проще, т.к. задание не требовало выводить "===========" до и после **вывода** результата. Речь шла о **до и после запуска функции**. Т.е. кода
```
print("======")
r = f(*args, **kwargs)
print("======")
return r
```
было бы достаточно.

2023-06-21 12:17 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7 Decorator.py
> +        def add_message(x):
Здесь надо предусмотреть возможность приёма и передачи в f любых возможных аргументов (намёк на *args и **kwargs).

2023-06-21 12:17 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7 Decorator.py
> +z = anyfunc(10) * 2
Это относится к основному коду. Основной код должен находиться ниже определения функции (стр.18-20).

2023-06-25 17:54 UTC, IlyaOrlov requested changes
Код, в целом, почти корректный, но не уверен в достижении полного понимания его работы.

2023-06-25 17:54 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7 Decorator2.py
> +# Не понимаю почему в коде декоратора рез 100, а не 200, и как это исправить
Потому что в декораторе печатается результат anyfunc, т.е. 10 ** 2 (100). А умножение 100 * 2 происходит вне декоратора. Попробуйте пройтись по коду отладчиком (начиная со строки 18), чтоб увидеть последовательность шагов.
Непонятно только, почему это нужно исправлять.

2023-06-25 17:54 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7 Decorator2.py
> +res = anyfunc(10) * 2
Стр.18-19 - это основной код, стр. 22-24 - определение функции. Стоит размещать определения функций выше основного кода.

2023-06-25 17:54 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7 Decorator1.py
> +z = anyfunc(10) * 2
Эта строка относится к основному коду. Основной код должен располагаться ниже определения функций. Если непонятно, что имеется в виду, напишите мне - разберемся с этим вопросом.

2023-06-26 15:01 UTC, IlyaOrlov reviewed
Замечаний по коду нет. Всё корректно.
Но не могу не задать вопрос про комментарий относительно "неверного ответа".

2023-06-26 15:01 UTC, IlyaOrlov commented on Practice/Lazarev/HW4.7 Decorator1.py
> +# Здесь кстати тоже не верный ответ
Почему?

2023-06-27 06:29 UTC, KirillLazarev commented
Потому что в моём понимании dec должен обернуть итоговый ответ (=== 200
===) иначе я не понимаю смысл конкретно этого дека.
На решение этого вопроса я потратил много времени, даже научился более
менее дебажить.
В итоге я пришёл к умозаключению, что ответ  === 200 === невозможен при
текущей функции на которую вешается dec.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Никаких
вирусов.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 26 июн. 2023 г. в 18:01, IlyaOrlov ***@***.***>:

> ***@***.**** commented on this pull request.
>
> Замечаний по коду нет. Всё корректно.
> Но не могу не задать вопрос про комментарий относительно "неверного
> ответа".
> ------------------------------
>
> In Practice/Lazarev/HW4.7 Decorator1.py
> <https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/73#discussion_r1242339735>
> :
>
> > +
> ***@***.***_dec('====')
> +def anyfunc(y):
> +    return y ** 2
> +
> +
> ***@***.***_dec('====')
> +def anyfunc2(y):
> +    return y
> +
> +
> +z = anyfunc(10) * 2
> +
> +anyfunc2("hello")
> +
> +# Здесь кстати тоже не верный ответ
>
> Почему?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/73#pullrequestreview-1498761500>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7YK7XQGAFICOXVHVHUTZ5DXNGP5VANCNFSM6AAAAAAYN452AQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-27 15:31 UTC, IlyaOrlov commented
> Потому что в моём понимании dec должен обернуть итоговый ответ (=== 200 ===) иначе я не понимаю смысл конкретно этого дека. На решение этого вопроса я потратил много времени, даже научился более менее дебажить. В итоге я пришёл к умозаключению, что ответ === 200 === невозможен при текущей функции на которую вешается dec.

По заданию не требовалось оборачивать именно вывод ответа) Смысл этого - например, в отладке. Если сама функция ничего не напечатала, вывелся только один набор === - это значит, что ошибка где-то в вызове функции. Там, где нет отладчика пайчарм - это единственный выход.
Но то, что Вы обеспечили ещё более сложное решение (что декоратор выводит ещё и результат функции) - это тоже хорошо)

2023-06-27 15:32 UTC, merged

2023-06-27 17:57 UTC, KirillLazarev commented
Что декоратор можно использовать как отладчик не думал даже в моём
представлении было все более сложно))
Спасибо!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Никаких
вирусов.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 27 июн. 2023 г. в 18:32, IlyaOrlov ***@***.***>:

> Потому что в моём понимании dec должен обернуть итоговый ответ (=== 200
> ===) иначе я не понимаю смысл конкретно этого дека. На решение этого
> вопроса я потратил много времени, даже научился более менее дебажить. В
> итоге я пришёл к умозаключению, что ответ === 200 === невозможен при
> текущей функции на которую вешается dec.
>
> По заданию не требовалось оборачивать именно вывод ответа) Смысл этого -
> например, в отладке. Если сама функция ничего не напечатала, вывелся только
> один набор === - это значит, что ошибка где-то в вызове функции. Там, где
> нет отладчика пайчарм - это единственный выход.
> Но то, что Вы обеспечили ещё более сложное решение (что декоратор выводит
> ещё и результат функции) - это тоже хорошо)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/IlyaOrlov/PythonCourse2.0_May23/pull/73#issuecomment-1609759391>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7YK7XQ5IAOGPBB2YOGGKQTXNL4HPANCNFSM6AAAAAAYN452AQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>