HW 3: tasks 4, 5. ver1
IlyaOrlov/PythonCourse2.0_May23 pull request #74
Opened 2023-05-25 12:55 UTC by pavelzagy

2023-05-25 14:22 UTC, IlyaOrlov requested changes
Хорошо. Но есть некоторые замечания.

2023-05-25 14:22 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW3/HW3-4.py
> +    str = input('Введите слово, в котором хотите заменить заглавные буквы "А" на символ "*": ')
str - это имя функции, которая используется для преобразования значения к типу Строка. Использовать такие зарезервированные слова для именования своих переменных не рекомендуется, т.к. теряется доступ к исходным значениям этих слов. Например, теперь в этом коде функцию str() использовать не получится. Обычно PyCharm подсвечивает такие ошибки.

2023-05-25 14:41 UTC, pavelzagy commented
Принял в работу, спасибо за советы оптимизации кода))

2023-05-25 18:13 UTC, IlyaOrlov requested changes
ОК. Но ещё есть некоторые предложения.

2023-05-25 18:13 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW3/HW3-4.py
> +
Хорошо, но как же теперь быть, если пользователь введёт, например, "3"?
Можно данный код обернуть в:
```python
if prg == 1 or prg == 2:
    ...
else:
    print("Некорректный ввод")
```

2023-05-25 18:13 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW3/HW3-5.py
> +print(s1 == s)
Можно сразу, без s1: print(s[::-1] == s)

2023-05-26 22:14 UTC, pavelzagy commented
Исправил. В 4 задании решил сделать проверку через цикл while.

2023-05-27 05:08 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW3/HW3-4.py
> +while prg == 1 or prg == 2:
while здесь не нужен! Мы же ничего повторять не собираемся. Здесь достаточно if. Да и break в стр.13 тогда не понадобится.

2023-05-29 11:44 UTC, pavelzagy commented on Practice/Zagorskiy/HW3/HW3-4.py
> +while prg == 1 or prg == 2:
Внес ваши замечания) Исправил

2023-05-29 12:58 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-05-29 12:58 UTC, merged