Домашнее задание 1 и 2 к четвертой лекции
IlyaOrlov/PythonCourse2.0_May23 pull request #75
Opened 2023-05-25 14:30 UTC by Dkisunkina

2023-05-25 18:09 UTC, IlyaOrlov requested changes
Есть существенные замечания!

2023-05-25 18:09 UTC, IlyaOrlov commented on Practice/Kisunkina/homework4.1.py
> +x = random.randint(1, 100)
ОК. Только нужно вывести ВСЕ числа от 1 до 100, заменяя некоторые на Fizz/Buzz, а не одно случайное.

2023-05-25 18:09 UTC, IlyaOrlov commented on Practice/Kisunkina/homework4.2.py
> +        print('Первая цифра равна', number[0])
Как-то негибко получается... А если заказчик попросит 100-значное число вывести? Имеет смысл здесь какой-нибудь цикл использовать.

2023-05-25 18:22 UTC, Dkisunkina commented on Practice/Kisunkina/homework4.2.py
> +        print('Первая цифра равна', number[0])
да, я даже пыталась так сделать. но я не поняла как в цикл вписать изменение надписи (первая цифра, вторая цифра и прочее)

2023-05-31 13:12 UTC, IlyaOrlov requested changes
ОК. Есть некоторые замечания.

2023-05-31 13:12 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.1.py
> +
Зачем пустая строка?

2023-05-31 13:12 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.1.py
> +        print(f"{x}")
Можно просто: print(x)

2023-05-31 13:12 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.2.py
> +else: print("Введена неверная длина строки, введите пятизначное число")
В одну строку писать else и выражение писать [не стоит](https://peps.python.org/pep-0008/#:~:text=%3D%20delay()-,Definitely%20not%3A,-%23%20Wrong%3A%0Aif).

2023-05-31 13:12 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.3.py
> +        print(text)
Достаточно вывести только итоговое значение text после цикла.

2023-06-01 09:31 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.1.py
> +
Убрала

2023-06-01 10:04 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.1.py
> +        print(f"{x}")
Исправила

2023-06-01 10:09 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.3.py
> +        print(text)
Не поняла, что имеете ввиду? пусть человек вводит числа и только после stop на экран должно вывестись итоговое значение?

2023-06-01 13:21 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.3.py
> +        print(text)
Да. Всё верно

2023-06-01 13:25 UTC, IlyaOrlov requested changes
Хорошо. Но пара нюансов осталась.

2023-06-01 13:25 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.6.py
> +def fun1(num1, num2):
Не стоит забывать отделять определения функций двумя пустыми строками, как того требует PEP8.
Ну и print из 1-й строки стоит спустить ниже определения функций в область основного кода.

2023-06-01 13:25 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.2.py
> +    while i < 5:
Пожалуй, стоит ещё немного оптимизировать код: вместо конкретной длины 5 указать len(number). Тогда если требования заказчика по количеству цифр в числе поменяются - как минимум, эту строку кода менять не придётся.

2023-06-06 13:28 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.2.py
> +    while i < 5:
Если я оставлю просто len(number) тогда код не будет срабатывать на неверную длину строки. Мне нужно будет добавить цикл на проверку длины введённого значения. Это увеличит код и при внесении каких - либо изменений со стороны заказчика всё равно будет строчка, где придётся вносить изменения. Точно ли стоит так делать?

2023-06-07 08:12 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.2.py
> +    while i < 5:
теперь понятно, что от меня требуется)) сейчас поправлю!

2023-06-07 10:53 UTC, IlyaOrlov requested changes
ОК. Оставил ещё несколько замечаний.

2023-06-07 10:53 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.2.py
> +        len(number) != len_str
Лишнее выражение. Оно ни на что не влияет.

2023-06-07 10:53 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.6.py
> +    return x
Если num1 окажется равным num2, здесь будет ошибка!
Также случай равенства стоит предусмотреть и в fun1.

2023-06-07 10:53 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.6.py
> +
Здесь надо ещё одну пустую строку добавить.

2023-06-07 10:53 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.2.py
> +        break
Если мы захотим отказаться от break, чтоб пользователь мог ввести несколько пятизначных чисел, у нас ничего не получится. Чтоб исправить ситуацию, достаточно перенести определение i = 0 непосредственно к циклу while (перед стр.7).
Общий принцип таков: переменные стоит определять как можно ближе к месту их использования, но так, чтоб не было лишних переопределений (т.е. len_str = 5, например, в цикл `while True` заносить не нужно).

2023-06-07 11:44 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.2.py
> +        len(number) != len_str
Согласна - убрала

2023-06-07 11:46 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.2.py
> +        break
Перенесла

2023-06-07 20:49 UTC, IlyaOrlov commented on Practice/Kisunkina/lec 4/homework4.6.py
> +fun2(num1, num2)
Вопрос на понимание: как узнать/проверить результат работы функции fun2?

2023-06-08 07:37 UTC, Dkisunkina commented on Practice/Kisunkina/lec 4/homework4.6.py
> +fun2(num1, num2)
Можно двумя способами: 
1) в данных строках нужно присвоить например переменной number = fun2(num1, num2)
print(f"Результат функции2 {number}")
2) в самой функции fun2 перед retern x на одном уровне отступа добавить print(f"Результат функции2 {x}")

2023-06-08 07:54 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-06-08 07:54 UTC, merged