Задача 8 к лекции №4
IlyaOrlov/PythonCourse2.0_May23 pull request #76
Opened 2023-05-25 19:41 UTC by DmitriySapegov

Думаю не самое изящное решение, но работает.
Единственное не получилось после
print('Вы ошиблись в вводе! Попробуйте снова!')
выводить не на самое начало, а на ввод you.
Но похоже нужно структуру цикла просто менять, и input('Хотите сыграть? Введите: Да или Нет ') ставить на строчку ниже.

2023-05-25 20:42 UTC, IlyaOrlov commented
> Думаю не самое изящное решение, но работает. Единственное не получилось после print('Вы ошиблись в вводе! Попробуйте снова!') выводить не на самое начало, а на ввод you. Но похоже нужно структуру цикла просто менять, и input('Хотите сыграть? Введите: Да или Нет ') ставить на строчку ниже.

Если выводить не на самое начало, у пользователя не будет возможности завершить игру. Как вариант - объединить два input, т.е. сразу дать пользователю выбрать камень, ножницы, бумагу или, например, stop.

2023-05-25 20:55 UTC, IlyaOrlov requested changes
Всё супер! Оставил одно предложение по оптимизации.
На самом деле, решение хорошее. Минусом здесь является только необходимость сравнивать строки. Числа сравниваются в разы быстрее. Поэтому, если предложить пользователю 'Введите цифру: 0-камень, 1-ножницы, 2-бумага: ', дальнейшее решение можно построить на сравнении чисел. Но это уже, если захочется погрузиться в задачу)

2023-05-25 20:55 UTC, IlyaOrlov commented on Practice/Sapegov/Sap4.8.py
> +    if you == 'камень' or you == 'ножницы' or you == 'бумага':
Мы ещё не проходили кортежи, но с их использованием возможна ещё такая запись условия: 
```python
if you not in ('камень', 'ножницы', 'бумага'):
```
Аналогично для стр.18

2023-05-26 19:09 UTC, DmitriySapegov commented on Practice/Sapegov/Sap4.8.py
> +    if you == 'камень' or you == 'ножницы' or you == 'бумага':
Так а для чего not?
при нем всю конструкцию менять надо. а вот без not все корректно работает и менять структуру не надо

2023-05-26 19:16 UTC, DmitriySapegov commented
Закинул альтернативное решение через цифры. Не знаю, такую конструкцию вы предполагали? сравнить цифры как-то иначе у меня не пришло в голову. По сути тоже решение с использование кортежей, только вместо строк - цифры)

2023-05-26 19:59 UTC, IlyaOrlov commented on Practice/Sapegov/Sap4.8.py
> +    if you == 'камень' or you == 'ножницы' or you == 'бумага':
Упс... поправочка: not случайно написал(

2023-05-26 20:06 UTC, IlyaOrlov approved these changes

2023-05-26 20:09 UTC, IlyaOrlov commented
> 

Отлично! Это как раз то, что нужно! На самом деле, числа тоже можно комбинировать и сравнивать по-всякому, но это уже не принципиально. А вот само использование чисел, их сравнение и арифметические операции - это гораздо эффективнее, чем работа со строками.

2023-05-26 20:10 UTC, merged