Task 0.Edit 1
IlyaOrlov/PythonCourse2.0_May23 pull request #79
Opened 2023-05-26 07:08 UTC by OzerovaKs

2023-05-26 07:36 UTC, IlyaOrlov requested changes
Всё супер! Оставил комментарии по мелочи.

2023-05-26 07:36 UTC, IlyaOrlov commented on Practice/Ozerova/3/3.4.py
> +result = x.replace("А", "*")
А это русская А или английская? Может, сразу и одну, и другую заменять?

2023-05-26 07:36 UTC, IlyaOrlov commented on Practice/Ozerova/3/3.4.py
> +
Многовато пустых строк. Одной достаточно)

2023-05-26 16:55 UTC, IlyaOrlov requested changes
Всё ОК. Добавил несколько пожеланий.

2023-05-26 16:55 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.2.py
> +    y = y+1
Можно покороче: y += 1

2023-05-26 16:55 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.2.py
> +    print(y," цифра равна ",z)
Форматные строки - это же удобно и наглядно) Давайте их использовать!

2023-05-26 16:55 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.4.py
> +while (y := input("Привет: ")) != "хватит":
Как странно получается: программа выводит слово "Аргументируй", а потом - "Привет". И каждый раз - "Привет". Лучше приглашение ко вводу как-то иначе сделать. Например, ">>" или "Ваше слово: ".

2023-05-26 20:23 UTC, OzerovaKs commented on Practice/Ozerova/4/4.2.py
> +    y = y+1
скорректировано

2023-05-26 20:23 UTC, OzerovaKs commented on Practice/Ozerova/4/4.2.py
> +    print(y," цифра равна ",z)
предполагаю, что можно упростить и сделать короче, не совсем понимаю как..

2023-05-26 20:23 UTC, OzerovaKs commented on Practice/Ozerova/4/4.4.py
> +while (y := input("Привет: ")) != "хватит":
скорректировано

2023-05-27 05:04 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.2.py
> +    print(y," цифра равна ",z)
Речь об этих форматных строках:
```python
print(f"{y} цифра равна {z}")
```

2023-05-28 11:27 UTC, OzerovaKs commented on Practice/Ozerova/4/4.2.py
> +    print(y," цифра равна ",z)
Поняла, спасибо.

2023-05-28 15:02 UTC, IlyaOrlov requested changes
ОК. Есть замечания!

2023-05-28 15:02 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.6.py
> +def maxmin(x, y):
Почему определение функции - ниже основного кода?

2023-05-28 15:02 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.6.py
> +    return a
Получилась функция - "два в одном", т.е. она и возвращает результат, и выводит его на экран. Это абсолютно нормально. Но в задании требовалось две функции: одна выводит результат на экран (print), другая возвращает результат (return).

2023-05-28 18:33 UTC, OzerovaKs commented on Practice/Ozerova/4/4.5.py
> +    if n.isalpha():
исправлено

2023-05-28 18:36 UTC, OzerovaKs commented on Practice/Ozerova/4/4.6.py
> +def maxmin(x, y):
перенесла все вниз

2023-05-28 18:36 UTC, OzerovaKs commented on Practice/Ozerova/4/4.6.py
> +    return a
хммм.. пока не знаю как тогда написать, подумаю..

2023-05-28 18:59 UTC, IlyaOrlov requested changes
Вопросы ещё остаются.

2023-05-28 18:59 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.5.py
> +    if n.isdigit():
Да, но только должно быть:
```python
if not n.isdigit():
```

2023-05-28 18:59 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.5.py
> +        break
Если тут выполнить break, то у пользователя уже больше не будет шанса ввести число.

2023-05-28 18:59 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.6.py
> +def maxmin(x, y):
Хорошо. И на всякий случай уточню: **x** и **y** в стр.1 (локальные) и **x** и **y** в стр.11 и 12 (глобальные) - это разные **x** и **y**.  И связываются они друг с другом только при вызове функции в стр.13.

2023-05-28 18:59 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.6.py
> +    return a
Да так же, как и maxmin. Только это будет, например, maxmin2 и у неё не будет return.

2023-05-31 10:57 UTC, IlyaOrlov commented on Practice/Ozerova/4/4.8.py
> +        print("Вы проиграли. Если не хотите играть, напишите стоп")
Сейчас можно оставить, как есть, но на будущее, чтоб не писать повторяющийся код, текст и т.д., стоит, условно говоря, "выносить общий множитель за скобки". Т.е. если текст повторяется, можно записать его в переменную и далее использовать уже эту переменную. Тогда, если понадобится этот текст поменять (например, вместо "стоп" использовать слово "хватит"), достаточно внести изменения в одном месте, а не во всём коде.
```python
s = "Если не хотите играть, напишите стоп"
print(f"Вы выиграли. {s}")
print(f"Вы проиграли. {s}")
```

2023-05-31 10:57 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-05-31 10:57 UTC, merged