O lunina
IlyaOrlov/PythonCourse2.0_May23 pull request #87
Opened 2023-05-29 12:27 UTC by LesyaLunina

Task 3.4 
Можно сделать так, чтобы замена не зависела от раскладки?

2023-05-29 13:05 UTC, IlyaOrlov requested changes
ОК. Но есть существенное замечание!

2023-05-29 13:05 UTC, IlyaOrlov commented on Practice/Lunina/Practice 3/Task 3.4.py
> +if language.upper() == "LF":
Код в стр.17-23 по сути такой же, как и в стр. 9-15. Лучше просто слегка видоизменить условие:
language = language.upper() == "ДА"
```python
if language == "ДА" or language == "LF":
```
Замена сразу русской, английской, большой, маленькой буквы возможна следующим образом:
```python
a1 = a.replace("A", "*").replace("a", "*").replace("А", "*").replace("а", "*")
```
В дальнейшем мы пройдём библиотеку регулярных выражений re, позволяющую сделать то же самое, но эффективней и изящней.

2023-05-29 14:15 UTC, LesyaLunina reviewed
Так гораздо лучше. Но сейчас у меня почему то вместе с финальной фразой печатается и значение else

2023-05-29 19:46 UTC, IlyaOrlov requested changes
Хорошо. Но вопросы ещё есть.
Видимо, у Вас очень быстрый компьютер, раз Вы постоянно стараетесь замедлить его работу sleep'ами:)

2023-05-29 19:46 UTC, IlyaOrlov commented on Practice/Lunina/Practice 3/Task 3.4.py
> +if language.upper() == "НЕТ":
В этой строке вместо if надо написать elif, тогда значение из-под else печататься не будет)

2023-05-29 19:46 UTC, IlyaOrlov commented on Practice/Lunina/Practice 3/Task 3.5.py
> +res = a1 in a
Через in, конечно, тоже можно проверить в этом случае, но выглядит странно. Это как есть ножом вместо ложки:)  Всё-таки палиндром - это когда "перевёрнутая строка совпадает с исходной", а не когда "перевёрнутая строка включает в себя исходную". Чем ближе решение к определению - тем оно понятней.

2023-05-29 19:46 UTC, IlyaOrlov commented on Practice/Lunina/Practice 3/Task 3.5.py
> +a = input("Введите слово: \n")
А если пользователь введёт слово "Топот" (т.е. палиндром, начинающийся с большой буквы)?

2023-05-30 04:20 UTC, LesyaLunina reviewed
Task 3.4 edit 2. Исправила строку 16 - действительно работает.  
Коммент про время: мне кажется так выглядит человечнее, особенно в чатах. ) Больше так не буду , только в крайних случаях.

2023-05-30 04:23 UTC, LesyaLunina commented on Practice/Lunina/Practice 3/Task 3.5.py
> +res = a1 in a
Согласна. Решила показать 2 решения, которые нашла по презентации. Посмотрела только 3 лекцию. Исправлю.

2023-05-30 04:25 UTC, LesyaLunina commented on Practice/Lunina/Practice 3/Task 3.5.py
> +a = input("Введите слово: \n")
А это хороший вопрос. Об этом тоже подумала, после того как оправила. Видела некий модуль, который в следующем изменении применю

2023-05-30 04:54 UTC, LesyaLunina reviewed
добавлен метод lower()

2023-05-30 07:32 UTC, IlyaOrlov requested changes
Замечаний больше нет! Кроме одного: в Pull Request попала папка .idea (ну и здесь высвечиваются соответствующие файлы). .idea - это служебная папка PyCharm, ей в main делать нечего. Нужно удалить эту папку и закоммитить/запушить информацию об удаленных файлах. PyCharm для себя эту папку всё равно пересоздаст, но в коммит её добавлять уже не надо.

2023-05-30 09:09 UTC, merged