HW4. tasks 1-6, 8. version 1.
IlyaOrlov/PythonCourse2.0_May23 pull request #88
Opened 2023-05-29 13:04 UTC by pavelzagy

ДЗ 4, задачи с 1-6 и 8. версия 1. Так же переместил задачи к 2 лекции в папку

2023-05-29 18:46 UTC, IlyaOrlov requested changes
Хорошо. Но есть некоторые замечания!

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-1.py
> +    print(f'{a}')
Почему эта **a** отдельно выводится, а не в общем цикле?

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-1.py
> +    while a != 100:
100 тоже надо выводить. И безопаснее использовать сравнение на >,<,>=,<=, т.к. если б шаг был не 1, а, например, 2, можно было бы случайно проскочить ограничение != 100 и попасть в бесконечный цикл.

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-1.py
> +        if (a % 15) == 0:
Скобки лишние. И в стр.20 и 22 тоже.

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-2.py
> +# Необходимо сделать проверку, вводит ли пользователь именно число?
Да, такую проверку сделать желательно.

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-2.py
> +    x = int(x)
А если не преобразовывать **x** к int, а просто пройтись по нему, как по строке и вывести содержащиеся в нём символы?

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-3.py
> +        y = y + int(x)
Не совсем то. В задаче требовалось именно склеить цифры в число, т.е. просто y += x (при условии, что изначально y = '').

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-5.py
> +    num = random.randint(a, b)
Не стоило ради одной операции функцию создавать)

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-5.py
> +        elif int(x) > num:
Здесь можно просто else. Т.к. если **x** не равен **num** и не меньше его, то он, по-любому, больше.

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-6.py
> +def fun1(a,b):
Не хватает пробела после запятой.

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-5.py
> +    print("Программа успешно завершена!")
При выходе из цикла по break эта строка в else не напечатается!

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-5.py
> +        elif int(x) < num:
Дважды вызывается **int(x)** для одного и того же **x**. Стоит оптимизировать, например, написав перед стр.25: **x = int(x)**. И дальше работать просто с **x**.

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-8.py
> +    continue
continue здесь лишний

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-8.py
> +        elif x == "КАМЕНЬ" and y == "БУМАГА":
Стоит сгруппировать условия, чтоб избежать лишних сравнений. Например, так:
```python
        elif x == "КАМЕНЬ":
            if y == "БУМАГА":
                print(f"Машина: {y} = Победила машина!")
            else:
                print(f"Машина: {y} = Победил человек!")
```

2023-05-29 18:46 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-8.py
> +    if x == "КАМЕНЬ" or x == "НОЖНИЦЫ" or x == "БУМАГА":
Можно чуть упростить: 
```python
if x in {"КАМЕНЬ", "НОЖНИЦЫ", "БУМАГА"}:
```
Здесь использован ещё не пройденный нами тип **множество** - оптимальный для операции **in**.

2023-05-29 18:52 UTC, pavelzagy commented
Спасибо, принял в работу

2023-05-30 20:12 UTC, pavelzagy commented
Исправил

2023-05-30 21:02 UTC, IlyaOrlov requested changes
Стало лучше. Но некоторые замечания остались. И добавились новые.

2023-05-30 21:09 UTC, pavelzagy commented on Practice/Zagorskiy/HW4/HW4-1.py
> +        print(f'{a}')
Все, понял. Я раньше дал переменной "а" значение 1 и программа начинала вывод с 2. Теперь же дал переменной значение 0 и все стало на свои места

2023-05-30 21:12 UTC, pavelzagy commented on Practice/Zagorskiy/HW4/HW4-3.py
> +        y = y + x
Спасибо, честно говоря, думал что такое выражение применимо только когда в выражении есть числа

2023-05-30 21:14 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-2.py
Можно оставить, т.к. бывают задачи, где такой подход требуется (если в условии задачи прямо сказано, что мы работаем с числом, и в строку его преобразовывать нельзя, т.е. задача - чисто на математику).
Но разъяснительный комментарий написать всё же стоит.

2023-05-30 21:19 UTC, pavelzagy commented on Practice/Zagorskiy/HW4/HW4-5.py
> +    print("Программа успешно завершена!")
У меня возник вопрос: после того, как пользователь угадал число, то программа снова просит его угадать число, но оно все тоже. Стоит ли сделать так, чтобы программа, после угадывания, перезапускалась полностью, или же цель достигнута?

2023-05-30 21:19 UTC, pavelzagy commented
Исправил, спасибо большое за полезные советы)

2023-05-30 21:24 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-5.py
> +    print("Программа успешно завершена!")
Если смотреть строго по зданию, то программа должна останавливаться. Но можно и перезагадать число. Отгадывать то же самое число не имеет смысла.

2023-05-30 21:26 UTC, pavelzagy commented on Practice/Zagorskiy/HW4/HW4-5.py
> +    print("Программа успешно завершена!")
Получается, что после вывода "число угадано" нужно было оставить break, чтобы программа завершалась

2023-05-30 21:28 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-8.py
> +    if x == "КАМЕНЬ" or x == "НОЖНИЦЫ" or x == "БУМАГА":
Ну а если вынести ans_list = ["КАМЕНЬ", "НОЖНИЦЫ", "БУМАГА"] из функции  в основной код, то можно проверять и так: 
```
if x in ans_list:
```
Получится гораздо короче.

2023-05-30 21:28 UTC, IlyaOrlov commented on Practice/Zagorskiy/HW4/HW4-5.py
> +    print("Программа успешно завершена!")
Да

2023-05-30 21:36 UTC, pavelzagy commented on Practice/Zagorskiy/HW4/HW4-8.py
> +    if x == "КАМЕНЬ" or x == "НОЖНИЦЫ" or x == "БУМАГА":
Действительно, можно даже от функции отказаться

2023-05-30 21:41 UTC, pavelzagy commented
Исправил

2023-05-30 21:45 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2023-05-30 21:45 UTC, merged