домашнее задание №5
IlyaOrlov/PythonCourse2.0_May23 pull request #89
Opened 2023-05-29 13:07 UTC by AlenaStupina

2023-05-29 14:07 UTC, IlyaOrlov requested changes
Хорошо. Оставил комментарии.

2023-05-29 14:07 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_6.py
> +        print('Числа равны')
Нужен ли этот вывод с точки зрения практического использования функции?
Если в случае равенства аргументов, мы выводим любой из них - то можно просто условие в стр.11 поменять на >=. 
Если мы хотим как-то выделить случай равенства, то стоит возвращать какой-то третий вариант (например, None).

2023-05-29 14:07 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_8.py
> +# Не могу разобраться со следующей строкой. Вы говорили до этого, что логические операторы имеют самый низкий приоритет
У "моржового" оператора приоритет ещё ниже, чем у логических операторов (см. [здесь](https://habr.com/ru/companies/skillfactory/articles/683418/#:~:text=%D0%95%D1%89%D1%91%20%D0%BE%D0%B4%D0%BD%D0%B0%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0%2C%20%D1%81%C2%A0%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D0%BE%D0%B9%20%D0%B2%D1%8B%C2%A0%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%D0%B5%20%D1%81%D1%82%D0%BE%D0%BB%D0%BA%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%2C%C2%A0%E2%80%94%20%D0%BF%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%20%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0%20%D0%BC%D0%BE%D1%80%D0%B6%D0%B0%2C%20%D0%B2%D0%B5%D0%B4%D1%8C%20%D0%BE%D0%BD%20%D0%BD%D0%B8%D0%B6%D0%B5%20%D0%BF%D1%80%D0%B8%D0%BE%D1%80%D0%B8%D1%82%D0%B5%D1%82%D0%B0%20%D0%BB%D0%BE%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85%20%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2%3A)), поэтому его рекомендуется всегда брать в скобки.

2023-05-29 14:07 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_8.py
> +                                                                                        pl_2 == var[0]):
Как-то кривовато перенос получился(

2023-05-29 14:07 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_8.py
> +    pl_2 = random.choice(var)
Этот код можно опустить ниже стр.15-17, а стр.18 начать с if. Т.к. если pl_1 некорректный, то рассчитывать pl_2 не имеет смысла.

2023-05-29 14:54 UTC, AlenaStupina commented on Practice/Stupina/homework_5/task_6.py
> +        print('Числа равны')
Да, я хотела выделить случай равенства, с none у меня был первый вариант и он "резал " глаз мне, поэтому решила так) Тем более это наверное не ресурсозатратная операция?

2023-05-29 14:56 UTC, AlenaStupina commented on Practice/Stupina/homework_5/task_8.py
> +# Не могу разобраться со следующей строкой. Вы говорили до этого, что логические операторы имеют самый низкий приоритет
Ах ясно... А я мучалась, голову ломала . Получается тогда, к прошлому дз Ваш комментарий не совсем точен: " Приоритет операций и так однозначен (логические операторы всегда выполняются последними),"? Мне чтоб понять)

2023-05-29 14:58 UTC, AlenaStupina commented on Practice/Stupina/homework_5/task_8.py
> +                                                                                        pl_2 == var[0]):
Меня смутило, что Pycharm не подчеркнул, и к тому же сам так перенёс, и я поэтому подумала, что при переносе выражение ставится под то выражение, к которому оно непосредственно относится, ну в данном случае под свою скобку. Исправлю

2023-05-29 20:04 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_6.py
> +        print('Числа равны')
Нет, ресурсы не перерасходуются) Можно оставить так. Но использование None - это приемлемый и распространённый вариант.

2023-05-29 20:06 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_8.py
> +# Не могу разобраться со следующей строкой. Вы говорили до этого, что логические операторы имеют самый низкий приоритет
Получается так)
У "моржового" оператора, как и у оператора присваивания самый низкий приоритет, чтоб можно было связывать переменную в т.ч. и с результатом логических операций:
```python
x = a == b
```

2023-05-29 20:08 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_8.py
> +    pl_2 = random.choice(var)
Т.к. в первом if у Вас есть continue, то оба вместе они всё равно выполняться не будут.

2023-05-29 20:09 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_8.py
> +                                                                                        pl_2 == var[0]):
Смотря после какого символа в строке нажать Enter. Я бы разделил по оператору or.

2023-05-30 08:04 UTC, AlenaStupina commented
Исправила замечания

2023-05-30 08:06 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_8.py
> +                                                                                        pl_2 == var[0]):
Лучше всего про это написано [здесь](https://peps.python.org/pep-0008/#indentation)
Ещё и с примерами)

2023-05-30 08:13 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_6.py
> +        out = 'Числа равны'
А с таким решением не согласен категорически! 
Функции, которые возвращают значения, обычно используются в составе выражений. Например, `res = fun_max_2(100, 100) ** 2` ... А что, пользователь хотел посчитать квадрат наибольшего из чисел. Вот он удивится, когда увидит ошибку применения операции ** для непонятно откуда взявшейся строки.
Лучше, чтоб функция возвращала значения только одного типа (и None в случае ошибки или какой-то нестандартной ситуации). А так, что она в одном случае будет возвращать числа, в другом - строки, - это не вариант.

2023-05-30 08:17 UTC, AlenaStupina commented on Practice/Stupina/homework_5/task_6.py
> +        out = 'Числа равны'
В задании то про возможность дальнейшего использование функции не было написано ))) 
Хорошо, исправлю

2023-05-30 08:46 UTC, AlenaStupina commented
Исправлено

2023-05-30 09:32 UTC, IlyaOrlov commented on Practice/Stupina/homework_5/task_6.py
> +        out = 'Числа равны'
Замечание относится уже не к заданию, а к лучшим практикам написания функций. Можно построить дом, у которого дверь будет на крыше. Дом есть, вход есть, всё по заданию... Но кто ж знал, что этим кто-то пользоваться будет)

2023-05-30 09:44 UTC, AlenaStupina commented on Practice/Stupina/homework_5/task_6.py
> +        out = 'Числа равны'
Ну это уже утрировано) Но да, я поняла все буквально, буду думать "шире"

2023-05-30 09:55 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-05-30 09:55 UTC, merged