Tanacheva branch
IlyaOrlov/PythonCourse2.0_May23 pull request #90
Opened 2023-05-30 19:47 UTC by JuliaTanacheva

2023-05-30 20:41 UTC, IlyaOrlov requested changes
Хорошо. Но есть некоторые замечания.

2023-05-30 20:41 UTC, IlyaOrlov commented on Practice/Tanacheva/task3.4.py
> +str2 = str1.replace("А", "*")
Это русская А или английская?

2023-05-30 20:41 UTC, IlyaOrlov commented on Practice/Tanacheva/task3.5.py
> +word1 = str(input("Введите слово для проверки: "))
str - лишняя: input и так всегда возвращает значение строкового типа.

2023-05-30 20:41 UTC, IlyaOrlov commented on Practice/Tanacheva/task3.5.py
> +print (f"Слово является палиндромом? {word2 == word1.lower()}")
Лишний пробел между print и скобкой. 
Ну и у одной и той же переменной word1 дважды вызывается один и тот же метод lower()
Стоит где-то выше по коду упростить себе задачу: word1 = word1.lower()

2023-05-30 20:41 UTC, IlyaOrlov commented on Practice/Tanacheva/task3.3.py
Всё-таки шифрование и дешифрование должно выполняться разными программами, иначе смысл теряется.

2023-05-30 20:41 UTC, IlyaOrlov commented on Practice/Tanacheva/task4.2.py
> +s = str(input("Введите пятизначное число:"))
str - лишняя: input и так всегда возвращает значение строкового типа.

2023-05-30 20:41 UTC, IlyaOrlov commented on Practice/Tanacheva/task4.2.py
> +for number in range(0, 5):
Лучше указывать не конкретное число, а переменную или выражение к которой мы привязываем наши вычисления. В данном случае, мы их привязываем к длине строки s, т.е. len(s).
Если потом заказчик попросит переделать программу, например, для шестизначных чисел, нам не придётся менять этот код.

2023-06-04 20:32 UTC, JuliaTanacheva commented on Practice/Tanacheva/task3.4.py
> +str2 = str1.replace("А", "*")
это русская А, надо чтобы работала и при вводе русской и при вводе английской?

2023-06-05 06:03 UTC, Tetrackon requested changes
В целом всё хорошо! Особенно мне приглянулась задачка с палиндромом))) Есть пара замечаний.

2023-06-05 06:03 UTC, Tetrackon commented on Practice/Tanacheva/task5.6.1.py
> +    if x < y:
Здесь лучше использовать else, вместо второго ifю Потому что если х не равен и не больше у, то он сто процентов меньше его.

2023-06-05 07:36 UTC, IlyaOrlov commented on Practice/Tanacheva/task3.4.py
> +str2 = str1.replace("А", "*")
Необязательно. Просто обращаю Ваше внимание на неоднозначность интерпретации задания)

2023-06-06 21:13 UTC, JuliaTanacheva commented on Practice/Tanacheva/task4.5.py
> +    if int(number2) > number1:
Если написать строку while (number2 := int(input('Введите число:'))).isdigit() , то пользователь не может ввести нечисловой символ (выдает ошибку).

2023-06-07 04:52 UTC, IlyaOrlov commented on Practice/Tanacheva/task4.5.py
> +    if int(number2) > number1:
Имелось в виду, что где-то выше стр.12 можно написать number2 = int(number2)
Вовсе не обязательно добавлять это преобразование типа именно в условие while.

2023-06-07 04:59 UTC, IlyaOrlov requested changes
Всё хорошо. Остались замечания по мелочи.

2023-06-07 04:59 UTC, IlyaOrlov commented on Practice/Tanacheva/task4.5.py
> +    elif int(number2) == number1:
А здесь я бы даже просто else написал. Ведь, если одно число не больше другого и не меньше, то эти числа, по-любому, равны)

2023-06-07 04:59 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.8.py
> +while (i := int(input("Хотите сыграть в игру, нажмите 1, если нет нажмите 2:"))) == 1:
i не используется. Поэтому её можно убрать и из стр.30, и из стр.31.

2023-06-07 04:59 UTC, IlyaOrlov commented on Practice/Tanacheva/task5.8.py
> +        elif computer_action == "бумага":
Поскольку компьютер выбирает строго из значений actions, в стр. 16, 21, 26 вместо elif можно смело писать else - одной проверкой будет меньше;)

2023-06-08 16:33 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-06-08 16:34 UTC, merged