HW_5_Fedorov
IlyaOrlov/PythonCourse2.0_May23 pull request #92
Opened 2023-05-31 20:53 UTC by Fed909

2023-06-01 07:40 UTC, IlyaOrlov requested changes
Супер! Но есть нюансы.

2023-06-01 07:40 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +# Очень странно что не так :) Таков путь
Сортировки бывают разные) Списковый метод sort() - это "быстрая сортировка", в задаче требуется "сортировка выбором". Ну и сама задача - не на знание справочной информации методов, а на понимание алгоритмов и структур данных.

2023-06-01 07:40 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +    index_min = arr[index::].index(num_min) + index
Давайте теперь подумаем про эффективность алгоритма. Функция min в стр.9 бежит по списку arr и находит минимальный элемент. В стр.10 уже функция index опять бежит по этому же списку, чтоб найти **ранее уже найденный** num_min, чтоб узнать его индекс. Это же лишняя работа. А если arr будет состоять из миллиарда элементов?
Тут вместо min и index лучше написать свою функцию, которая будет идти по списку и не только минимум искать, но и СРАЗУ запоминать индекс этого минимума (помните задачу 4.2?).

2023-06-02 08:22 UTC, IlyaOrlov requested changes
Получилось всё супер! Оставил несколько предложений по доведению алгоритмов до идеального состояния)
Условно говоря, на собеседовании такие решения бы приняли, но всё равно спросили бы, что ещё можно улучшить.

2023-06-02 08:22 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +    return [num_min, idx_min]
Скобки указывать не нужно. Вернётся просто кортеж: num_min, idx_min

2023-06-02 08:22 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +    num_min_idx = minim(arr[index:])
А здесь для удобства, чтоб потом индексирование не использовать, стоит сразу две переменные применить: `num_min, idx = minim(arr[index:])` Ну и сопоставятся соответственно num_min и num_min, idx и idx_min.

2023-06-02 08:22 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.2.py
> +    new_list = list()
Всё ОК. Чтоб получилось вообще идеально, вместо list **здесь** нужно использовать set.

2023-06-02 08:22 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.4.py
> +        for index2, j in enumerate(del_col):
Чтоб не корректировать удаляемый индекс j-index2, можно просто начинать удалять с конца.
Для этого достаточно отсортировать del_col по убыванию - sort(reverse=True).

2023-06-02 08:22 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.4.py
> +            if j == num and index not in del_col:
Чтоб не выполнять проверку index not in del_col, можно del_col просто сделать множеством. А перед сортировкой преобразовать его в список.

2023-06-04 16:13 UTC, Fed909 commented on Practice/Fedorov/HW_5/5.2.py
> +    new_list = list()
а чем мне поможет set? в моём примере, что-то переделывать нужно чтобы использовать set :)

2023-06-04 16:42 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.2.py
> +    new_list = list()
Операция in для поиска элемента в списке линейно зависит от количества элементов в этом списке, т.к. в худшем случае придётся пересмотреть все элементы списка.
Операция in для поиска элемента во множестве практически не зависит от количества элементов (благодаря тому, как эта структура данных размещается в памяти).
Поэтому для проверки наличия некоторого элемента в списке new_list из миллиарда элементов операция in потребует в худшем случае миллиард проверок. 
А для проверки наличия некоторого элемента во множестве из миллиарда элементов операция in потребует в худшем случае одну проверку (хотя и чуть более сложную).

2023-06-04 17:52 UTC, Fed909 commented on Practice/Fedorov/HW_5/5.4.py
> +            if j == num and index not in del_col:
С этим тоже не понятно, нужно же другую проверку какую-то делать?

2023-06-04 18:13 UTC, Fed909 commented on Practice/Fedorov/HW_5/5.2.py
> +    new_list = list()
большое спасибо!

2023-06-04 18:45 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.4.py
> +            if j == num and index not in del_col:
Именно так. Можно считать, что такая проверка у множества внутри)

2023-06-06 09:52 UTC, IlyaOrlov requested changes
Хорошо. Осталось ещё несколько замечаний.

2023-06-06 09:52 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +    arr[idx + index] = arr[index]
Ещё нюанс. Если index == 0, то менять arr[index] местами с самим собой не нужно)

2023-06-06 09:52 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +for index, i in enumerate(arr):
Есть такая практика: неиспользуемые переменные, которые добавлены чисто для соблюдения синтаксиса (как i в этом коде), называть `_` (нижнее подчеркивание).

2023-06-06 09:52 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.2.py
> +        new_list = list(new_list)
Тут на первом же элементе множество превращается обратно в список, и вся магия быстрого поиска in исчезает)
Можно просто: new_list.add(i)
Правда, имя new_list - какое-то не очень подходящее для множества)

2023-06-06 19:02 UTC, Fed909 commented on Practice/Fedorov/HW_5/5.1.py
> +    arr[idx + index] = arr[index]
Ну по идее ничего не поменяется, нужно ли вводить такое условие index == 0? 
Программа будет работать и эта замена не приведет к большим затратам ? Или я не прав?

2023-06-06 20:49 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +    arr[idx + index] = arr[index]
Вот как раз в соседнем пулл реквесте этот вопрос обсуждали) Скопирую прямо оттуда:

Берём миллиард элементов и крайние случаи...
Если список уже отсортирован по возрастанию, для каждого элемента idx будет 0. Будет каждый раз два лишних присваивания. Итого: 1млрд * 2 = 2млрд. лишних операций.
Если список отсортирован по убыванию, для каждого элемента idx будет всегда отличен от 0. Будет каждый раз одна лишняя проверка. Итого: 1млрд * 1 = 1млрд. лишних операций.
Про вероятность того, что список отсортирован по возрастанию или убыванию ничего неизвестно, так что стоит считать эти ситуации равновероятными.
При этом, присваивание (запись) само по себе занимает больше времени, чем проверка (чтение).
Считаю, что из двух зол стоит выбрать меньшее.

2023-06-06 20:51 UTC, IlyaOrlov requested changes
Всё супер! Замечаний нет. Только открытый вопрос по 5.1.py

2023-06-07 21:16 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.
Для информации:
1) В children_example.py ещё можно использовать в качестве решения DEFAULT.get('children').copy() Оно будет работать, даже если мы решим поменять тип DEFAULT['children'] на множество или словарь.
2) Хочу явно отметить, что применение list() приводит к созданию нового списка (равно как и метод .copy()). Поэтому, например, следующий код:
```python
lst = [1, 2, 3]
for i in list(lst):
    print(i)
```
содержащий вроде бы безобидное преобразование к типу list (как бы на всякий случай), на самом деле выполняет лишнюю работу и может потребовать вдвое больше памяти (на новый список), чем нужно. А если в lst будет миллиард элементов...?)

2023-06-07 21:20 UTC, IlyaOrlov requested changes
Ещё один вопрос остался!

2023-06-07 21:20 UTC, IlyaOrlov commented on Practice/Fedorov/HW_5/5.1.py
> +    return num_min, idx_min
Вот только ещё один момент остался!
Если я вызову minim просто для пустого списка, т.е. minim([]) - будет ошибка. Стоит предусмотреть эту ситуацию.

2023-06-08 09:45 UTC, IlyaOrlov requested changes
Предлагаю другой вариант инициализации idx_min

2023-06-13 20:05 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-06-13 20:06 UTC, merged