Задачи 6,7 к лекции 4 + задача 5.2
IlyaOrlov/PythonCourse2.0_May23 pull request #93
Opened 2023-05-31 21:29 UTC by DmitriySapegov

Есть подозрение, что задача 5.2 должна решаться как-то легче.

2023-06-01 07:45 UTC, IlyaOrlov requested changes
Супер! оставил комментарий по 5.2

2023-06-01 07:45 UTC, IlyaOrlov commented on Practice/Sapegov/Sap5.2.py
> +        for j in range(len(x) - 1):
Стр.3 и 4 стоит заменить на for j in range(i)
Мы же смотрим элементы предшествующие i-му.
Хорошее решение. Ещё вариант - создать вспомогательный контейнер, куда складывать пройденные элементы. И проверять присутствует ли x[i] in этот контейнер.

2023-06-01 14:42 UTC, DmitriySapegov commented on Practice/Sapegov/Sap5.2.py
> +        for j in range(len(x) - 1):
Вот да! Как раз и думал создать пустой список и через .append закидывать в него по элементу и потом проверять есть ли новый элемент в этом списке. Но что-то так и не добил это решение. Родилось через двойной цикл)

2023-06-01 19:05 UTC, IlyaOrlov requested changes
Ещё один момент остался.

2023-06-01 19:05 UTC, IlyaOrlov commented on Practice/Sapegov/Sap5.2.py
> +            if i != j:
Лишняя проверка! range не включает указанную верхнюю границу (в данном случае i), поэтому i и так никогда не совпадёт с j.

2023-06-04 18:54 UTC, DmitriySapegov commented on Practice/Sapegov/Sap5.2.py
> +            if i != j:
Да, точно!
Исправил

2023-06-04 19:22 UTC, IlyaOrlov approved these changes
Всё отлично! Замечаний нет.

2023-06-04 19:23 UTC, merged