домашнее задание №6
IlyaOrlov/PythonCourse2.0_May23 pull request #94
Opened 2023-06-01 08:36 UTC by AlenaStupina

2023-06-01 19:08 UTC, IlyaOrlov requested changes
Комментарий по стилю оставил.

2023-06-01 19:08 UTC, IlyaOrlov commented on Practice/Stupina/homework_6/task_7_decorator.py
> +#здесь же должны быть 2 строки пустые (отделяем ф-ию верхнего уровня)?
Нет. Функция верхнего уровня - это wrapper, и всё, что относится к её телу (до стр.11). А вот после стр.11 нужны 2 пустые строки.

2023-06-01 19:48 UTC, AlenaStupina commented on Practice/Stupina/homework_6/task_7_decorator.py
> +#здесь же должны быть 2 строки пустые (отделяем ф-ию верхнего уровня)?
я не совсем корректно написала комментарий, имела ввиду: отделяем функцию верхнего уровня wrapper от new_fun (new_fun функция не верхнего уровня в моем понимании). 
Ок, тогда что такое функция верхнего уровня? Я думала это понятие относится к вложенным функциям, внешняя функция- функция верхнего уровня. Так же как и с поиском переменных локальных: если они не объявлены в теле ф-ии, ищем их на уровень выше, т.е. во внешней ф-ии, отсюда и понятие, что внешняя ф-ия это  ф-ия верхнего уровня...

2023-06-01 20:34 UTC, AlenaStupina commented on Practice/Stupina/homework_6/task_7_decorator.py
> +#здесь же должны быть 2 строки пустые (отделяем ф-ию верхнего уровня)?
Аа,  в Pep8 значит имелось ввиду отделять функции верхнего уровня друг от друга, а не от вложенных?

2023-06-01 21:17 UTC, IlyaOrlov commented on Practice/Stupina/homework_6/task_7_decorator.py
> +#здесь же должны быть 2 строки пустые (отделяем ф-ию верхнего уровня)?
Дословно требование выглядит так: "Surround top-level function and class definitions with two blank lines." - "окружайте определения функций верхнего уровня и классов двумя пустыми линиями". К определению функции относится явно не только её заголовок, но и тело, даже если оно включает вложенную функцию.

2023-06-02 09:08 UTC, IlyaOrlov approved these changes
Отлично! Зачтено.

2023-06-02 09:08 UTC, merged