Домашнее задание №6, к четвертой лекции.
IlyaOrlov/PythonCourse2.0_May23 pull request #96
Opened 2023-06-01 13:27 UTC by AnnaKapralova

Задание №6

2023-06-01 18:59 UTC, IlyaOrlov requested changes
Хорошо. Но есть вопросы.

2023-06-01 18:59 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz4.6.py
> +
Зачем здесь и в стр.17 пустая строка?

2023-06-01 18:59 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz4.6.py
> +        return int(y)
Одни и те же **x** и **y** дважды приводятся к int. Незачем выполнять лишние операции! Можно же перед стр.15 выполнить код навроде `x = int(x)` и дальше работать с обычным **x**.
Кстати, вроде как **x** и **y** и так передаются сюда, как числа.

2023-06-02 10:43 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz4.6.py
> +def maxmin(x, y):
Раз уж всё в одном файле... Определения функций надо писать выше основного кода. Чтобы не было путаницы в названиях функций, эту можно назвать, например, maxmin2.

2023-06-02 12:17 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz4.6.py
> +def maxmin2(x, y):
ОК. И теперь определение функции (стр.13-17) поднимаем выше основного кода (стр.8-10)...

2023-06-02 12:26 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz4.6.py
> +def maxmin2(x, y):
Исправила! надеюсь в этот раз верно)

2023-06-02 12:35 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2023-06-02 12:35 UTC, merged