A kapralova
IlyaOrlov/PythonCourse2.0_May23 pull request #98
Opened 2023-06-02 20:26 UTC by AnnaKapralova

Задание №8

2023-06-03 06:28 UTC, IlyaOrlov requested changes
Хорошо. Но есть, что улучшить.

2023-06-03 06:28 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz4.8.py
> +        elif x == "камень" and y == "ножницы":
Чтоб не делать лишние проверки (например, дважды x == "камень"), стоит сгруппировать условия:
```python
if x == "камень":
    if y == "ножницы":
        print(f"Мой вариант: {y} - Ты выиграл!")
    else:  # очевидно, здесь y == "бумага"
        print(f"Мой вариант: {y} - Ты проиграл!")
elif x == "ножницы":
...
```

2023-06-03 06:28 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz4.8.py
> +    if x == "камень" or "ножницы" or "бумага":
Можно упростить проверку, используя новые типы данных, которые мы изучили: 
```python
if x in ("камень", "ножницы", "бумага"):
```
А если вытащить z из game сюда, то вообще просто получится: `if x in z:`

2023-06-03 06:28 UTC, IlyaOrlov commented on Practice/AKapralova/KapralovaDz4.8.py
> +        continue
continue здесь лишний

2023-06-03 19:12 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz4.8.py
> +        continue
Ок, убрала.

2023-06-03 19:12 UTC, AnnaKapralova commented on Practice/AKapralova/KapralovaDz4.8.py
> +        elif x == "камень" and y == "ножницы":
Да, так выглядит на много проще. Изменила.

2023-06-04 08:26 UTC, IlyaOrlov requested changes
Ну осталось теперь сделанные изменения сюда прислать)

2023-06-04 11:45 UTC, AnnaKapralova commented
Хьюстон, у меня проблема))
Написала вам в телеграмм. Не получается git push сделать. Выдает ошибку(

2023-06-05 12:29 UTC, IlyaOrlov approved these changes
Отлично! Замечаний нет.

2023-06-05 12:29 UTC, merged