O lunina
IlyaOrlov/PythonCourse2.0_May23 pull request #99
Opened 2023-06-03 10:59 UTC by LesyaLunina

Tasc 4.6 Хотела вписать оператор условия, если пользователь введет символ, то запросить заново. Но у меня они не смогли подружиться с функцией. функцию нельзя совмещать с операторами условия?

2023-06-03 11:01 UTC, LesyaLunina reviewed
Исправила по PEP8 замечания и коммит правильный указала

2023-06-03 12:19 UTC, IlyaOrlov commented
> Tasc 4.6 Хотела вписать оператор условия, если пользователь введет символ, то запросить заново. Но у меня они не смогли подружиться с функцией. функцию нельзя совмещать с операторами условия?

Нет такого ограничения. Напишите, как Вы хотели их подружить - разберём.

2023-06-04 07:26 UTC, LesyaLunina reviewed
Логично. Поняла, приняла, исправила.

2023-06-04 08:01 UTC, LesyaLunina commented on Practice/Lunina/Practice 4/Task 4.6.py
> +        return x == y
на тот комментарий не могу ответить. Хотела что-то типа такого. Но при отображении цифр - все ок . А если вводить символы, то завершается с ошибкой.
a = input(f"Введите любое число: ")

if a.isdigit():
    a = int(a)
    b = input(f"Введите любое число: ")
    if b.isdigit():
        b = int(b)

        def myf1(x, y):
            print(f"Вы ввели: {x} и {y}. Сравним.")
            if x > y:
                print(f"Наибольшее значение в паре {x}.")
            elif x == y:
                print(f"Введенные числа равны. {x} = {y}")
            else:
                print(f"Наибольшее значение в паре {y}.")
    else:
        print(f" {b} - не число. Программа завершается")


else:
    print(f" {a} - не число. Программа завершается")

myf1(a, b)

2023-06-04 08:33 UTC, IlyaOrlov commented on Practice/Lunina/Practice 4/Task 4.6.py
> +    elif x == y:
Супер! А теперь давайте строки 12-15 превратим в:
```python
if x >= y:
    return x
```

2023-06-04 08:47 UTC, IlyaOrlov commented on Practice/Lunina/Practice 4/Task 4.6.py
> +        return x == y
Неплохо. Только определение функции в основной код тащить не надо. Определение функции - это просто её описание. Чтоб описание работало, функцию надо вызвать. А вот как раз вызов функции нужно поместить под условие:
```python
def myf1(x, y):
    print(f"Вы ввели: {x} и {y}. Сравним.")
    if x > y:
        print(f"Наибольшее значение в паре {x}.")
    elif x == y:
        print(f"Введенные числа равны. {x} = {y}")
    else:
        print(f"Наибольшее значение в паре {y}.")

a = input(f"Введите любое число: ")
if a.isdigit():
    a = int(a)
    b = input(f"Введите любое число: ")
    if b.isdigit():
        b = int(b)
        myf1(a, b)
    else:
        print(f" {b} - не число. Программа завершается")
else:
    print(f" {a} - не число. Программа завершается")
```
Проведу аналогию... Если научить ребёнка самостоятельно есть ложкой, у него создастся определение соответствующей функции eat_with_spoon(). Можно вызывать эту функцию с разными параметрами: кашей, супом и т.д. Можно вызывать эту функцию при различных условиях: 
```python
if time_to_eat:
    eat_with_spoon(soup) 
```
При этом, даже если эту функцию не вызывать, её определение вполне себе может существовать и ждать своего часа:)

2023-06-04 09:17 UTC, LesyaLunina reviewed
изменено

2023-06-04 09:17 UTC, LesyaLunina commented on Practice/Lunina/Practice 4/Task 4.6.py
> +    elif x == y:
вот очевидно же, сама не дошла до этого

2023-06-04 09:17 UTC, LesyaLunina commented on Practice/Lunina/Practice 4/Task 4.6.py
> +        return x == y
смотрю сейчас 6 лекцию и понимаю что это мой случай. Оптимизирую.

2023-06-04 11:53 UTC, IlyaOrlov reviewed
Сейчас всё отлично. Могу принять так, могу подождать оптимизации.

2023-06-05 07:25 UTC, LesyaLunina reviewed
Оптимизировала. Но меня смущают 2 момента:
1) Строка слишком с длинным кодом. В Def не дает писать функцию а = а.isdigital, т.к. он возвращает значение.
2) Если ввести вторую переменную "неправильную (букву, символ.), то он по новой запрашивает первое число.

2023-06-05 07:50 UTC, IlyaOrlov commented
> Оптимизировала. Но меня смущают 2 момента:
> 
> 1. Строка слишком с длинным кодом. В Def не дает писать функцию а = а.isdigital, т.к. он возвращает значение.
> 2. Если ввести вторую переменную "неправильную (букву, символ.), то он по новой запрашивает первое число.

1. "В Def не дает писать функцию а = а.isdigital" - не понял: это как и где? Если стр.17 кажется слишком длинной, ставите перед **or** курсор и нажимаете клавишу Enter:)
2. Потому что всё в одном условии. В этом ничего некорректного нет - просто такая логика реализована: либо вводите сразу два числа корректно, либо всё вводите заново. Можно реализовать и другую логику, разделив цикл на два - для **a** и для **b** (тут, чтоб не повторять цикл, лучше вынести код для проверки введённого числа в отдельную функцию).

2023-06-05 09:41 UTC, LesyaLunina reviewed
Вот это чудеса: от одного "enter" код преобразился. 
1) ок
2) Если на каждую переменную вводить функцию. У меня получается больше строк кода. я мучалась но не поняла как сделать.

2023-06-05 12:24 UTC, IlyaOrlov commented
> Вот это чудеса: от одного "enter" код преобразился.
> 
> 1. ок
> 2. Если на каждую переменную вводить функцию. У меня получается больше строк кода. я мучалась но не поняла как сделать.

2. Нет. Функция вводится один раз - на какое-то однотипное действие (например, проверка значения), а для каждой переменной она вызывается:
```python
def check_num(n):
    while not (x := input(f"Введите {n} число: ")).isdecimal():
        print("Вы ввели не число.")
    return x

a = check_num(1)
b = check_num(2)
```

2023-06-05 12:27 UTC, IlyaOrlov requested changes
В целом, всё ОК. Но могу подождать оптимизации ввода **a** и **b**.

2023-06-05 12:27 UTC, IlyaOrlov commented on Practice/Lunina/Practice 4/Task 4.6 optimal.py
> +
Здесь по PEP8 нужна ещё пустая строка.

2023-06-05 12:27 UTC, IlyaOrlov commented on Practice/Lunina/Practice 4/Task 4.6 optimal.py
> +
А здесь пустая строка выглядит лишней (но это уже моё субъективное мнение).

2023-06-05 13:30 UTC, LesyaLunina reviewed
Задача 4,7
Хотела сделать простую - с примером сложения, но почему-то выдает сначала две строчки с "=====", и только потом результат.

2023-06-05 13:36 UTC, LesyaLunina reviewed
Исправила ошибки по PEP8. Оптимизацию ввода a b  не сейчас - я не понимаю как оптимизировать. Чуть позднее могу вернуться к вопросу. А может и подожду посижу от Вас подсказки :-)

2023-06-05 19:42 UTC, IlyaOrlov commented
> > Вот это чудеса: от одного "enter" код преобразился.
> > 
> > 1. ок
> > 2. Если на каждую переменную вводить функцию. У меня получается больше строк кода. я мучалась но не поняла как сделать.
> 
> 2. Нет. Функция вводится один раз - на какое-то однотипное действие (например, проверка значения), а для каждой переменной она вызывается:
> 
> ```python
> def check_num(n):
>     while not (x := input(f"Введите {n} число: ")).isdecimal():
>         print("Вы ввели не число.")
>     return x
> 
> a = check_num(1)
> b = check_num(2)
> ```

Так вот же подсказка) Буквально готовое решение.

2023-06-05 19:49 UTC, IlyaOrlov commented
> Задача 4,7 Хотела сделать простую - с примером сложения, но почему-то выдает сначала две строчки с "=====", и только потом результат.

Всё верно выводится. Только у Вас в одном файле и декорированная функция вызывается, и недекорированная функция от старого кода вызывается и её результат печатается... Хорошо бы оставить в файле только то, что относится к заданию.

Введите 1 число: 1  <- это от кода в стр.28
Введите 2 число: 5  <- это от кода в стр.29
Отлично! Приступим к сравнению.  <- это от кода в стр.33
====== <- это работает декоратор (стр.3)
Вы ввели: 1 и 5 <- это работает декорированная функция (стр.13)
Наибольшее значение в паре 5. <- это работает декорированная функция (стр.19)
====== <- это работает декоратор (стр.5)
Наибольшее  возвращаемое значение 5  <- это - непонятно, зачем - от кода в стр.40

Стоит навести порядок в файле и разобраться, какой код за что отвечает.

2023-06-06 04:25 UTC, LesyaLunina commented
1) 4.6 - Сенсей, нет слов. Просто гениально! Я думала что слишком много функций ( 3шт) это много для такого задания. Исправила.
2) 4.7 убрала лишнее. Оставила ввод вне декоратора.

2023-06-06 09:57 UTC, IlyaOrlov approved these changes
1. Теперь всё классно. Чем меньше повторяющегося кода - тем лучше.
2. Красота! И в коде, в выводе!
Всё отлично! Зачтено.

2023-06-06 09:57 UTC, merged